### ISSUE TITLE
Updated Dockerfile

### ISSUE THREAD

**Issue by andrewschmidt-a** [shadow/shadow#1015]
**State your question concisely**
Could someone look at my Dockerfile and tell me if I installed shadow correctly?
https://github.com/andrewschmidt-a/shadow-docker

**Describe your current understanding of Shadow as it relates to your question**
Currently there is some docker layers that are published as a tarball. Its running a really old version of fedora container and I needed to install some newer packages to work alongside of shadow. When I realized I was practically updating the whole os in my docker image I decided to start with a new base image. 

I couldn't find the dockerfile that georgetown used to create the original base layer so I just recreated it from the steps.

**Describe which parts you are unsure about**
Not sure if I got all the sysctl settings configured right. I couldnt actually set them in the docker image itself (permission denied)

Also I have the proposed hotfix for https://github.com/shadow/shadow/issues/805 included

**Comment by stevenengler** [comment]
You're right that the Docker instructions are very out of date, and need to be updated.

> I couldn't find the dockerfile that georgetown used to create the original base layer so I just recreated it from the steps.

I don't think that image was created from a Dockerfile.

> Could someone look at my Dockerfile and tell me if I installed shadow correctly?

It looks okay to me. The main question is, do the tests pass and does Shadow run? If so, then it's probably good. The sysctl settings affect the kernel and usually need to be made outside of the container, so you can't put them in a Dockerfile. Some sysctl options are namespaced so you might be able to set some per-container, but I don't know which ones.

I'm not sure if you're asking for general suggestions to improve your Dockerfile, but if you are, here are some suggestions:

1. Your Dockerfile skips running Shadow's tests. The tests are very important, especially when running in a container, but maybe these are better run on each user's system after they start a container.
2. You may want to `rm -r shadow/build` after you install it to reduce the number of files in your image.
3. It's usually best to reduce the number of RUN steps to reduce the number of layers.
4. When you download an external file in your Dockerfile (for example with wget), you should check the hash to make sure it's the expected file and not a wrong or malicious file. This also helps make your Dockerfile reproducible.
5. Many of your RUN steps run under the root user when they don't need to. For example you build tgen as the root user, when it might be better to build it as your shadow user.
6. You install the same package in multiple locations, and you install some that I don't think are needed (such as the `kernel-devel` package).
