### ISSUE TITLE
Sendto/write/recvfrom/read buffer sizes are limited by SYSCALL_IO_BUFSIZE

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#1027]
**Is your feature request related to a problem? Please describe.**
Calls to sendto/write/recvfrom/read inside a plugin will never send/receive more than [`SYSCALL_IO_BUFSIZE`](https://github.com/shadow/shadow/blob/5079bb55ecc7ad7574389fadfe0d6eed7f56fcf9/src/main/host/syscall/protected.h#L63) bytes (currently 16 KiB) per syscall. ([Example](https://github.com/shadow/shadow/blob/5079bb55ecc7ad7574389fadfe0d6eed7f56fcf9/src/main/host/syscall/unistd.c#L216-L219).) This constant limits the amount of data that has to be copied between the process and Shadow. The Linux kernel can transfer buffer sizes much larger than this if the fd has bytes available.

**Describe the solution you'd like**
Since Shadow now uses shared memory more often, we can consider increasing or removing this buffer size limit.

**Describe alternatives you've considered**
We discussed the following:

1. Increasing `SYSCALL_IO_BUFSIZE` to ~1 MiB.
2. Within Shadow's syscall handler, loop and send the given buffer in `SYSCALL_IO_BUFSIZE`-sized chunks.
3. Within Shadow, determine how much space the fd can accept, and only copy at most that amount.

Option 2 is probably not worthwhile, and instead should choose option 3 over option 2.

**Comment by robgjansen** [comment]
After some discussion, we decided that we want Item 3, and then also use item 1 as a backstop. We think the backstop can be somewhere in the range [1 MiB, 100 MiB] (I think 10 MiB is a good option).
