### ISSUE TITLE
Implement new UNIX socket (AF_UNIX) descriptor type

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#1035]
After completing [milestone 23](https://github.com/shadow/shadow/milestone/23), we should have a clear way to implement a new UNIX descriptor type in rust, using the new rust-based UDP socket as an example. We'll need to hook up the various syscalls that can operate on sockets to the new UNIX socket class.

**Comment by stevenengler** [comment]
We now have a `UnixSocket` type for unix sockets. Only abstract and socketpair() unix sockets are currently supported.
