### ISSUE TITLE
CMAKE_BUILD_TYPE shouldn't be an environment variable

### ISSUE THREAD

**Issue by rwails** [shadow/shadow#1121]
**Describe the issue**

Shadow's cmake build doesn't handle `CMAKE_BUILD_TYPE` variable correctly. Currently, the logic is:

https://github.com/shadow/shadow/blob/d2fc305e3c4e06005118b0c6d98c942e653c0d45/CMakeLists.txt#L113-L125

However, if cmake is called with `-DCMAKE_BUILD_TYPE=Debug` (which is the ordinary way to set cmake build types), this variable *is not* stored in `$ENV{CMAKE_BUILD_TYPE}`. It is stored in `CMAKE_BUILD_TYPE` (n.b. this variable isn't an environment variable).

I recommend that the build script be changed to modify the CMAKE_BUILD_TYPE cache variable, and the `CMAKE_BUILD_TYPE` variable be checked instead.

We also don't support the `RelWithDebInfo` build type, but we probably should.

This affects both the `master` and `dev` branches. I don't know how Rust is setup to grab these variables.

**Comment by robgjansen** [comment]
The bigger issue here is that @rwails isn't using the setup script, which is the recommended and documented way to build Shadow. This makes we wonder if we should just remove the setup script entirely, and instead just document how to build, install, and test by calling cmake and ctest directly.

**Comment by RWails** [comment]
Sampling some other large open source projects online for inspiration...

Some projects wrap cmake for easier setup:

<https://github.com/monero-project/monero/blob/master/Makefile>

Others don't:

<https://clang.llvm.org/get_started.html>
<https://github.com/CoatiSoftware/Sourcetrail>
<https://github.com/apache/arrow/blob/master/docs/source/developers/cpp/building.rst>
<https://github.com/microsoft/STL#how-to-build-with-a-native-tools-command-prompt>
<https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/build_linux.md#running-cmake>
<https://github.com/google/leveldb#building>

I don't see anything wrong with supporting the setup script! But if we want to keep the script, I think it makes sense to invoke `cmake` as if it was being called from the command line.

**Comment by stevenengler** [comment]
> I don't know how Rust is setup to grab these variables.

The Rust code is built in release or debug mode depending on the `CMAKE_BUILD_TYPE` variable.

https://github.com/shadow/shadow/blob/551c65c17c835723ad4bda52d7cfe78036809e1f/src/main/CMakeLists.txt#L30-L38

https://github.com/shadow/shadow/blob/551c65c17c835723ad4bda52d7cfe78036809e1f/src/main/CMakeLists.txt#L205

The actual Rust library that Shadow links to does not use this variable, but instead lets CMake choose to link to the debug version or release version depending on however CMake internally tracks whether it's building a debug or release version.

https://github.com/shadow/shadow/blob/551c65c17c835723ad4bda52d7cfe78036809e1f/src/main/CMakeLists.txt#L217-L219

If the `CMAKE_BUILD_TYPE` variable doesn't match with however CMake internally keeps track of whether its building the debug or release version, then that would be a problem for the Rust code as it would build for example in Release mode, but link a Debug mode version instead.

**Comment by sporksmith** [comment]
As a recent VS Code convert this issue is suddenly more relevant to me ;). I think I have it fixed locally; will send out a PR shortly
