### ISSUE TITLE
waitpid is O(# children), resulting in O((# sim processes)^2) in thread_ptrace

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#1134]
Broken out from #1041 

Using a [syscall-heavy-microbenchmark](https://github.com/sporksmith/phantom-paper/blob/realtime-experiment/experiments/realtime/workload.c), I did some perf-based profiling of ptrace mode.

Without cpu-pinning, we spend 20% of our time in [wait_consider_task inside the kernel](https://github.com/torvalds/linux/blob/219d54332a09e8d8741c1e1982f5eae56099de85/kernel/exit.c#L1279). It turns out that `waitpid` ends up using the `wait4` syscall, which ends up in [do_wait](https://github.com/torvalds/linux/blob/219d54332a09e8d8741c1e1982f5eae56099de85/kernel/exit.c#L1441), which checks *every* child and *every* ptraced process; not just the one whose pid was supplied.

From `perf report` (there are 4 symmetric worker threads; the total counts are ~4x these):

```
-    7.21%     6.55%         24363  worker-3         [kernel.vmlinux]         [k] wait_cons▒
   - 6.55% __GI___clone (inlined)                                                          ▒
        start_thread                                                                       ▒
        worker_run                                                                         ▒
      - event_execute                                                                      ▒
         - 6.54% process_continue                                                          ▒
              thread_resume                                                                ▒
              _thread_cleanupSysCallCondition (inlined)                                    ▒
            - threadptrace_resume                                                          ▒
               - 6.41% _threadptrace_doAttach (inlined)                                    ▒
                    _threadptrace_nextChildState                                           ▒
                    __waitpid                                                              ▒
                    entry_SYSCALL_64                                                       ▒
                    do_syscall_64                                                          ▒
                    __x64_sys_wait4                                                        ▒
                    __do_sys_wait4                                                         ▒
                  - kernel_wait4                                                           ▒
                     - 6.06% do_wait                                                       ▒
                          6.03% wait_consider_task 
```

We spend less time here with cpu-pinning enabled. I suspect this is because `do_wait` actually does a semi-busy wait of checking all children and then [calling schedule](https://github.com/torvalds/linux/blob/219d54332a09e8d8741c1e1982f5eae56099de85/kernel/exit.c#L1485). i.e. it can get repeatedly woken up again, find there's still no children ready, and then go back to sleep. With cpu-pinning enabled, the waiting thread won't be able to be scheduled again (to do a futile linear scan) until the child has actually stopped and relinquished that cpu.

With cpu-pinning enabled:

```
-    0.75%     0.63%          1690  worker-1  [kernel.vmlinux]  [k] wait_consider_task 
     0.63% __GI___clone (inlined)                                                          ▒
        start_thread                                                                       ▒
        worker_run                                                                         ▒
        event_execute                                                                      ▒
        process_continue                                                                   ▒
        thread_resume                                                                      ▒
        _thread_cleanupSysCallCondition (inlined)                                          ▒
      - threadptrace_resume                                                                ▒
         - 0.61% _threadptrace_doAttach (inlined)                                          ▒
              _threadptrace_nextChildState                                                 ▒
              __waitpid                                                                    ▒
              entry_SYSCALL_64                                                             ▒
              do_syscall_64                                                                ▒
              __x64_sys_wait4                                                              ▒
              __do_sys_wait4                                                               ▒
            - kernel_wait4                                                                 ▒
               - 0.58% do_wait                                                             ▒
                    0.57% wait_consider_task                                               ▒
+    0.72%     0.59%          1599  worker-3  [kernel.vmlinux]  [k] wait_consider_task     ▒
+    0.71%     0.59%          1599  worker-2  [kernel.vmlinux]  [k] wait_consider_task     ▒
+    0.71%     0.59%          1600  worker-0  [kernel.vmlinux]  [k] wait_consider_task
```

While these numbers are less worrisome, the above is all with 256 hosts (each with 1 simulated process). If we double the number of hosts doing the same amount of work, we should expect that the number of calls to `waitpid` will be doubled, *and* its cost will be doubled. i.e. we're going to see quadratic growth here.

Experimentally, doubling the # of hosts to 512:

```
-    1.48%     1.31%          5469  worker-1  [kernel.vmlinux]  [k] wait_consider_task     ◆
     1.31% __GI___clone (inlined)                                                          ▒
        start_thread                                                                       ▒
        worker_run                                                                         ▒
      - event_execute                                                                      ▒
         - 1.31% process_continue                                                          ▒
              thread_resume                                                                ▒
              _thread_cleanupSysCallCondition (inlined)                                    ▒
            - threadptrace_resume                                                          ▒
               - 1.27% _threadptrace_doAttach (inlined)                                    ▒
                    _threadptrace_nextChildState                                           ▒
                    __waitpid                                                              ▒
                    entry_SYSCALL_64                                                       ▒
                    do_syscall_64                                                          ▒
                    __x64_sys_wait4                                                        ▒
                    __do_sys_wait4                                                         ▒
                  - kernel_wait4                                                           ▒
                     - 1.21% do_wait                                                       ▒
                          1.21% wait_consider_task                                         ▒
+    1.43%     1.25%          5173  worker-0  [kernel.vmlinux]  [k] wait_consider_task     ▒
+    1.41%     1.23%          5146  worker-3  [kernel.vmlinux]  [k] wait_consider_task     ▒
+    1.34%     1.17%          4885  worker-2  [kernel.vmlinux]  [k] wait_consider_task 
```

As expected, the percentages (cost relative to the rest of the simulation) doubles, and the raw number of samples increases super-linearly (About 3.2x vs the expected 4x).

**Comment by sporksmith** [comment]
Potential solution:

* Fork the plugin (simulated) processes from a thread other than the worker threads (which are the ones that trace the plugins and call `getpid`). This would keep the size of the child-list at 0 instead of growing linearly.
* ptrace-detach inactive simulated processes. This would keep the size of the tracee list at 1 instead of growing linearly. This is already implemented for the work-stealing scheduler (to facilitate migration to other workers)

**Comment by sporksmith** [comment]
nickm @ tor suggested checking whether we could use `pidfd` together with `epoll` instead of calling `waitpid`.

I'm not very familiar with `pidfd`, but according to [this article](https://lwn.net/Articles/801319/), "There do not appear to be any use cases for pidfds that refer to an individual thread for now; such a feature could be added in the future if the need arises." So minimally we'd need to get that functionality added. Additionally the `ptrace` documentation all specifically says to use `getpid`, so specifically supporting ptrace-stops might require some kernel changes as well.

**Comment by sporksmith** [comment]
I extended this out a bit further to 2048 hosts, using perf stats and probe counts rather than a full report (which was getting unmanageable at 1024 hosts).

I installed probes on the symbols `kernel_wait4` and `wait_consider_task`. Given my understanding, I expect # of calls to `kernel_wait4` to grow linearly with # of simulated processes, but `wait_consider_task` to grow quadratically.

Setup:

```
sudo perf probe --add kernel_wait4
sudo perf probe --add wait_consider_task
ulimit -n 100000
```

256 hosts:

```
sudo chrt -f 1 perf stat -e probe:wait_consider_task -e probe:kernel_wait4 /home/jnewsome/.shadow/bin/shadow --interpose-method=ptrace -w 4 -t host --pin-cpus config.xml > ptrace
** Starting Shadow v1.13.2-1775-g0e13d3f4 2021-03-02--10:15:20 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)

 Performance counter stats for '/home/jnewsome/.shadow/bin/shadow --interpose-method=ptrace -w 4 -t host --pin-cpus config.xml':

        87,092,767      probe:wait_consider_task                                    
         2,679,751      probe:kernel_wait4                                          

      31.451961167 seconds time elapsed

      28.468135000 seconds user
      95.667249000 seconds sys
```

512 hosts:

```
sudo chrt -f 1 perf stat -e probe:wait_consider_task -e probe:kernel_wait4 /home/jnewsome/.shadow/bin/shadow --interpose-method=ptrace -w 4 -t host --pin-cpus config.xml > ptrace
** Starting Shadow v1.13.2-1775-g0e13d3f4 2021-03-02--10:15:20 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)

 Performance counter stats for '/home/jnewsome/.shadow/bin/shadow --interpose-method=ptrace -w 4 -t host --pin-cpus config.xml':

       345,640,552      probe:wait_consider_task                                    
         5,359,513      probe:kernel_wait4                                          

      67.123361929 seconds time elapsed

      58.073063000 seconds user
     207.530526000 seconds sys
```

1024 hosts:
```
sudo chrt -f 1 perf stat -e probe:wait_consider_task -e probe:kernel_wait4 /home/jnewsome/.shadow/bin/shadow --interpose-method=ptrace -w 4 -t host --pin-cpus config.xml > ptrace
** Starting Shadow v1.13.2-1775-g0e13d3f4 2021-03-02--10:15:20 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)

 Performance counter stats for '/home/jnewsome/.shadow/bin/shadow --interpose-method=ptrace -w 4 -t host --pin-cpus config.xml':

     1,376,763,973      probe:wait_consider_task                                    
        10,718,689      probe:kernel_wait4                                          

     158.438467348 seconds time elapsed

     114.483939000 seconds user
     512.651689000 seconds sys
```

2048 hosts:

```
sudo chrt -f 1 perf stat -e probe:wait_consider_task -e probe:kernel_wait4 /home/jnewsome/.shadow/bin/shadow --interpose-method=ptrace -w 4 -t host --pin-cpus config.xml > ptrace
** Starting Shadow v1.13.2-1775-g0e13d3f4 2021-03-02--10:15:20 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)

 Performance counter stats for '/home/jnewsome/.shadow/bin/shadow --interpose-method=ptrace -w 4 -t host --pin-cpus config.xml':

     5,496,248,211      probe:wait_consider_task                                    
        21,437,296      probe:kernel_wait4                                          

     445.069738499 seconds time elapsed

     237.692532000 seconds user
    1523.179200000 seconds sys
```

![image](https://user-images.githubusercontent.com/179146/109881522-0e05a680-7c3e-11eb-8fbc-918401bb4617.png)

This seems to validate my understanding so far. # of calls to `wait_consider_task` is clearly ~quadratic, and by 2048 simulated processes overall kernel time (`sys`) is very clearly super-linear, and elapsed time is becoming noticeably super-linear.

**Comment by sporksmith** [comment]
Forking from a proxy thread (#1143) seems to have the desired effect. We still need to do a single `waitpid` from the fork-proxy thread as part of the detach process, and will get the quadratic behavior there. Subsequent `waitpid`s now appear to be constant time; as expected for a small number of hosts this change is slightly more expensive. By 2048 hosts though it becomes a substantial win.

Primed' numbers are with the fork-proxy:

hosts | wait_consider_task | wait_consider_task' | kernel_wait4 | kernel_wait4' | elapsed | elapsed' | user | user' | sys | sys'
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
256 | 87,092,767 | 7,845,176 | 2,679,751 | 7,800,426 | 31 | 36.52642967 | 28 | 34.819797 | 95 | 109.031216
512 | 345,640,552 | 15,716,584 | 5,359,513 | 15,600,527 | 67 | 71.26890564 | 58 | 71.542191 | 207 | 211.077523
1024 | 1,376,763,973 | 31,651,081 | 10,718,689 | 31,201,213 | 158 | 143.2743868 | 114 | 144.733005 | 512 | 423.629688
2048 | 5,496,248,211 | 63,867,558 | 21,437,296 | 62,401,974 | 445 | 289.3670742 | 237 | 286.385822 | 1523 | 862.098542

**Comment by sporksmith** [comment]
Looked a bit more into how we could fix this with a kernel patch.

`do_wait` *does* [look up the target task](https://elixir.bootlin.com/linux/latest/source/kernel/exit.c#L1450) in a global data structure (before doing the linear scans).

It looks like we should be able to validate the caller using `parent` and `real_parent` on the [target task struct](https://elixir.bootlin.com/linux/latest/source/include/linux/sched.h#L863)

So I *think* [do_wait_thread](https://elixir.bootlin.com/linux/latest/source/kernel/exit.c#L1392) and [ptrace_do_wait](https://elixir.bootlin.com/linux/latest/source/kernel/exit.c#L1406) can just call `wait_consider_task` with the target task instead of looping, when there's a non-null target task.

**Comment by robgjansen** [comment]
> So I think do_wait_thread and ptrace_do_wait can just call wait_consider_task with the target task instead of looping, when there's a non-null target task.

Seems like a simple enough kernel change that we ought to be able to get it through the kernel patch gauntlet. :)

**Comment by sporksmith** [comment]
I got in touch with kernel dev Oleg Nesterov, who seems amenable to the patch and gave a couple pointers:

> I don't think we need to change do_wait_thread/ptrace_do_wait, and we don't
need get_pid_task...
>
> I think we should simply do wait_consider_task() on pid_task(wo_pid, PIDTYPE_PID)
before the main do/while_each_thread loop. Yes, we need to check parent/real_parent
first. Don't forget about __WNOTHREAD.

**Comment by sporksmith** [comment]
Candidate kernel patch: [0001-do_wait-make-PIDTYPE_PID-case-O-1-instead-of-O-n.patch.txt](https://github.com/shadow/shadow/files/6097901/0001-do_wait-make-PIDTYPE_PID-case-O-1-instead-of-O-n.patch.txt)

I remeasured with 2048 hosts, using `time` (didn't go through the process of making `perf` work with my custom kernel).

Measured at current `dev` 551c65c17c835723ad4bda52d7cfe78036809e1f

Vanilla kernel, ptrace:
```
ulimit -n 100000
sudo chrt -f 1 time /home/jnewsome/.shadow/bin/shadow --interpose-method=ptrace -w 4 -t host --pin-cpus config.xml > ptrace.hoston
** Starting Shadow v1.13.2-1781-g551c65c1 2021-03-03--16:27:47 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)
132.38user 338.44system 2:13.28elapsed 353%CPU (0avgtext+0avgdata 180692maxresident)k
39576inputs+164736outputs (72major+957621minor)pagefaults 0swaps
```

o1-waitpid kernel, ptrace:
```
ulimit -n 100000

sudo chrt -f 1 time /home/jnewsome/.shadow/bin/shadow --interpose-method=ptrace -w 4 -t host --pin-cpus config.xml > ptrace.hosto1
** Starting Shadow v1.13.2-1781-g551c65c1 2021-03-03--16:27:47 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)
154.33user 146.44system 1:21.56elapsed 368%CPU (0avgtext+0avgdata 180724maxresident)k
1192inputs+164752outputs (1159major+418072minor)pagefaults 0swaps
```

`sys` and `elapsed` time are quite a bit improved, for some reason `user` time has increased. Maybe time is shifting from the kernel into `waitpid` w/`WNOHANG` spin loops?

The increase seems to carry over to preload-mode too, though, including a bump in elapsed time:

Vanilla kernel, preload:
```
sudo chrt -f 1 time /home/jnewsome/.shadow/bin/shadow --interpose-method=preload -w 4 -t host --pin-cpus config.xml > preload.hoston
** Starting Shadow v1.13.2-1781-g551c65c1 2021-03-03--16:27:47 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)
123.54user 70.43system 0:50.05elapsed 387%CPU (0avgtext+0avgdata 405680maxresident)k
0inputs+165096outputs (0major+578215minor)pagefaults 0swaps
```

o1-waitpid kernel, preload:
```
sudo chrt -f 1 time /home/jnewsome/.shadow/bin/shadow --interpose-method=preload -w 4 -t host --pin-cpus config.xml > preload.hosto1
** Starting Shadow v1.13.2-1781-g551c65c1 2021-03-03--16:27:47 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)
144.78user 85.83system 1:03.88elapsed 361%CPU (0avgtext+0avgdata 402372maxresident)k
```

I'm not sure why it affects preload mode at all. I'm planning to pick this back up on Monday and re-measure; maybe see what it takes to make `perf` work. Also this is using the default ubuntu kernel as a baseline; I should use the self-compiled staging kernel without my patch to get a better apples-to-apples comparison.

**Comment by sporksmith** [comment]
Meaasured a new baseline, using my custom built kernel without the o1-waitpid patch instead of the Ubuntu distro kernel. This baseline is indeed a bit slower, making the patch a more unambiguous win.

Comparison with new baseinle and o1-waitpid #'s pasted from above:

baseline, ptrace:
```
# sudo chrt -f 1 time /home/jnewsome/.shadow/bin/shadow --interpose-method=ptrace -w 4 -t host --pin-cpus config.xml > ptrace.hoston
** Starting Shadow v1.13.2-1781-g551c65c1 2021-03-03--16:27:47 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)
143.46user 346.45system 2:29.03elapsed 328%CPU (0avgtext+0avgdata 180824maxresident)k
39680inputs+164760outputs (388major+414148minor)pagefaults 0swaps
```

o1-waitpid, ptrace (from above):
```
sudo chrt -f 1 time /home/jnewsome/.shadow/bin/shadow --interpose-method=ptrace -w 4 -t host --pin-cpus config.xml > ptrace.hosto1
** Starting Shadow v1.13.2-1781-g551c65c1 2021-03-03--16:27:47 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)
154.33user 146.44system 1:21.56elapsed 368%CPU (0avgtext+0avgdata 180724maxresident)k
1192inputs+164752outputs (1159major+418072minor)pagefaults 0swaps
```

There's still a minor bump in `user` time, but not as much as in the previous comparison.

baseline, preload:
```
# sudo chrt -f 1 time /home/jnewsome/.shadow/bin/shadow --interpose-method=preload -w 4 -t host --pin-cpus config.xml > preload.hoston
** Starting Shadow v1.13.2-1781-g551c65c1 2021-03-03--16:27:47 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)
146.38user 83.76system 1:03.35elapsed 363%CPU (0avgtext+0avgdata 402984maxresident)k
0inputs+165096outputs (2292major+575799minor)pagefaults 0swaps
```

o1-waitpid, preload (from above):
```
sudo chrt -f 1 time /home/jnewsome/.shadow/bin/shadow --interpose-method=preload -w 4 -t host --pin-cpus config.xml > preload.hosto1
** Starting Shadow v1.13.2-1781-g551c65c1 2021-03-03--16:27:47 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)
144.78user 85.83system 1:03.88elapsed 361%CPU (0avgtext+0avgdata 402372maxresident)k
```

As expected, the patch doesn't effect preload.

**Comment by sporksmith** [comment]
Relevant LKML threads:
* v1: https://lkml.org/lkml/2021/3/9/204
* v2: https://lkml.org/lkml/2021/3/9/875
* v3: https://lkml.org/lkml/2021/3/9/1134

**Comment by sporksmith** [comment]
Quick comparison of no mitigations vs fork-proxy workaround vs patched kernel.
Measured on my plugged-in w530. TLDR, syscall microbenchmark with 4k simulated hosts:

test | elapsed
-- | --
unpatched kernel | 8:35
unpatched kernel, with workarounds | 4:55
patched kernel | 2:54

Details:

\#1171 mitigates the issue by roughly a linear factor of the # of workers,
pushing the cross-over point of when the "fork proxy" workaround becomes a win
out to around 2k processes on my machine, so measuring at 4k processes.

As always, need to increase open file limit:
```
ulimit -n 100000
```

Version info:
```
$ uname -a
Linux vusiri 5.12.0-rc1-staging-testing+ #2 SMP Sun Mar 14 12:38:53 CDT 2021 x86_64 x86_64 x86_64 GNU/Linux
$ ~/.shadow/bin/shadow --version
Shadow v1.13.2-1860-g53597f01 2021-03-13--13:25:45 running GLib v2.56.4 and IGraph v0.7.1
Shadow was built from branch dev on 2021-03-14--13:47:25 in Release mode with compile options: -ggdb;-fno-omit-frame-pointer;-Wreturn-type;-Wswitch;-O3 and link options: -Wl,--no-as-needed
For more information, visit https://shadow.github.io or https://github.com/shadow
```

unpatched kernel, without workarounds:
```
# sudo chrt -f 1 time /home/jnewsome/.shadow/bin/shadow --interpose-method=ptrace -w 4 -t host --pin-cpus --disable-o-n-waitpid-workarounds config.xml > /dev/null
** Starting Shadow v1.13.2-1860-g53597f01 2021-03-13--13:25:45 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)
356.46user 1480.92system 8:35.18elapsed 356%CPU (0avgtext+0avgdata 317132maxresident)k
53424inputs+98312outputs (511major+820944minor)pagefaults 0swaps
```

unpatched kernel, with workarounds:
```
# sudo chrt -f 1 time /home/jnewsome/.shadow/bin/shadow --interpose-method=ptrace -w 4 -t host --pin-cpus config.xml > /dev/null
** Starting Shadow v1.13.2-1860-g53597f01 2021-03-13--13:25:45 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)
451.02user 652.15system 4:55.38elapsed 373%CPU (0avgtext+0avgdata 316268maxresident)k
0inputs+98312outputs (1743major+827945minor)pagefaults 0swaps
```

Patched kernel:
```
# uname -a
Linux vusiri 5.12.0-rc1-o1waitpid+ #5 SMP Sun Mar 14 13:08:20 CDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```

patched kernel, without workarounds:
```
sudo chrt -f 1 time /home/jnewsome/.shadow/bin/shadow --interpose-method=ptrace -w 4 -t host --pin-cpus --disable-o-n-waitpid-workarounds config.xml > /dev/null
** Starting Shadow v1.13.2-1860-g53597f01 2021-03-13--13:25:45 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)
363.10user 266.67system 2:54.94elapsed 359%CPU (0avgtext+0avgdata 316332maxresident)k
896inputs+98312outputs (2403major+829693minor)pagefaults 0swaps
```

patched kernel, with workarounds:
(for completeness; no reason to ever run in this configuration)
```
# sudo chrt -f 1 time /home/jnewsome/.shadow/bin/shadow --interpose-method=ptrace -w 4 -t host --pin-cpus config.xml > /dev/null
** Starting Shadow v1.13.2-1860-g53597f01 2021-03-13--13:25:45 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)
471.17user 667.86system 5:12.81elapsed 364%CPU (0avgtext+0avgdata 312452maxresident)k
0inputs+98312outputs (1181major+827700minor)pagefaults 0swaps
```

**Comment by sporksmith** [comment]
The O(1) waitpid kernel patch appears to be on track for acceptance.

In the meantime, #1238 appears to provide an adequate workaround, by scaling the number of worker threads with the number of tracees. This adds memory and context-switching overhead from the extra threads, but is significantly faster than the "forkproxy" workaround, which requires ptrace detaching and reattaching to keep the tracee list small.
