### ISSUE TITLE
Possible issues when running Tor

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#1136]
Running a minimal Tor network config in phantom  at b72c1cf24e1651fb675d429ba857d3a60d4d5edc produces the following warnings in the `shadow.log` file:

1. `[clone.c:69] [syscallhandler_clone] Unhandled clone flags 0x80000`
2. `[ioctl.c:90] [syscallhandler_ioctl] We do not support ioctl request 35147 on descriptor 12`
3. `[protected.c:73] [_syscallhandler_validateDescriptor] descriptor handle '100' is closed`  
(Is not really an issue - covered by #1101)
4. `[socket.c:1201] [syscallhandler_socket] unsupported socket domain "1", we only support AF_INET`  
(I _think_ Tor can function without using UNIX sockets - covered by #1035.)
5. The dirauth seems to go to sleep on a futex at 3 minutes into the sim, and never wakes up again:

```
00:00:17.114349 [thread-0] 00:03:03.250000000 [debug] [4uthority~100.0.0.1] [syscall_handler.c:135] [_syscallhandler_pre_syscall] SYSCALL_HANDLER_PRE(tor,pid=1000): handling syscall 202 futex
00:00:17.114350 [thread-0] 00:03:03.250000000 [debug] [4uthority~100.0.0.1] [futex.c:146] [syscallhandler_futex] futex called with addr=0x22bde68 op=128 (operation=0 and options=128) and val=3
00:00:17.114353 [thread-0] 00:03:03.250000000 [debug] [4uthority~100.0.0.1] [futex.c:159] [syscallhandler_futex] Handling FUTEX_WAIT operation 0
00:00:17.114356 [thread-0] 00:03:03.250000000 [debug] [4uthority~100.0.0.1] [futex.c:48] [_syscallhandler_futexWaitHelper] Futex value is 3, expected value is 3
00:00:17.114357 [thread-0] 00:03:03.250000000 [debug] [4uthority~100.0.0.1] [futex.c:89] [_syscallhandler_futexWaitHelper] Dynamically created a new futex object for futex addr 0x3e80000022bde68
00:00:17.114360 [thread-0] 00:03:03.250000000 [debug] [4uthority~100.0.0.1] [futex.c:96] [_syscallhandler_futexWaitHelper] Futex blocking for wakeup without timeout
00:00:17.114361 [thread-0] 00:03:03.250000000 [debug] [4uthority~100.0.0.1] [syscall_handler.c:149] [_syscallhandler_post_syscall] SYSCALL_HANDLER_POST(tor,pid=1000): syscall 202 futex result: state=BLOCK code=0(n/a) in 0.000012 seconds
00:00:17.114366 [thread-0] 00:03:03.250000000 [debug] [4uthority~100.0.0.1] [syscall_condition.c:248] [_syscallcondition_logListeningState] Process 4uthority.tor.1000 thread 0x29fc710 started listening for status on futex 0x3e80000022bde68
```

**Comment by sporksmith** [comment]
> [clone.c:69] [syscallhandler_clone] Unhandled clone flags 0x80000

Huh, I don't see such a clone flag, unless some trailing 0's got dropped somehow:

```
$ grep -R CLONE_.*0x80000  /usr/include
/usr/include/linux/sched.h:#define CLONE_IO		0x80000000	/* Clone io context */
/usr/include/bits/sched.h:# define CLONE_IO	0x80000000	/* Clone I/O context.  */
/usr/include/x86_64-linux-gnu/bits/sched.h:# define CLONE_IO	0x80000000	/* Clone I/O context.  */
```

> [memory_manager.rs:924] [shadow_rs::host::memory_manager] mprotect: ENOMEM: Out of memory

One of the reasons mprotect can return ENOMEM is if the address range isn't actually mapped. The relevant code in memory_manager has some fiddly pointer arithmetic; I checked again and couldn't spot a mistake, but this could probably use better test coverage.

> Also, at the end of the simulation, the plugin processes are still running and Shadow has to send them signals to shut them down.

threadptrace_terminate sends SIGKILL and then waits on the pid. Interestingly, a SIGKILL will kill the whole process, not just the receiving thread. I'd *expect* the extra signals to be redundant and to still be able to `waitpid` on each thread, but maybe that's not the case.

We should probably add a test case covering this scenario. I don't think we have any with threads that are still running when shadow terminates the simulation.

**Comment by robgjansen** [comment]
For the clone issue, I think the leading zeros got dropped because we are not zero-padding the format string. So on my system 80000 equates to the following:
```
#define CLONE_SETTLS	0x00080000	/* create a new TLS for the child */
```

**Comment by sporksmith** [comment]
If I'm reading correctly, unhandled flags still get passed through to the native `clone` call, which looks like the right way to handle  `CLONE_SETTLS`. If that's the case we should just squelch the warning for that flag (perhaps by |'ing into handled_flags with a comment that we don't need to do anything with it other than pass to the native `clone` call)

**Comment by robgjansen** [comment]
I broke out a ptrace issue in #1166 and a memory manager issue in #1167.
