### ISSUE TITLE
Coverage build broken in CI

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#1152]
We thought this might be due to a recent [changeover to LLVM 12](https://github.com/rust-lang/rust/pull/81451) in the rust nightly, but pinning to an older nightly [didn't seem to fix it](https://github.com/shadow/shadow/pull/1150).

Mitigated by disabling coverage in #1151

**Comment by stevenengler** [comment]
This issue does appear to be the change to LLVM 12, but I made a mistake when I tried to re-use an older Rust nightly version. So since using an older Rust nightly version does fix the issue, we pinned it to an earlier version in #1153 and the coverage tests now work again.
