### ISSUE TITLE
Allow variable suffixes for bandwidth config values

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#1161]
Currently, Shadow interprets the values given in the `bandwidthup` and `bandwidthdown` config attributes as `KiB/s`.

https://github.com/shadow/shadow/blob/482458a2ff0573d4b5eec0c588852af46aead24a/src/main/core/master.c#L376-L377

We should do something like [TGen does in it's `tgenoptionparser_parseBytes` function](https://github.com/shadow/tgen/blob/47d5eb385195eb22a87b05984116447ad32ef8d7/src/tgen-optionparser.c#L197), where
- a raw integer is interpreted as bytes, and
- a suffix can be given to instruct Shadow how to interpret the config value.

**Comment by stevenengler** [comment]
This behaviour is now supported in the new Rust version. It differs slightly from the TGen parsing, but is very similar. The main differences are that the Shadow parsing is case-sensitive, and Shadow uses bits-per-second rather than bytes-per-second for bandwidth.
