### ISSUE TITLE
Remove 'preloadPath' configuration option

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#1215]
Since this functionality can be set with the `environment` option, we don't need this extra 'preloadPath' option anymore.

**Comment by robgjansen** [comment]
Do you mean the preload path under each `<host>` element (e.g., where we set `libshadow-preload-tor.so`), or the preload attribute on the `<shadow>` element (where we set `libshadow-shim.so`)? I agree we can remove the former; the latter needs to be set for every process that shadow forks, so we probably want to keep that one (and insert it into the environment like we do now) to avoid launching a sim without it.

**Comment by stevenengler** [comment]
Why can't we remove both? Can't the user specify the `LD_PRELOAD` in the environment list? Why do we need a separate option specifically for `LD_PRELOAD`?

**Comment by stevenengler** [comment]
The decision we came to is that Shadow should locate the shim automatically using the rpath, so we don't see a need for this option anymore.
