### ISSUE TITLE
Organize and remove legacy options

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#1220]
We've collected a set of options that may be rarely used. As we are migrating to a new option and config format for Shadow 2.0, we are going to remove legacy options that we don't think are that useful for most users.

Here are the legacy options I am pretty confident we can remove:

```
Simulation Examples
  --test                                  Run basic benchmark tests
  --tgen                                  PLACEHOLDER - Run basic data transfer simulation

System Options
  --cpu-precision=TIME                    round measured CPU delays to the nearest TIME, in microseconds (negative value to disable fuzzy CPU delays) [200]
  --cpu-threshold=TIME                    TIME delay threshold after which the CPU becomes blocked, in microseconds (negative value to disable CPU delays) (experimental!) [-1]
  --tcp-ssthresh=N                        Set TCP ssthresh value instead of discovering it via packet loss or hystart [0]
  --tcp-windows=N                         Initialize the TCP send, receive, and congestion windows to N packets [10]

Application Options:
  -p, --preload=VALUE                     LD_PRELOAD environment VALUE to use for function interposition (/path/to/lib:...) [None]
```

I'm less confident about these, and we might want to keep them around. How about we move them to the "Experimental" section?

```
System Options
  --interface-batch=TIME                  Batch TIME for network interface sends and receives, in microseconds [5000]
  --interface-buffer=N                    Size of the network interface receive buffer, in bytes [1024000]
  --interface-qdisc=QDISC                 The interface queuing discipline QDISC used to select the next sendable socket ('fifo' or 'rr') ['fifo']
  --socket-recv-buffer=N                  Initialize the socket receive buffer to N bytes [174760]
  --socket-send-buffer=N                  Initialize the socket send buffer to N bytes [131072]
```

These we do want, but I would move them to the "Experimental" section too:

```
Application Options:
  -r, --runahead=TIME                     If set, overrides the automatically calculated minimum TIME workers may run ahead when sending events between nodes, in milliseconds [0]
  -t, --scheduler-policy=SPOL             The event scheduler's policy for thread synchronization ('thread', 'host', 'steal', 'threadXthread', 'threadXhost') ['steal']
  -n, --interpose-method=METHOD           Which interposition method to use ('hybrid', 'preload', 'ptrace') ['ptrace']
  -z, --pin-cpus                          Use experimental CPU pinning
```

I think those options not listed here are still useful to keep.

**Comment by stevenengler** [comment]
@robgjansen Shadow currently only supports the `reno` value for `--tcp-congestion-control`, should we remove that option as well?

**Comment by sporksmith** [comment]
>   -z, --pin-cpus

I assume we want to enable this by default? If so we'll need to explicitly disable it in our shadow_test macro to avoid them all pinning to the same core.

**Comment by robgjansen** [comment]
Steven and I just discussed that removing the reno option makes sense.

It's looking like it will be best to enable `--pin-cpus`  by default, but we probably want a separate issue/PR for that?

**Comment by stevenengler** [comment]
> It's looking like it will be best to enable `--pin-cpus` by default, but we probably want a separate issue/PR for that?

Made this a separate issue in #1271.

**Comment by stevenengler** [comment]
The `--interface-batch` option is unused in the dev branch, so we can remove it as well.

**Comment by stevenengler** [comment]
@robgjansen For the options like `socket-recv-buffer`, `interface-qdisc`, etc that are to be moved to the experimental options, these will no longer be able to be set on a per-host level. These will only be able to be set as the same value for all hosts. Is that what you expect?

**Comment by robgjansen** [comment]
I think the options originally applied to all hosts, so that is consistent with how they worked before.

I suppose we could extend the code so that the options could be set on hosts individually, but I don't think it's worth putting in that work until we think it's needed.

**Comment by stevenengler** [comment]
> I think the options originally applied to all hosts, so that is consistent with how they worked before.
> 
> I suppose we could extend the code so that the options could be set on hosts individually, but I don't think it's worth putting in that work until we think it's needed.

To clarify, the command line options applied to all hosts, but in the configuration file you could specify values for hosts individually. So we can continue to keep the same behaviour (and they will be classified as host options and not experimental options), or we can make them experimental options but you won't be able to set them per-host in the configuration file. I have it implemented both ways in Rust currently. I'm not sure which way you'd prefer.

**Comment by robgjansen** [comment]
> To clarify ...

Thanks, that helps :)

With this in mind, if we're going to keep the options around, I slightly prefer to keep them as host options so that hosts can specify them individually. It's a little heavy handed to require that all hosts use the same values.

**Comment by stevenengler** [comment]
I believe we made all of the changes discussed here in #1278.
