### ISSUE TITLE
Add default single-node topology in case user does not provide one

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#1221]
We decided that if the user does not provide a topology, we'll load in a default one internally stored as a string. We can store such a default topology using something like this:

https://github.com/shadow/shadow/blob/0a62c035b149af060390fdcc669ba45219878a36/src/main/core/support/examples.c#L10-L50

Note, the above should be updated and simplified because some of the attributes no longer exist or are unnecessary.

**Comment by stevenengler** [comment]
We now include a basic topology we're currently calling "plain".

```yaml
topology: plain
```

https://github.com/shadow/shadow/blob/f6f25cd9c21ab9379a6fd3ea46beffd642f35bc8/src/main/core/support/configuration.rs#L671-L697
