### ISSUE TITLE
Error conditions after vfork() cause Shadow to freeze

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#1243]
When running Shadow, it froze (required `SIGKILL` to stop) with the last log line:

```
forking new thread with environment '[snip]', arguments 'test-epoll', and working directory '[snip]'
```

After changing the code to use `fork()` rather than `vfork()`, I could see that the forked process was getting killed by a `SIGSEGV` (`STOPREASON_SIGNAL: 11`). This `SIGSEGV` seems to have been caused by the combination of disabling the RDTSC (with the `PR_TSC_SIGSEGV` option), and then later calling `error()`. I was able to fix this `SIGSEGV` by changing `error()` to `printf()` and then calling `exit(1)`. After these changes, I was able to figure out that the path to my plugin was incorrect so `execvpe()` was failing.

I think we should avoid calling the Shadow logging methods after `prctl()` (when using `fork()` or `vfork()`). I think we should also avoid calling any logging methods (Shadow logging or printf) after `vfork()` since the program is in a delicate state, and it's difficult to debug when things go wrong. If we really want to log, maybe we should instead have a helper program so that we can `vfork()`, immediately `execvpe()`, and then set the remaining options in the helper program which can do another `execvpe()` later to start the plugin.

Edit: We also need to be careful about Shadow in multi-threaded mode. If another thread is in the middle of allocating memory or logging or anything else requiring locks when the vfork happens, the vforked process will hang forever.

**Comment by sporksmith** [comment]
@stevenengler

> We also need to be careful about Shadow in multi-threaded mode. If another thread is in the middle of allocating memory or logging or anything else requiring locks when the vfork happens, the vforked process will hang forever.

I think this is only an issue if we try to take locks in the code between `vfork` and `exec`, right? (which indeed could be an issue if we call something like `printf`, which takes some libc locks)

I think we should be ok if we restrict ourselves to thin syscall wrappers; e.g. things in `man` section 2. AFAICT that makes our best option on error something like `kill(0, SIGABRT)`

**Comment by stevenengler** [comment]
> @stevenengler
> 
> > We also need to be careful about Shadow in multi-threaded mode. If another thread is in the middle of allocating memory or logging or anything else requiring locks when the vfork happens, the vforked process will hang forever.
> 
> I think this is only an issue if we try to take locks in the code between `vfork` and `exec`, right? (which indeed could be an issue if we call something like `printf`, which takes some libc locks)

I think so. I think the biggest one to be careful of is `malloc()`. Since we also support CentOS 7 which uses an old version of glibc that [calls malloc in `execvpe()`](https://elixir.bootlin.com/glibc/glibc-2.17.90/source/posix/execvpe.c#L164), we also need to be careful about that.

I think we should avoid glibc wrappers altogether and only make system calls.

**Comment by sporksmith** [comment]
> I think we should avoid glibc wrappers altogether and only make system calls.

I'd moderately prefer not lose the type-safety of calling the wrappers vs. calling `syscall` (or even our own implementation of `syscall`) directly. Anything in `man` section 2 is a very thin wrapper; most generated via a macro
