### ISSUE TITLE
Implement futex operations that currently generate warnings in tor sims

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#1262]
In Tor simulations we currently get some warnings about `futex` operations that we don't support yet. We return ENOSYS for these, and as far as we can tell, this is handled gracefully without adversely affecting the simulation.

We probably ought to implement these operations though to increase our assurance about correctness in Tor simulations, get rid of the warnings, and support other simulations where they might really be needed.

Previously I've run across that glibc semaphores use `FUTEX_WAIT_BITSET` and `FUTEX_WAKE_BITSET`, so we probably ought to implement those. There might be others that are generating warnings in the tor simulations, though.

**Comment by sporksmith** [comment]
@stevenengler reports that the bitset operations are also used in Python, which currently ends up dead-locking.

**Comment by robgjansen** [comment]
In a recent 5% Tor network experiment, I counted 876,113 warnings about missing futex operation 5, which on my machine maps to `FUTEX_WAKE_OP`. I did not see warnings for any other missing futex operations.

**Comment by sporksmith** [comment]
@robgjansen are you still seeing warnings for these?

**Comment by robgjansen** [comment]
Sorry for the delay! I'm not seeing this futex warning

https://github.com/shadow/shadow/blob/b0e1fd5e7b6c922cf0fad0ea0889c59bd55fcd0b/src/main/host/syscall/futex.c#L206

for either ptrace or preload mode when running Shadow in docker at v2.0.0-pre.4 (8f2ceee4dcb97ff12e6ff3d94bc54f109c2e9fd3).

**Comment by sporksmith** [comment]
Thanks for the update! Going ahead and closing, then
