### ISSUE TITLE
Enable `--pin-cpus` by default and rename the option

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#1271]
Since the `--pin-cpus` option is becoming an "experimental" option, we should instead enable CPU pinning by default and change the option to something like `--disable-cpu-pinning`.

**Comment by robgjansen** [comment]
Remember this tidbit from @sporksmith 
> we'll need to explicitly disable it in our shadow_test macro to avoid them all pinning to the same core.

**Comment by robgjansen** [comment]
Closed in #1346
