### ISSUE TITLE
Shadow returned code '-9'

### ISSUE THREAD

**Issue by shrlck221** [shadow/shadow#1337]
Hi,

I've successfully passed all shadow's tests (including the minimal example) but after executing "tornettools simulate", shadow returned -9.
```
2021-05-10 11:35:54 1620639354.988084 [tornettools] [INFO] Starting shadow
2021-05-10 12:59:01 1620644341.450801 [tornettools] [INFO] Cleaning up
2021-05-10 12:59:01 1620644341.851468 [tornettools] [INFO] Done simulating; shadow returned code '-9'
```

The shadow.log file has this warning messages: 
```
00:00:09.055298 [thread-12] 00:00:01.000000000 [warning] [4uthority2~100.0.0.2] [process.c:6765 [process_emu_pthread_mutexattr_settype] pthread_mutexattr_settype() is not supported by pth or by shadow
00:00:09.055301 [thread-4] 00:00:01.000000000 [warning] [4uthority1~100.0.0.1] [process.c:6765] [process_emu_pthread_mutexattr_settype] pthread_mutexattr_settype() is not supported by pth or by shadow
00:00:09.055301 [thread-10] 00:00:01.000000000 [warning] [4uthority3~100.0.0.3] [process.c:6765] [process_emu_pthread_mutexattr_settype] pthread_mutexattr_settype() is not supported by pth or by shadow
00:00:09.055422 [thread-12] 00:00:01.000000000 [warning] [4uthority2~100.0.0.2] [process.c:4952] [process_emu___cxa_atexit] atexit at library close is not currently supported
00:00:09.055424 [thread-4] 00:00:01.000000000 [warning] [4uthority1~100.0.0.1] [process.c:4952] [process_emu___cxa_atexit] atexit at library close is not currently supported
00:00:09.055426 [thread-10] 00:00:01.000000000 [warning] [4uthority3~100.0.0.3] [process.c:4952] [process_emu___cxa_atexit] atexit at library close is not currently supported
00:00:09.056898 [thread-12] 00:00:01.000000000 [warning] [4uthority2~100.0.0.2] [process.c:4952] [process_emu___cxa_atexit] atexit at library close is not currently supported
00:00:09.056900 [thread-4] 00:00:01.000000000 [warning] [4uthority1~100.0.0.1] [process.c:4952] [process_emu___cxa_atexit] atexit at library close is not currently supported
00:00:09.056901 [thread-10] 00:00:01.000000000 [warning] [4uthority3~100.0.0.3] [process.c:4952] [process_emu___cxa_atexit] atexit at library close is not currently supported
```

- Description:	Ubuntu 18.04.5 LTS

- Linux micPC 5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Shadow v1.13.2-704-g27f0e792 2021-05-03--16:38:19 running GLib v2.56.4 and IGraph v0.7.1

- Using Tornettools 1.1.0

**Comment by shrlck221** [comment]
I've checked the log file of some of the many hosts that are failing and all of them have these same warning messages:

`Jan 01 00:00:03.000 [notice] Bootstrapped 0%: Starting`
`Jan 01 00:00:03.000 [notice] Starting with guard context "default"`
`Jan 01 00:00:04.000 [notice] New control connection opened from 127.0.0.1.`
`Jan 01 00:00:04.000 [warn] The "EXTENDED" SETEVENTS argument is no longer supported.`
`Jan 01 00:00:04.725 [warn] Received http status code 404 ("Not found") from server '100.0.0.2:8080' while fetching consensus directory.`
`Jan 01 00:00:04.828 [warn] Received http status code 404 ("Not found") from server '100.0.0.3:8080' while fetching consensus directory.`
...
...
`Jan 01 00:02:29.870 [warn] Received http status code 404 ("Not found") from server '100.0.0.3:8080' while fetching consensus directory.`
`Jan 01 00:02:29.870 [warn] Received http status code 404 ("Not found") from server '100.0.0.3:8080' while fetching consensus directory.`
`Jan 01 00:02:31.560 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.`
`Jan 01 00:02:32.463 [notice] The current consensus has no exit nodes. Tor can only build internal paths, such as paths to onion services.`
`Jan 01 00:02:32.463 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/70, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)`

`Jan 01 00:02:33.917 [notice] The current consensus contains exit nodes. Tor can build exit and internal paths.
Jan 01 00:02:35.281 [notice] Bootstrapped 10%: Finishing handshake with directory server
Jan 01 00:02:35.281 [notice] Bootstrapped 80%: Connecting to the Tor network
Jan 01 00:02:36.123 [notice] Bootstrapped 90%: Establishing a Tor circuit
Jan 01 00:02:37.217 [`


Thanks a lot for your help!

**Comment by shrlck221** [comment]
I've tried simulating a smaller network (network_scale 0.001 instead of 0.01) and it executed successfully. Comparing the relay's log files from both simulations, the fetching consensus error appears in both of them but for some reason the one that returned -9 suddenly stops writing on stdout-xxx.tor.1000.log file:

Jan 01 00:02:30.848 [notice] The current consensus contains exit nodes. **Tor can build exit and inter**

While in the successful execution, it keeps writing:

Jan 01 00:02:31.036 [notice] The current consensus contains exit nodes. **Tor can build exit and internal paths.**
Jan 01 00:02:31.706 [notice] Self-testing indicates your ORPort is reachable from the outside. Excellent. Publishing server descriptor.
Jan 01 00:02:32.000 [notice] Bootstrapped 90%: Establishing a Tor circuit
Jan 01 00:02:32.528 [notice] Bootstrapped 100%: Done

Could be something related with system configs or limits?

**Comment by robgjansen** [comment]
> Could be something related with system configs or limits?

Oh, I think you might be right! It's possible that in the larger networks, your processes fail due to the system file limit but in the smaller network, you do not exceed the system file limit and things work OK.

You'll definitely need to adjust the default limits if you haven't done that yet, as shown here:
https://github.com/shadow/shadow/blob/27f0e7920b579b14be02ea79bd35192cfa7e88e1/docs/1.1-Shadow.md#system-configs-and-limits

Please work through that section and try the 1% network again and let us know if things improve.

**Comment by shrlck221** [comment]
I've adjusted the limits with the following values: 

![sysctl](https://user-images.githubusercontent.com/81997761/118114856-71534800-b3e8-11eb-8324-3041a90eff1c.png)


![ulimit](https://user-images.githubusercontent.com/81997761/118114685-36e9ab00-b3e8-11eb-93ea-0969ebda6800.png)

 
But Shadow returned -9 again after executing for about 90min. I'm simulating with 32 GB of RAM, so I don't think it's anything related with memory capacity, right?

**Comment by robgjansen** [comment]
According to [Table 4 in our paper](https://www.robgjansen.com/publications/neverenough-sec2021.pdf), I expect a 1% network to consume about 35 GiB of RAM before the end of the experiment. The behavior you describe of being killed after 90 minutes is consistent with running out of RAM I think.

You could also check the logs collected by tornettools - it should log output from `free` during the simulation, so you could check the free.log file to check how RAM usage is changing over time.

**Comment by robgjansen** [comment]
Also, I do expect Shadow memory usage to start slower and increase over time, which is why it takes a while before it's killed. Here is an example memory usage graph from a **5%** network. If you run through the parsing and plotting steps in tornettools, you should be able to generate this graph for your particular experiment too.

![ram](https://user-images.githubusercontent.com/788144/118155286-11f43880-b3e6-11eb-8295-897b04398c9d.png)

**Comment by robgjansen** [comment]
We've opened #1358 to help add messages to shadow's log file to warn about the type of failures I believe are observed here.
