### ISSUE TITLE
Scan and correct user documentation

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#1366]
We want to make sure our instructions for setting up and using the new version of Shadow are up to date and clear. We should scan and ensure that the setup instructions, tutorials, etc. are properly updated and well-presented.

We want to do this before merging `dev` into `main`, because after the merge anyone that clones the repo will start using the new version of Shadow and will need instructions on how to do so.

**Comment by robgjansen** [comment]
Some items to consider for the docs update:

- [ ] make md filenames consistent (remove numbers, change to underscore separators)
- [ ] do a better job of separating documentation sections into different files (e.g., resource usage can probably be in its own file, and there are probably other things that could be split out too)
- [ ] `2018-ccs-tmodel.md` and `3.3-TGen-Config.md` can be deleted
- [ ] I think we should split the shadow configuration part into two sections like we now have with the network config: one file has a general overview and some high level descriptions, and the other file has the detailed descriptions of every option that can be set and the associated behaviors
- [ ] `3-Simulation-Customization.md` can be deleted and instead list the structure in the table of contents?
- [ ] For `4-Notes-and-FAQs.md`, I think most of the questions can either be deleted, move to the discussions forum page, or some dev notes stuff could go into other existing dev instruction manuals (or a new one)
- [ ] The design overview page is definitely outdated and needs to be updated. For now, we could at least put a big disclaimer at the top that the design it references is based on shadow 1 and not shadow 2.

**Comment by stevenengler** [comment]
> We should probably have a page that describes how to run Tor's configure and build scripts to build the tor binary that shadow will then exec? Or maybe we can just say "follow tor's build process"?

TorNetTools [has this](https://github.com/shadow/tornettools#we-also-need-tor) in it's documentation, so maybe we don't need this within the Shadow docs?

**Comment by robgjansen** [comment]
Closed in #1433.
