### ISSUE TITLE
Allow configuring libraries and/or symbols from which native syscalls are allowed (for LTTng)

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#1461]
Broadly, it'd be useful to allow the tor processes in a shadow simulation to communicate with an LTTng daemon running outside of Shadow, s.t. it could collect tracing events for the whole simulation.

I think a way to solve this might be to allow the user to specify libraries that are allowed to make native syscalls. In preload+seccomp mode, it'd be relatively easy from the shim to implement by getting the address ranges that belong to the specified library (e.g. the lttng client library) from `/proc/self/maps`, and then in each syscall walk the stack (using the `backtrace` library function) to determine whether any of the return addresses in the stack are from that library.

The main downside I can think of is that we'd need to walk the stack on every syscall, though it's probably not that expensive relative to the cost of the syscall.

**Comment by sporksmith** [comment]
The main possible gotcha I can think of that might break this approach is if code running outside the library makes system calls (which get intercepted by Shadow), and then pass the results to the library. e.g. if the client of the library opens a file (getting a Shadow virtual file descriptor) and passes that to the library, which then tries to use the virtual fd with native syscalls. This seems unlikely in practice,  though.

**Comment by sporksmith** [comment]
Technically we could probably do something similar in the ptrace mode of operation, but it'd be a bit trickier.  We couldn't easily just call libc's `backtrace` from a ptrace-syscall-stop, since we get control in Shadow's process instead of the managed process. We'd probably need to find or implement some library that implemented backtrace functionality but allowed us to point to the mmap'd managed process's stack instead of walking "this" stack.

**Comment by sporksmith** [comment]
Another possibility is for the managed program or library to be patched to call the shim's functions for enabling/disabling interposition. (I think it could use `dlsym` to dynamically call the function if the shadow shim is present, or do nothing otherwise).

I looked into whether this would work for tor+lttng, but unfortunately it looks like the lttng library makes most of its syscalls from its own global constructors and destructors, without tor in the stack at all. i.e. we'd need to patch lttng rather than patching tor. e.g. from `strace -fk tor`:

```
800487 futex(0x7fe29c6580c8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
 > /usr/lib/x86_64-linux-gnu/libpthread-2.31.so(__pthread_once_slow+0xe7) [0x124a7]
 > /usr/lib/x86_64-linux-gnu/libdl-2.31.so(dlerror+0x2db) [0x1b1b]
 > /usr/lib/x86_64-linux-gnu/libdl-2.31.so(dlopen+0x4a) [0x13da]
 > /usr/lib/x86_64-linux-gnu/liblttng-ust-tracepoint.so.0.0.0() [0x2593]
 > /usr/lib/x86_64-linux-gnu/ld-2.31.so(_dl_rtld_di_serinfo+0x6afa) [0x11b8a]
 > /usr/lib/x86_64-linux-gnu/ld-2.31.so(_dl_rtld_di_serinfo+0x6c01) [0x11c91]
 > /usr/lib/x86_64-linux-gnu/ld-2.31.so() [0x113a]
...
800487 futex(0x7fe29c627390, FUTEX_WAKE_PRIVATE, 2147483647) = 0
 > /usr/lib/x86_64-linux-gnu/libpthread-2.31.so(__pthread_once_slow+0xe7) [0x124a7]
 > /usr/lib/x86_64-linux-gnu/libpthread-2.31.so(__shm_directory+0x1b) [0x1278b]
 > /usr/lib/x86_64-linux-gnu/librt-2.31.so(shm_open+0x35) [0x5e25]
 > /usr/lib/x86_64-linux-gnu/liblttng-ust.so.0.0.0(lttng_ust_exit+0xb6d) [0xef3d]
 > /usr/lib/x86_64-linux-gnu/liblttng-ust.so.0.0.0(lttng_ust_exit+0x1668) [0xfa38]
 > /usr/lib/x86_64-linux-gnu/ld-2.31.so(_dl_rtld_di_serinfo+0x6afa) [0x11b8a]
 > /usr/lib/x86_64-linux-gnu/ld-2.31.so(_dl_rtld_di_serinfo+0x6c01) [0x11c91]
 > /usr/lib/x86_64-linux-gnu/ld-2.31.so() [0x113a]
800487 openat(AT_FDCWD, "/dev/shm/lttng-ust-wait-8", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = 3
 > /usr/lib/x86_64-linux-gnu/libpthread-2.31.so(__open64+0x5b) [0x14a5b]
 > /usr/lib/x86_64-linux-gnu/librt-2.31.so(shm_open+0x12e) [0x5f1e]
 > /usr/lib/x86_64-linux-gnu/liblttng-ust.so.0.0.0(lttng_ust_exit+0xb6d) [0xef3d]
 > /usr/lib/x86_64-linux-gnu/liblttng-ust.so.0.0.0(lttng_ust_exit+0x1668) [0xfa38]
 > /usr/lib/x86_64-linux-gnu/ld-2.31.so(_dl_rtld_di_serinfo+0x6afa) [0x11b8a]
 > /usr/lib/x86_64-linux-gnu/ld-2.31.so(_dl_rtld_di_serinfo+0x6c01) [0x11c91]
 > /usr/lib/x86_64-linux-gnu/ld-2.31.so() [0x113a]
800487 read(3, "\1\0\0\0", 4)           = 4
 > /usr/lib/x86_64-linux-gnu/libpthread-2.31.so(read+0x12) [0x14332]
 > /usr/lib/x86_64-linux-gnu/liblttng-ust.so.0.0.0(lttng_ust_exit+0xb94) [0xef64]
 > /usr/lib/x86_64-linux-gnu/liblttng-ust.so.0.0.0(lttng_ust_exit+0x1668) [0xfa38]
 > /usr/lib/x86_64-linux-gnu/ld-2.31.so(_dl_rtld_di_serinfo+0x6afa) [0x11b8a]
 > /usr/lib/x86_64-linux-gnu/ld-2.31.so(_dl_rtld_di_serinfo+0x6c01) [0x11c91]
 > /usr/lib/x86_64-linux-gnu/ld-2.31.so() [0x113a]
```

**Comment by robgjansen** [comment]
Can you just run LTTng as a managed process inside of Shadow too?

**Comment by sporksmith** [comment]
> Can you just run LTTng as a managed process inside of Shadow too?

Yes; I now think that's a better solution. Closing in favor of https://github.com/shadow/shadow/issues/1723
