### ISSUE TITLE
Update version string that is printed on --version

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#1464]
- [x] When running `shadow --version` and `shadow --show-build-info` Shadow prints different version information, the latter option producing a more specific version that includes the git shorthash and the number of commits since the previous tag. It would be nice if `--version` could include the more specific version too.

- [x] Also, `--version` should end in one newline instead of 2 as it currently does, I think.

**Comment by stevenengler** [comment]
We'll need to write custom `-h` (short help) and `--help` (long help) handlers for clap. I'm not sure which options we'll want to enable, probably `exclusive`, and then add the help flags to `required_unless_present_any()` for the config option.

**Comment by stevenengler** [comment]
> When running shadow --version and shadow --show-build-info Shadow prints different version information, the latter option producing a more specific version that includes the git shorthash and the number of commits since the previous tag. It would be nice if --version could include the more specific version too.

This part is done in #1612.

**Comment by stevenengler** [comment]
> Also, --version should end in one newline instead of 2 as it currently does, I think.

Fixed in #1653.
