### ISSUE TITLE
Disable logging tracker stats before 2.0 release

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#1629]
We currently log something like the following every second in a heartbeat message for each host:

```
00:00:07.393281 [thread-531] 00:00:02.000000000 [message] [peer678~11.0.2.166] [tracker.c:457] [_tracker_logNode] [shadow-heartbeat] [node] 1,2037126,2143726,0.000000,0,0.000000;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;1911,2037126,0,0,0,0,1911,80262,1956864,0,0,0;2011,2143726,0,0,0,0,2011,84462,2059264,0,0,0
```

This is unreadable and so we probably want to change it up. Also, this code is using a C counter type, but we really should be using the newer rust counter type for counting things like number of packets and bytes sent/recv in the last second.

We should consider turning this off by default and placing the feature in the experimental section so we can change it after releasing 2.0.

**Comment by stevenengler** [comment]
Related discussion: https://github.com/shadow/shadow/issues/1399, https://github.com/shadow/shadow/issues/1450
