### ISSUE TITLE
Shadow does not print usage or help info

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#1652]
Clean build at bbf7d014a5240d131a51a2b5b03426e76f5ee784

```
$ ./build/src/main/shadow --help
** Shadow did not complete successfully: Could not parse command-line options
** See the log for details

$ ./build/src/main/shadow --version
** Shadow did not complete successfully: Could not parse command-line options
** See the log for details
```

All of the tests pass successfully and passing a `yml` files does cause it to run correctly.

**Comment by stevenengler** [comment]
Oops, and `--help` is broken too. These were broken in #1633 since I forgot clap considers these to be errors. This should be fixed in #1653.
