### ISSUE TITLE
Setup a private github runner

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#1735]
We need to investigate the requirements for setting up a private github runner and create the configurations needed to submit the performance testing jobs we want to the runner. The idea is that we'll do this dev work using a smaller low-resource machine and later, once we have things working, we'll upgrade to a larger resource machine. So we should document the steps needed to get things running.

**Comment by stevenengler** [comment]
@robgjansen I think this summarizes our discussion:

We probably want a workflow that runs the benchmark, stores the results (including graphs as images) in a benchmark-specific git repository, and then if the benchmark was run on a PR, the workflow should leave a new comment on the PR with links to the graph images stored in the benchmark-specific repository.

GitHub recommends to not add private runners to public repositories, but if we only run the workflow on the main branch (and when someone with write access requests to run the workflow on a PR), we should hopefully be fine.

Question: Can someone submit a new PR with a new workflow that runs on the private runner?

Alternatively, we might need to put the private runner and workflow in the benchmark-specific repository, and have it watch for new commits in the shadow repository using a `repository_dispatch` event.

> 1. When will the performance testing jobs run? Once a day? For every commit on the shadow main branch? Can they be run on pull requests before merging (not sure if this is possible)?

For every commit on the main branch, and for pull requests if requested by someone who is authorized to run the workflow (people with write access to the repository).

> 2. What format do we want to save the results in? The tornettools graph pdfs only?

The graphs are the most important, but depending on where we save the results, it might be useful to save all results.

> 3. Where will we store the results? Push them to a git repository?

Workflow artifacts only store data temporarily, and it doesn't make sense to store them in the shadow repository itself. Instead we'll store them in a benchmark-specific repository (maybe in an LFS?).

> 4. Can the results be stored only temporarily, or do we want them to be persistent?

We want them to be persistent (or at least until we decide to remove them manually).

**Comment by stevenengler** [comment]
From discussion, we want three separate workflows:

1. Nightly (except Saturday and Sunday)
    - run 1 tor simulation of the main branch
    - use a 5% network for 30 minutes (approx 16 hours)
    - plot against a baseline and the previous day's results
2. Weekly (Saturday)
    - run 3 tor simulations of the main branch
    - use a 5% network for 30 minutes (approx 48 hours)
    - plot all 3 simulations against a baseline and the previous week's results
3. Manual
    - run 1 tor simulation of a user-chosen commit
    - use a 5% network for 15 minutes (approx 7 hours)
    - plot against a user-chosen result

In the results repository, we want to store only the graphs (pngs) and the plot data directory. On the host, we save the entire simulation directory.

**Comment by stevenengler** [comment]
I think this can be closed now. We have one running which pushes results to https://github.com/shadow/benchmark-results/tree/master/tor.
