### ISSUE TITLE
Multiple calls to `listen()` not working correctly on a TCP socket

### ISSUE THREAD

**Issue by rwails** [shadow/shadow#1827]
**Describe the issue**

Calling `listen()` twice on a TCP socket is a valid sequence of operations---for example, you can change the socket's listen-backlog size with a second call to `listen()`.

https://github.com/shadow/shadow/blob/5353405e136fb9d7a630fffc4bbd7f3bec426b03/src/main/host/syscall/socket.c#L1066-L1079

LOCs 1073--1079 in the above snippet implement this logic. However, LOC 1073 is never reached. Instead, the condition at 1067 (`!tcp_isListeningAllowed()`) is always true for listening sockets (see snippet [0] below), and the syscall handler returns an error to the caller.

Returning an error on subsequent `listen()` calls causes certain applications to crash that rely on this behavior to work correctly.

--------------------

[0] `tcp_isListeningAllowed()` only checks that the socket's state is `TCPCS_NONE`, but `TCPS_LISTEN` is also a valid listening state.
https://github.com/shadow/shadow/blob/5353405e136fb9d7a630fffc4bbd7f3bec426b03/src/main/host/descriptor/tcp.c#L1427-L1439

**Comment by stevenengler** [comment]
This is also an issue for nginx, but nginx only logs a warning when the second `listen()` fails.

**Comment by stevenengler** [comment]
Re-opening since shadow now allows multiple `listen()` calls, but does not update the backlog size.

https://github.com/shadow/shadow/blob/5353405e136fb9d7a630fffc4bbd7f3bec426b03/src/main/host/syscall/socket.c#L1073-L1079
