### ISSUE TITLE
support select for synchronous i/o multiplexing

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#1887]
Many networking applications make use of select, and we should support it.

The select implementation should be mostly similar to our `poll` implementation, so we can look to the poll syscall handler for guidance.

https://man7.org/linux/man-pages/man2/select.2.html

**Comment by stevenengler** [comment]
I think this is a duplicate of https://github.com/shadow/shadow/issues/1721?

**Comment by robgjansen** [comment]
Whoops, you're right, thanks!
