### ISSUE TITLE
Remove --interpose-method=ptrace

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#1945]
With #1549 fixed, there will be no remaining supported use-cases where ptrace-mode works better than preload-mode. We should remove ptrace mode and correspondingly simplify the code.

Since `--interpose-method` is in the experimental section, this does not require a major version bump.

Let's start by removing the "ptrace" option for the `--interpose-method` flag, making "preload" currently the only option. Likewise we can remove `thread_ptrace.c` etc.

A potential follow-up is to remove `--interpose-method` and support for "subclassing" `Thread` in general. At the least that should be a distinct separate step, though. We might also consider keeping them around for future experimentation with other interposition mechanisms.

Potentially blocking issues:

- [x] #1549
- [x] #867
- [x] #2091

**Comment by sporksmith** [comment]
For #867, *most* of the preload tests now work in coverage mode. We could just disable the non-working ones for now.

OTOH maybe it's also worth revisiting whether maintaining coverage support is worth it.

**Comment by sporksmith** [comment]
Current plan is to leave ptrace-mode in for the next release (2.1), but delete it after that before our upcoming push to migrate code to Rust (2.2)

**Comment by 0xsmoos** [comment]
yea
