### ISSUE TITLE
Failing to intercept time in golang

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#1948]
Given the golang program:

```
package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Println(time.Now())
}
```

The output in both preload and ptrace mode is the host system time instead of simulation time. e.g.:

```
2022-03-03 18:28:00.602167415 +0000 UTC m=+0.000000001
```

**Comment by sporksmith** [comment]
Stepping through in gdb, `time.Now` -> `time.now` -> `runtime.walltime1` -> `[vdso]`.

In C code we mostly avoid running the `[vdso]` code by intercepting the libc time APIs.

I would've thought that running the `[vdso]` code might be ok now that we're emulating `rdtsc`. Maybe that's used to measure the delta from some t0 that's either also in shared memory, or somehow initialized before we gain control? The latter would be pretty surprising in ptrace-mode, though.

**Comment by sporksmith** [comment]
Tracing through the [vdso source](https://elixir.bootlin.com/linux/latest/source/arch/x86/entry/vdso/vclock_gettime.c#L20), it does appear to ultimately access a [shared data page](https://elixir.bootlin.com/linux/latest/source/include/vdso/datapage.h#L60) with a base time measurement.

Since we already only support dynamically linked golang programs, *maybe* we could intercept the golang time APIs via `LD_PRELOAD`, but it's probably worth just [fixing vdso](https://github.com/shadow/shadow/issues/1091) at this point.

**Comment by sporksmith** [comment]
@cohosh FYI this bug puts a substantial asterisk on golang simulation results. Before fixing this bug, golang simulations are definitely not deterministic, and time deltas weren't simulated accurately.

Unfortunately now that it's fixed, we get a deadlock in the runtime in both ptrace and preload mode (#1968). I'm investigating that now.

**Comment by cohosh** [comment]
> @cohosh FYI this bug puts a substantial asterisk on golang simulation results. Before fixing this bug, golang simulations are definitely not deterministic, and time deltas weren't simulated accurately.
> 
> Unfortunately now that it's fixed, we get a deadlock in the runtime in both ptrace and preload mode (#1968). I'm investigating that now.

Wow, this is good to know. Thanks for the updates!
