### ISSUE TITLE
signals in ptrace mode

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#1967]
Signal support in ptrace mode is less complete than in preload mode. In particular, we haven't implemented having a signal interrupt a blocking syscall in ptrace mode.

Our current plan is that this issue will be closed as deprecated after removing ptrace mode (#1945). For now though, this is a placeholder in case we end up deciding to continue supporting ptrace mode in the longer term.

**Comment by stevenengler** [comment]
Closing since we no longer support ptrace mode.
