### ISSUE TITLE
When printing the sim progress, also print the current time

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#2006]
When the `--progress` option is enabled and the sim is not running in a tty, the stderr messages should also show the current time. Ideally, we'd like to find a way to format the current time without requiring an extra library.

**Comment by sporksmith** [comment]
I wrote some basic time formatting code for the shadow logger: https://github.com/shadow/shadow/blob/main/src/main/utility/time.rs

**Comment by robgjansen** [comment]
I think one or both of these would be a big improvement:
- print a stamp of the current time in the progress line
- log the progress line more frequently, e.g., once every minute instead of once every 30 minutes

Most benchmark sims take 7 hours on our runner, so if you round that up to 10 hours and print a progress line every minute, that's only ~600 progress lines.

**Comment by stevenengler** [comment]
> I wrote some basic time formatting code for the shadow logger: https://github.com/shadow/shadow/blob/main/src/main/utility/time.rs

I think we'd need a lot more to be able to print the current "datetime", since we need to print the actual date/time rather than just a time offset. For example we'd need the day/month/year, the time of day, conversion to UTC, etc. Maybe we could write a wrapper around one of the libc functions for this.

> I think one or both of these would be a big improvement:
>
> - print a stamp of the current time in the progress line
> - log the progress line more frequently, e.g., once every minute instead of once every 30 minutes

We now print the progress line every minute.

We decided that since we now print it frequently, we don't really need the current time in the progress line anymore. If we decide later that we still want to print the current time then we can re-open this.
