### ISSUE TITLE
Rename file objects

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#2040]
See #2031

Edit (added by @stevenengler):

- [x] rename the `File` in C to `c::RegularFile`
- [x] rename the `Socket` in C to `c::LegacySocket`
- [x] rename `GenericFile` to `File`
- [x] rename `PipeFile` to `Pipe`, etc
- [x] image to give overview of FileDescTable -> Descriptor -> OpenFile -> File -> Pipe/Socket/RegularFile etc.

**Comment by stevenengler** [comment]
> image to give overview of FileDescTable -> Descriptor -> OpenFile -> File -> Pipe/Socket/RegularFile etc.

We discussed where to put this image, and we should probably store it in the `docs/assets` directory. Rustdoc doesn't currently support images in documentation, so this documentation will probably need to live as part of the markdown/mdbook docs, and we can maybe link to it from the `host::descriptor` rustdoc documentation.
