### ISSUE TITLE
Support the rseq syscall (restartable sequences)

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#2059]
Newer versions of glibc (>=2.35) [use the rseq syscall](https://lwn.net/Articles/883104/), so it's likely that we need to support this syscall in Shadow. It seems to be an issue for running Shadow in Ubuntu 22.04.

**Comment by sporksmith** [comment]
This also appears to affect Arch https://github.com/shadow/shadow/discussions/2084#discussioncomment-2674090

**Comment by stevenengler** [comment]
And for Fedora 36. Shadow likely won't run in any distro released after January 2022 (glibc 2.35 was released 03 Feb 2022).
