### ISSUE TITLE
Rename `host_defaults` configuration field

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#2065]
Consider renaming `HostOptions::options` to something like `HostOptions::host_default_overrides` to make the relationship more clear.

Likewise for Process defaults, if we have them at this point.

Update 2022-12-13: Renamed issue to refocus on removing `GeneralOptions::host_defaults` and `CliOptions:host_defaults`, in favor of using yaml merge keys and dynamic yaml generation tools to push such "templating" outside of shadow itself.

**Comment by sporksmith** [comment]
Another option might be to do away with the explicit `host_defaults` field and use yaml anchors.

The `<<:` "anchor extension" operator available in Docker files would make this pretty straightforward to work with, but unfortunately afaict this is not standard yaml. https://www.cloudsavvyit.com/10765/how-to-simplify-docker-compose-files-with-yaml-anchors-and-extensions/

**Comment by stevenengler** [comment]
> Another option might be to do away with the explicit `host_defaults` field and use yaml anchors.

I made #2067 based on this idea to remove the `hosts.<hostname>quantity` field.

**Comment by stevenengler** [comment]
> The `<<:` "anchor extension" operator available in Docker files would make this pretty straightforward to work with, but unfortunately afaict this is not standard yaml. https://www.cloudsavvyit.com/10765/how-to-simplify-docker-compose-files-with-yaml-anchors-and-extensions/

It looks like there's a crate that does this, but I'm not sure if I'd rely on it being correct: https://docs.rs/yaml-merge-keys/latest/yaml_merge_keys/

**Comment by stevenengler** [comment]
> > The `<<:` "anchor extension" operator available in Docker files would make this pretty straightforward to work with, but unfortunately afaict this is not standard yaml. https://www.cloudsavvyit.com/10765/how-to-simplify-docker-compose-files-with-yaml-anchors-and-extensions/
> 
> 
> 
> It looks like there's a crate that does this, but I'm not sure if I'd rely on it being correct: https://docs.rs/yaml-merge-keys/latest/yaml_merge_keys/

We support this in Shadow now as an [experimental feature](https://shadow.github.io/docs/guide/shadow_config_overview.html#yaml-extensions-experimental).

**Comment by stevenengler** [comment]
We've decided to just rename this field for the 3.0 release and not change the structure. We haven't decided specifically on how to rename it yet.

**Comment by sporksmith** [comment]
Decision:

top-level field "host_defaults" -> "host_option_defaults"
host field "options" -> "host_options"
