### ISSUE TITLE
Emulate sched_getaffinity

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#2101]
We often see warnings about software making calls to the unspported `sched_getaffinity` syscall. Most software recovers from it failing, but in addition to it being nice to get rid of the warning noise, some software may use the result to help decide e.g. how many worker threads to spawn.

In such cases it'd likely help simulation performance to report a small number of CPUs (e.g. 1), so that such use-cases spawn a minimal number of such worker threads. Shadow only executes one thread on a given emulated Host at once, so additional worker threads in an emulated Process won't particularly help parallelization. 

For example, we get this line in`stderr` when executing `java -version` using OpenJDK:

```
OpenJDK 64-Bit Server VM warning: sched_getaffinity failed (Function not supported)- using online processor count (12) which may exceed available processors
```

It'd also be useful to find where it's getting the online processor count (probably somewhere in /proc...?) and intercept that as well. From this message it looks like reporting an affinity with only 1 *available* processor in `sched_getaffinity` would be sufficient to minimize worker threads, though.

**Comment by trinity-1686a** [comment]
> It'd also be useful to find where it's getting the online processor count (probably somewhere in /proc...?) and intercept that as well.

it's doing a [`sysconf(_SC_NPROCESSORS_ONLN)`](https://github.com/openjdk/jdk/blob/5540a8c5b7160ab5c67bb84631e3de54fa5aeceb/src/hotspot/os/linux/os_linux.cpp#L4674), which opens `/sys/devices/system/cpu/online`.
While it would not be a good idea for a software to rely on it for that kind of purpose, `sysconf(_SC_NPROCESSORS_CONF)`  (`/sys/devices/system/cpu/possible`) should probably be intercepted too (this includes cores not online, like ones that could be hotplugged).

**Comment by sporksmith** [comment]
Thanks for digging into this!

Generally we prefer to intercept at the syscall level when feasible, since some programs could make the syscall directly instead of going through libc. i.e. I think we'll want to intercept `open` syscalls to these files, rather than the `sysconf` libc function.

See `regularfile_openat` for examples of such overrides. I think it'd be reasonable add handling for these two files there. 

Eventually we might want to think about restructuring this to scale better and covering more of `/proc` and `/sys`; maybe even hiding any files under those directories that we don't know how to handle. We'll probably want to wait until this code is in Rust before doing any major overhaul though.

**Comment by stevenengler** [comment]
The PR adds support for `sched_getaffinity` and `sched_setaffinity`, but adds partial support for `sysconf`. If we want to support CPU-related `sysconf` options such as `_SC_NPROCESSORS_ONLN`, we should make a new issue for that.
