### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#2146]
While it hasn't been an issue for us, I think it would be good to have a code of conduct document anyways.

Two possible options:
- adapt Tor's code of conduct (remove sections about the "Community Council", etc)
    - https://gitweb.torproject.org/community/policies.git/plain/code_of_conduct.txt
- adapt GitHub's default code of conduct (probably remove most of the "Enforcement Guidelines" section)
    - https://www.contributor-covenant.org/version/2/1/code_of_conduct/

We'd also need to figure out a private contact method.

**Comment by sporksmith** [comment]
Seems like a good idea. The [latter](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) looks a bit more amenable to customization and reuse
