### ISSUE TITLE
Shadow will return success even when plugins are killed by Linux OOM killer

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#2151]
In general Shadow will return a non-zero error code if any of the plugins failed. But since Shadow doesn't have a proper shutdown sequence, Shadow sends a SIGKILL to all plugin processes at the end of the simulation and does not consider those killed processes to be an error.

https://github.com/shadow/shadow/blob/cc0ec729d5ab40d9347373a79f36c82c4b14b8df/src/main/host/process.c#L392-L400

This means that plugins killed by a SIGKILL for any reason will not be considered as an error. If Linux decides to kill plugin processes due to memory exhaustion (or any other reason), Shadow will not report that as an error and the simulation will have invalid results while reporting that the simulation was successful.

I have not actually tested this since I don't want to invoke the oom killer on my machine, but I'm pretty confident that it will break in this case.

Possibly related to #2134.

**Comment by stevenengler** [comment]
Adding to 2.1 since I think this is important.

**Comment by sporksmith** [comment]
Nicely tracked down; yuck.

More generally it's probably also worth the `exitcode` file distinguishing between the process being killed by shadow at simulation end and other ways it might receive a SIGKILL. Maybe there shouldn't be a file at all in this case, or it should be empty.
