### ISSUE TITLE
Drop support for EOL distros

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#2178]
* Fedora 34 [june 7 2022](https://endoflife.date/fedora)
* Debian 10 [august 2022](https://wiki.debian.org/DebianReleases)

**Comment by stevenengler** [comment]
Related: #2309

**Comment by sporksmith** [comment]
It might be worth considering dropping ubuntu 18.04, too. It's not EOL until 2023, but it's holding back our minimum cmake version. #2418

OTOH as code moves into Rust maybe we'll care less about cmake.

**Comment by sporksmith** [comment]
When we do this, maybe we should also consider amending our stability guarantee to permit dropping distros that become EOL without a major version bump.

**Comment by sporksmith** [comment]
Done: https://github.com/shadow/shadow/pull/2850, https://github.com/shadow/shadow/pull/2820
