### ISSUE TITLE
Fedora is broken in CI

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#2179]
The shadow tests are failing at the "Install dependencies" step on Fedora configurations.

e.g. https://github.com/shadow/shadow/runs/6516557576?check_suite_focus=true
```
 Errors during downloading metadata for repository 'fedora':
Fedora 34 - x86_64                              2.1 kB/s | 3.3 kB     00:01    
  - Status code: 503 for https://mirrors.fedoraproject.org/metalink?repo=fedora-34&arch=x86_64 (IP: 35.81.0.97)
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Status code: 503 for https://mirrors.fedoraproject.org/metalink?repo=fedora-34&arch=x86_64 (IP: 35.81.0.97)
```

**Comment by sporksmith** [comment]
I can't reproduce locally - the tests succeed in a local Docker container.

I'm not seeing the IP 35.81.0.97 when I do a DNS lookup for "mirrors.fedoraproject.org". Maybe Github is trying to do some kind of MITM proxy here? I'm not sure how that would ever work though since it's https.

```
$ dig mirrors.fedoraproject.org

; <<>> DiG 9.16.1-Ubuntu <<>> mirrors.fedoraproject.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38585
;; flags: qr rd ra; QUERY: 1, ANSWER: 11, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;mirrors.fedoraproject.org.	IN	A

;; ANSWER SECTION:
mirrors.fedoraproject.org. 271	IN	CNAME	wildcard.fedoraproject.org.
wildcard.fedoraproject.org. 31	IN	A	152.19.134.142
wildcard.fedoraproject.org. 31	IN	A	140.211.169.196
wildcard.fedoraproject.org. 31	IN	A	67.219.144.68
wildcard.fedoraproject.org. 31	IN	A	38.145.60.21
wildcard.fedoraproject.org. 31	IN	A	38.145.60.20
wildcard.fedoraproject.org. 31	IN	A	35.81.0.97
wildcard.fedoraproject.org. 31	IN	A	8.43.85.73
wildcard.fedoraproject.org. 31	IN	A	8.43.85.67
wildcard.fedoraproject.org. 31	IN	A	209.132.190.2
wildcard.fedoraproject.org. 31	IN	A	152.19.134.198

;; Query time: 4 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Fri May 20 08:32:57 CDT 2022
;; MSG SIZE  rcvd: 237
```

**Comment by sporksmith** [comment]
Doing a reverse lookup on the IP from the error 35.81.0.97 gives an aws hostname. Not very informative, but doing a reverse lookup on the mirrored IP addresses above gives a fedoraproject name, increasing my suspicion that GitHub's DNS is lying to us  here...

```
$ dig -x 35.81.0.97
...
;; ANSWER SECTION:
97.0.81.35.in-addr.arpa. 300	IN	PTR	ec2-35-81-0-97.us-west-2.compute.amazonaws.com.
...
```

```
$ dig -x 38.145.60.21
...
;; ANSWER SECTION:
21.60.145.38.in-addr.arpa. 600	IN	PTR	proxy-iad02.fedoraproject.org.
...
```

**Comment by stevenengler** [comment]
> I'm not seeing the IP 35.81.0.97 when I do a DNS lookup for "mirrors.fedoraproject.org".
> [...]
> wildcard.fedoraproject.org. 31	IN	A	35.81.0.97

It looks like it's in the list?

If you visit `https://35.81.0.97/metalink?repo=fedora-34&arch=x86_64` it returns a 502 error, but I'm guessing that's because the proxy server is expecting a domain name not just an IP.

**Comment by sporksmith** [comment]
> It looks like it's in the list?\

:facepalm: that's what I get for scanning visually :)

**Comment by stevenengler** [comment]
Probably related: https://pagure.io/fedora-infrastructure/issue/10709

**Comment by sporksmith** [comment]
Ah nice find. I'd checked GH and Fedora main outage reporting sites, but it wasn't there yet...

**Comment by sporksmith** [comment]
Looks like it's fixed now https://pagure.io/fedora-infrastructure/issue/10709#comment-798697
