### ISSUE TITLE
Add signal handler to flush shadow log on SIGINT

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#2188]
It would be nice if using ctrl-c to stop shadow would flush the log before exiting. Probably would want to handle SIGTERM and SIGHUP as well.

**Comment by valdaarhun** [comment]
Hi. I would like to work on this issue.

**Comment by stevenengler** [comment]
Cool! This is something that would be nice to have, especially when debugging. We're in the process of moving our code to Rust, so it would be best if this was written in Rust as well (if you have any questions about this, let us know).

I think what we want is a signal handler that calls [`log::logger().flush()`](https://docs.rs/log/latest/log/trait.Log.html#tymethod.flush) before exiting. It would be nice to do this without adding a new dependency, but for simplicity we probably don't want to re-invent the wheel. [signal-hook](https://crates.io/crates/signal-hook) seems popular, so maybe that would be good here? @sporksmith Any thoughts about this? A downside of this is that we can't re-raise the original signal. For example in C you could catch the signal, flush the logger, reset to the default signal handler, and re-raise the signal. But with something like signal-hook we'd have to catch the signal, flush the logger, and just call something like `exit(1)`. Which isn't a big deal, but we just lose the proper exit status from something like `waitpid()`.

**Comment by stevenengler** [comment]
> Is there any reason as to why `signal-hook` might be preferred over `nix`'s [signal module](https://docs.rs/nix/latest/nix/sys/signal/index.html) in this particular case? I believe they both invoke `libc::sigaction` under the hood.

The main reason is that signal-hook provides a safe interface around signal handling. For example with signal-hook, you can provide a closure that does anything when a signal is received, without needing to worry about using unsafe rust or async-signal-safe code. With nix, you provide a function to run when a signal is received, but you need to make sure that everything the function does is async-signal-safe. Since `log::logger()` and `Log::flush()` aren't async-signal-safe, you'd probably want to provide a signal handler that sets a flag (or use a signalfd), and have another thread watch that flag and call those functions outside of the signal handler. So you could do it either way (with signal-hook or nix), but signal-hook takes care of the unsafe code and notifying another thread for you. As long as using nix doesn't add *too* much extra code complexity and we can easily reason that it's safe, I think that would be fine too.

**Comment by valdaarhun** [comment]
> `log::logger()` and `Log::flush()` aren't async-signal-safe

Given this, I think it would be better if I use `signal-hook`. Thanks!
