### ISSUE TITLE
Remove hostname prefix from data files

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#2218]
We currently have a lot of files with names of the form `<data-dir>/hosts/<hostname>/<hostname>.<processname>.<pid>.<type>`

Since each host is already in its own subdirectory, the `<hostname>` prefix is redundant.

Changing this would require a major version bump.

**Comment by stevenengler** [comment]
I don't think this should apply to pcap files since we allow the user to specify a directory using the `pcap_directory` option, and if all hosts use the same directory, there will be overlapping localhost interface pcap files.

**Comment by stevenengler** [comment]
> I don't think this should apply to pcap files since we allow the user to specify a directory using the `pcap_directory` option, and if all hosts use the same directory, there will be overlapping localhost interface pcap files.

We've decided to remove the `pcap_directory` option, so this *should* apply to the pcap files.
