### ISSUE TITLE
Improve failure mode when /dev/shm is full

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#2266]
Follow-up to: https://github.com/shadow/shadow/discussions/2264#discussioncomment-3109758

It appears that when /dev/shm gets filled, we can fail in a pretty baroque and disruptive way - managed programs go into an infinite SIGBUS loop.

Hopefully we can instead catch this in the shared memory allocator or where it's used and shut down with a helpful error message.

**Comment by stevenengler** [comment]
These conditions can probably be replicated using the `--shm-size` option for `docker run`. For example, maybe running a tor sim in a container with `--shm-size="100m"` or something similar.

**Comment by sporksmith** [comment]
I was able to reproduce a bus error using a small `--shm-size`. It didn't turn into the infinite loop we saw before; I think that'll end up depending whether shadow or the managed process is the first to try to access the memory.

I have a PR that seems to fix it; will send out shortly.
