### ISSUE TITLE
Missing few network performance graphs of the Tor simulation network

### ISSUE THREAD

**Issue by Safiyyah** [shadow/shadow#227]
I am running Shadow v1.9.2 on Ubuntu 12.04 LTS (on Amazon's EC2). 
Local machine: Mac OS X 10.9.4

I've e-mailed this question to shadow-support (http://mailman.cs.umn.edu/archives/shadow-support/2014-July/thread.html and http://mailman.cs.umn.edu/archives/shadow-support/2014-August/thread.html) but I've yet to find a solution for this. 

I'm testing the simulation network by running 'scallion'.

Referring to Rob Jansen's reply in the threads I've linked above, the contrib/analyze.py script in Shadow should be able to draw the following graphs:
- timing
- throughput-read
- throughput-write
- time-to-first-byte (rtt latency) for web clients (320k)
- time-to-first-byte (rtt latency) for bulk clients (5m)
- time-to-first-byte (rtt latency) for perf50k clients
- time-to-first-byte (rtt latency) for perf1m clients
- time-to-first-byte (rtt latency) for perf5m clients
- time-to-last-byte (download time) for web clients (320k)
- time-to-last-byte (download time) for bulk clients (5m)
- time-to-last-byte (download time) for perf50k clients
- time-to-last-byte (download time) for perf1m clients
- time-to-last-byte (download time) for perf5m clients
- aggregate network bytes downloaded, with percentages by client type

As the Shadow AMI has no GUI, I download the parsed results folder to my local machine, where I then run the script to plot the graph. However, I'm only able to get the first 3 graphs (timing, throughput-read, and throughput-write). Is anyone else facing the same issue?

EDIT: I've also tried parsing and plotting the graphs on the Ubuntu machine itself. Still facing the same problem. Only those 3 graphs are generated.

**Comment by robgjansen** [comment]
This should work with the latest Shadow and Tor plugins from the master branches. (The EC2 image is very outdated and probably should be updated.)
