### ISSUE TITLE
Size of `__vdso_gettimeofday` is too small for trampoline

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#2273]
In #2271, the shim panics with the message:

```
00:00:00.000001 error [patch_vdso.c:178] [_inject_trampoline] Can't inject 13 byte trampoline into 5 byte symbol '__vdso_gettimeofday'
```

This is failing on Ubuntu 22.04 with kernel 5.15.0-39-generic.

**Comment by sporksmith** [comment]
via afressancourt:

Hello

Here is the result of the command on my machine (Ubuntu 22.04 LTS, 5.15.0-39-generic kernel)

```
> readelf -Ws /lib/modules/5.15.0-39-generic/vdso/vdso64.so

Symbol table '.dynsym' contains 13 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND
     1: 0000000000000c10     5 FUNC    WEAK   DEFAULT   11 clock_gettime@@LINUX_2.6
     2: 0000000000000bd0     5 FUNC    GLOBAL DEFAULT   11 __vdso_gettimeofday@@LINUX_2.6
     3: 0000000000000c20    96 FUNC    WEAK   DEFAULT   11 clock_getres@@LINUX_2.6
     4: 0000000000000c20    96 FUNC    GLOBAL DEFAULT   11 __vdso_clock_getres@@LINUX_2.6
     5: 0000000000000bd0     5 FUNC    WEAK   DEFAULT   11 gettimeofday@@LINUX_2.6
     6: 0000000000000be0    41 FUNC    GLOBAL DEFAULT   11 __vdso_time@@LINUX_2.6
     7: 0000000000000cb0   156 FUNC    GLOBAL DEFAULT   11 __vdso_sgx_enter_enclave@@LINUX_2.6
     8: 0000000000000be0    41 FUNC    WEAK   DEFAULT   11 time@@LINUX_2.6
     9: 0000000000000c10     5 FUNC    GLOBAL DEFAULT   11 __vdso_clock_gettime@@LINUX_2.6
    10: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  ABS LINUX_2.6
    11: 0000000000000c80    37 FUNC    GLOBAL DEFAULT   11 __vdso_getcpu@@LINUX_2.6
    12: 0000000000000c80    37 FUNC    WEAK   DEFAULT   11 getcpu@@LINUX_2.6

Symbol table '.symtab' contains 28 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND
     1: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS vclock_gettime.c
     2: 00000000000006e0   201 FUNC    LOCAL  DEFAULT   11 __arch_get_hw_counter.constprop.0
     3: 00000000000007b0   621 FUNC    LOCAL  DEFAULT   11 __cvdso_clock_gettime_data.constprop.0
     4: 0000000000000a20   427 FUNC    LOCAL  DEFAULT   11 __cvdso_gettimeofday_data.constprop.0
     5: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS vgetcpu.c
     6: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS
     7: ffffffffffffc000     0 NOTYPE  LOCAL  DEFAULT  ABS vvar_page
     8: 00000000000003e0     0 OBJECT  LOCAL  DEFAULT    7 _DYNAMIC
     9: ffffffffffffd000     0 NOTYPE  LOCAL  DEFAULT  ABS pvclock_page
    10: ffffffffffffe000     0 NOTYPE  LOCAL  DEFAULT  ABS hvclock_page
    11: fffffffffffff000     0 NOTYPE  LOCAL  DEFAULT  ABS timens_page
    12: ffffffffffffc000     0 NOTYPE  LOCAL  DEFAULT    1 vvar_start
    13: 0000000000000554     0 NOTYPE  LOCAL  DEFAULT    9 __GNU_EH_FRAME_HDR
    14: ffffffffffffc080     0 NOTYPE  LOCAL  DEFAULT  ABS vvar__vdso_data
    15: fffffffffffff080     0 NOTYPE  LOCAL  DEFAULT  ABS timens__vdso_data
    16: 0000000000000c10     5 FUNC    WEAK   DEFAULT   11 clock_gettime
    17: 0000000000000cb0   156 FUNC    GLOBAL DEFAULT   11 __vdso_sgx_enter_enclave
    18: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  ABS LINUX_2.6
    19: 0000000000000bd0     5 FUNC    GLOBAL DEFAULT   11 __vdso_gettimeofday
    20: 0000000000000c20    96 FUNC    WEAK   DEFAULT   11 clock_getres
    21: 0000000000000c80    37 FUNC    GLOBAL DEFAULT   11 __vdso_getcpu
    22: 0000000000000c20    96 FUNC    GLOBAL DEFAULT   11 __vdso_clock_getres
    23: 0000000000000bd0     5 FUNC    WEAK   DEFAULT   11 gettimeofday
    24: 0000000000000be0    41 FUNC    WEAK   DEFAULT   11 time
    25: 0000000000000c80    37 FUNC    WEAK   DEFAULT   11 getcpu
    26: 0000000000000c10     5 FUNC    GLOBAL DEFAULT   11 __vdso_clock_gettime
    27: 0000000000000be0    41 FUNC    GLOBAL DEFAULT   11 __vdso_time
```

**Comment by sporksmith** [comment]
~copying my comment from the discussion:

This seems to be specific to the vdso module, which is part of the kernel. e.g. in the case of Docker I expect the problem to surface or not based on the kernel version of the host machine.

>     19: 0000000000000bd0     5 FUNC    GLOBAL DEFAULT   11 __vdso_gettimeofday

> 00:00:00.000001 error [patch_vdso.c:178] [_inject_trampoline] Can't inject 13 byte trampoline into 5 byte symbol '__vdso_gettimeofday'

It seems that readelf agrees that the symbol is only 5 bytes large, which is too small for us to inject our trampoline. I'm guessing it must be a relative jump to somewhere else in the vdso, which would only take a few bytes.

>      4: 0000000000000a20   427 FUNC    LOCAL  DEFAULT   11 __cvdso_gettimeofday_data.constprop.0

I'm guessing that this internal symbol contains the actual code, and is where `__vdso_gettimeofday is jumping`. Assuming that's the case we might be able to patch *that* symbol, but it won't be a very maintainable solution since we probably don't have any guarantee about this name staying the same in future kernel versions.

I'll have to think about if there's a way to shrink our trampoline to <= 5 bytes. Maybe we can inject something that'll raise a signal, and get control in the signal handler.

The next step is probably to inspect the disassembly of these symbols to validate my hypothesis. e.g. `objdump --disassemble=__vdso_gettimeofday /lib/modules/5.15.0-39-generic/vdso/vdso64.so` and `objdump --disassemble=__cvdso_gettimeofday_data.constprop.0 /lib/modules/5.15.0-39-generic/vdso/vdso64.so`.

We'll probably need to install this kernel version ourselves (e.g. in a VM) to do so, and to verify a fix. 

We currently run our CI in the oldest base image available in GH to help ensure backward compatibility with old kernels. Maybe we need to run it on the newest one available as well.

**Comment by sporksmith** [comment]
> I'll have to think about if there's a way to shrink our trampoline to <= 5 bytes. Maybe we can inject something that'll raise a signal, and get control in the signal handler.

`ud2; ret` would do it, I think. [ud2](https://mudongliang.github.io/x86/html/file_module_x86_id_318.html) raises `SIGILL`, and is only 2 bytes long. In the signal handler we can see which vdso function it's coming from by inspecting the PC in `siginfo`, handle the corresponding function, advance the PC, return from the signal handler, and  then execute the `ret` instruction (1 byte).

**Comment by sporksmith** [comment]
@afressancourt helped confirm what's happening: https://github.com/shadow/shadow/discussions/2271#discussioncomment-3138287

```
> objdump --disassemble=__vdso_gettimeofday /lib/modules/5.15.0-39-generic/vdso/vdso64.so

/lib/modules/5.15.0-39-generic/vdso/vdso64.so:     file format elf64-x86-64


Disassembly of section .text:

0000000000000bd0 <__vdso_gettimeofday>:
 bd0:   e9 4b fe ff ff          jmp    a20 <__cvdso_gettimeofday_data.constprop.0>

Disassembly of section .altinstr_replacement:
```

```
> objdump --disassemble=__cvdso_gettimeofday_data.constprop.0 /lib/modules/5.15.0-39-generic/vdso/vdso64.so

/lib/modules/5.15.0-39-generic/vdso/vdso64.so:     file format elf64-x86-64


Disassembly of section .text:

0000000000000a20 <__cvdso_gettimeofday_data.constprop.0>:
 a20:   55                      push   %rbp
 a21:   49 89 fa                mov    %rdi,%r10
 a24:   49 89 f3                mov    %rsi,%r11
 a27:   48 89 e5                mov    %rsp,%rbp
...
```

**Comment by sporksmith** [comment]
I have a fix locally that injects a 5-byte relative jump instead of the 13-byte absolute jump. It'll fail if the jump offset doesn't fit in 32 bits, but I think that's unlikely in practice.

If we do end up running into that we could try the `ud2; ret` approach instead, but it's a bit more complex and expensive.

**Comment by stevenengler** [comment]
> I have a fix locally that injects a 5-byte relative jump instead of the 13-byte absolute jump. It'll fail if the jump offset doesn't fit in 32 bits, but I think that's unlikely in practice.
> 
> If we do end up running into that we could try the `ud2; ret` approach instead, but it's a bit more complex and expensive.

Do we want to use multiple approaches rather than just one? Each approach has limitations/drawbacks (abs jump requires > 5 bytes, offset jump requires an offset smaller than 32 bits, etc), so would it be better to choose one and fall back to another if needed?

> It'll fail if the jump offset doesn't fit in 32 bits, but I think that's unlikely in practice.

This would require a <4GiB memory address offset right? This seems small relative to a 64-bit address space?

**Comment by sporksmith** [comment]
> Do we want to use multiple approaches rather than just one? Each approach has limitations/drawbacks (abs jump requires > 5 bytes, offset jump requires an offset smaller than 32 bits, etc), so would it be better to choose one and fall back to another if needed?

Yup, agreed.

> This would require a <4GiB memory address offset right? This seems small relative to a 64-bit address space?

Right. Spot-checking some examples, dynamically loaded libraries are loaded close to each-other and the vdso in the address space. Confirmed that this works at least for our tests in the CI. If this ends up failing later we can implement other fallbacks, such as trying to allocate a secondary trampoline area "close" to the VDSO, and/or the `ud2` approach.

**Comment by afressancourt** [comment]
I confirm that with the version following this commit, tests on my setup are running fine.

Thanks a lot !

**Comment by sporksmith** [comment]
> I confirm that with the version following this commit, tests on my setup are running fine.

Great, thanks for confirming!
