### ISSUE TITLE
Document how we decide which distros are supported

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#2309]
We should add to our "supported distros" page in the docs how we decide which versions are officially supported, and how we decide when to change the list.

I think generally we
- support at least the most recent two releases of ubuntu, debian, and fedora
- will stop supporting a distro once it hits EOL

**Comment by stevenengler** [comment]
> will stop supporting a distro once it hits EOL

This conflicts with our stability guarantees:

> More specifically, we aim to provide the following guarantees between MINOR versions:
> - [...]
> - Any supported platforms will not be dropped.

**Comment by robgjansen** [comment]
Oops. Perhaps I should add Fedora 34 back into the list then? I removed it in #2308 :(

Ubuntu 21.10 literally stops allowing you to install packages, so removing that one is a must. But I guess that one was not on our supported platforms list so removing that one would be OK.

**Comment by stevenengler** [comment]
I've added this to the 3.0 project since changing our supported platforms or changing how/when we add/remove supported platforms would require breaking one of our "stability guarantees".

**Comment by sporksmith** [comment]
Done in https://github.com/shadow/shadow/pull/2820
