### ISSUE TITLE
transparent plug-in thread management

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#236]
Transparently handle plug-ins that use threads, using [the GNU pth](http://www.gnu.org/software/pth/pth.html) to implement a user-mode non-preemptive threading engine that handles threads across all Shadow nodes.

**Comment by robgjansen** [comment]
The Tor plug-in is broken starting in version 0.2.6.3-alpha, because they added a new thread pool that the plug-in does not able to handle. It may be less work to fix it for all threads in this ticket, rather than fixing it on the Tor plug-in side of things.

**Comment by cauthu** [comment]
Hi @robgjansen , does "awaiting-push" mean you have implemented this on your local repo and just need to merge before pushing to github? :D

**Comment by robgjansen** [comment]
Yes, exactly. I have indeed implemented this feature (and many others). I'm going to do a bit more testing and get the necessary approvals, and it will appear in the next Shadow release (1.11.0).

**Comment by cauthu** [comment]
Cool. Looking forward to that! Any estimate on when 1.11.0 comes out? :)

**Comment by robgjansen** [comment]
I hope it will be out by the end of December, but it could be as short as 4 weeks.
