### ISSUE TITLE
Shadow uio is broken

### ISSUE THREAD

**Issue by Congyu-Liu** [shadow/shadow#2379]
**Describe the issue**

1. The return value of `writev` and `returnv` is incorrect. It returns the length of the last iovec. 

A test case for `writev`:
```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/uio.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#define ARRAY_LENGTH(a) (sizeof((a))/sizeof((a)[0]))
#define errExit(msg)    do { perror(msg); exit(EXIT_FAILURE); \
                                   } while (0)
int main(int argc, char *argv[]) {
        if (argc != 4) {
                exit(1);
        }
        char *serv_ip = argv[2];
        int serv_port = atoi(argv[3]);
        struct sockaddr_in sa;
        bzero(&sa, sizeof(sa));
        sa.sin_family = AF_INET;
        sa.sin_addr.s_addr = inet_addr(serv_ip);
        sa.sin_port = htons(serv_port);
        char *str_arr[] = {
                "hi",
                "hello",
        };
        struct iovec v_send[10];
        memset(v_send, 0, sizeof(v_send));
        int iov_size = ARRAY_LENGTH(str_arr);
        int total_len = 0;
        for (int i = 0; i < iov_size; i++) {
                v_send[i].iov_base = str_arr[I];
                v_send[i].iov_len = strlen(str_arr[i])+1;
                total_len += v_send[i].iov_len;
        }
        if (!strcmp(argv[1], "client")) {
                int s, ret;
                if((s = socket(AF_INET, SOCK_STREAM, 0)) == -1) {
                        errExit("socket");
                }
                
                if (connect(s, (struct sockaddr*)&sa, sizeof(sa))) {
                        errExit("connect");
                }
                ret = writev(s, v_send, iov_size);
                if (ret != total_len) {
                        fprintf(stderr, "return %d, expect %d\n", ret, total_len);
                        exit(1);
                }
        } else if (!strcmp(argv[1], "server")) {
                struct sockaddr_in ca;
                int s, ret, ca_len, c;

                if((s = socket(AF_INET, SOCK_STREAM, 0)) == -1) {
                        errExit("socket");
                }
                if ((bind(s, (struct sockaddr*)&sa, sizeof(sa)))) {
                        errExit("bind");
                }
                if ((listen(s, 10))) {
                        errExit("listen");
                }
                if ((c = accept(s, (struct sockaddr*)&ca, &ca_len)) == -1) {
                        errExit("accept");
                }
                char buf[128];
                ret = read(c, buf, sizeof(buf));
                if (ret != total_len) {
                        fprintf(stderr, "return %d, expect %d\n", ret, total_len);
                        exit(1);
                }
        }
        return 0;
}
```

Run the test case with the following configuration will fail:

```
general:
  stop_time: 10s

network:
  graph:
    type: 1_gbit_switch

hosts:
  client:
    network_node_id: 0
    processes:
    - path: a.out
      args: client 222.222.222.222 2222
  server:
    network_node_id: 0
    ip_addr: 222.222.222.222
    processes:
    - path: a.out
      args: server 222.222.222.222 2222
```

2. Simulate `readv` will crash shadow since function `_syscallhandler_readvHelper` takes mutable and non-mutable memory references at the same time, which cause assertion failures. Specifically, when `readv` reads from the file, `_syscallhandler_readvHelper` takes multiple mutable memory references.

**Comment by Congyu-Liu** [comment]
Submitted a patch (#2380) to address issue 1. Not very clear how to fix issue 2.

**Comment by stevenengler** [comment]
Good catch! Our iov support is completely untested at the moment unfortunately.

I might see another issue, where if `iov[i].iov_len == 0` (which I think should be allowed?), then two things go wrong when using writev:
1. `_syscallhandler_validateVecParams` doesn't allow an iovec buffer to have length 0
2. `result` will be 0 and we'll break out of the writev for loop too early

**Comment by stevenengler** [comment]
> Simulate readv will crash shadow since function _syscallhandler_readvHelper takes mutable and non-mutable memory references at the same time, which cause assertion failures. Specifically, when readv reads from the file, _syscallhandler_readvHelper takes multiple mutable memory references.

I think the two simplest fixes are:
1. Allocate our own buffers for the iovec passed to `regularfile_preadv2`, then copy the buffers to the plugin one-at-a-time.
2. Loop through the iovec and run `regularfile_pread` on each buffer individually.

**Comment by stevenengler** [comment]
We've fixed a lot of readv and writev bugs, now properly support preadv and pwritev, added some tests for sockets and regular files, and the example in the original post now works correctly. There may still be bugs, but they should be small and the core logic of readv/preadv/writev/pwritev now seems to work correctly.
