### ISSUE TITLE
Remove `--profile` option from setup script

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#2405]
The `setup` script has the `--profile` option to compile with gprof metadata.

We haven't made this work for Rust code, and some cursory searching didn't turn up anyone who has successfully done so. Internally we have been using `perf` instead, which doesn't require any instrumentation, and works with Rust code.

In WIP #2404 where I'm moving the compilation of most C code into Rust scripts, I'm tentatively not porting the ability to compile the C code with this option. While porting it would be feasible, it's currently of questionable and decreasing value. I'm tentatively marking the `setup` option deprecated instead, and turning it into a no-op.

**Comment by robgjansen** [comment]
The dev team agrees that `gprof` has not been useful and `perf` is the go-to choice for profiling, so we should feel free to go ahead and remove the `--profile` option.
