### ISSUE TITLE
libevent2 iovec support

### ISSUE THREAD

**Issue by vladie** [shadow/shadow#250]
yesterday i've tried to rewrite echo plugin example with libevent2.
after finishing, i've found that libevent2 socket write not working for me in shadow-plugin mode (but works as native application)
i've spent some time with gdb and have found, that my libevent2 (which i've compiled while building shadow-1.9.2) using iovec api by default (writev/readv). shadow doesn't hooks this api, and libevent2-based code doesn't work at all.
i think writev/readv must be implemented, or hooked with dummy functions, which will print "unsupported API" error.

**Comment by robgjansen** [comment]
I just finished this but haven't pushed it yet. After I push the code, it would be great if you could help test, as I don't currently have code that utilizes `readv` and `writev`.
