### ISSUE TITLE
incompatibility with openssl

### ISSUE THREAD

**Issue by vladie** [shadow/shadow#254]
openssl try to use egd daemon polling in order to get entropy for random number generation. in function RAND_query_egd_bytes it tries to connect socket with destport==0, which make shadow fault (because of line         utility_assert(sourceIP && sourcePort && destinationIP && destinationPort); in _tcp_createPacket). this must be handled in interposed 'connect' function (error must be returned instead of trying to create syn packet).

**Comment by vladie** [comment]
seems that problem go deeply. shadow tries to initialize AF_UNIX socket as AF_INET. this is bug.

**Comment by robgjansen** [comment]
Thanks for reporting!

**Comment by robgjansen** [comment]
@vladie can you check if this is still a problem using Shadow master. I think we already added support for this in #222.

**Comment by robgjansen** [comment]
Is this still a problem now that Shadow supports `AF_UNIX` sockets?

**Comment by robgjansen** [comment]
Closing because we now support AF_UNIX. If you find that a certain feature of AF_UNIX sockets is not supported or is causing weird behavior, please re-open.
