### ISSUE TITLE
assert failed on closing non bounded socket

### ISSUE THREAD

**Issue by vladie** [shadow/shadow#255]
in following code:

```
m_socket = socket(domain, SOCK_DGRAM, 0);
......
if (some_error)
{
   closesocket(m_socket);
   return false;
}
```
closesocket() makes shadow to fire assertion (socket->flags & SF_BOUND) in socket_getAssociationKey.

**Comment by robgjansen** [comment]
Correct, closing a socket that was never bound should not return error and should definitely not abort!
