### ISSUE TITLE
Build instructions need fixing for Debian stable systems

### ISSUE THREAD

**Issue by ndanger000** [shadow/shadow#258]
Debian stable still uses an old version of LLVM.  If you build a newer version, then you need to instruct cmake where to find the relevant files.  E.g., if you build llvm in /opt/llvm, then you need something like

./setup build --include=/opt/llvm-3.2/share/llvm/cmake --include=/opt/llvm-3.2/include

**Comment by robgjansen** [comment]
I just added your suggestion to https://github.com/shadow/shadow/wiki/1-Installation-and-Setup#setup-notes. Thanks!
