### ISSUE TITLE
Fix fstat interposition on 32-bit machines

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#260]
On 32-bit machines, `fstat` is called `fstat64`. This causes errors when shadow handles open and passes back a shadow fd, but then the app uses fstat and the kernel doesnt know about the shadow fd.

The symbols that we need to intercept are:

```
         U __fxstat64@@GLIBC_2.2
         U __xstat64@@GLIBC_2.2
```

More info on the shadow-support thread starting here:
http://mailman.cs.umn.edu/archives/shadow-support/2015-February/000309.html

**Comment by robgjansen** [comment]
@ndanger000 could you please try with the above fix (which is pushed to master)?

We don't currently interpose the `stat` (i.e. `__xstat`) or `statfs` functions, so I didn't bother to add interposition of `__xstat64`.

**Comment by robgjansen** [comment]
Looks like this fixed things for the person in shadow/shadow-plugin-tor#9, though it was not explicitly stated.I'm going to assume it is fixed, and close the issue.

**Comment by ndanger000** [comment]
Hi Rob,

Well, now shadow doesn't compile at all for me:

ndanner@kurtz:src$ cd shadow
ndanner@kurtz:shadow$ git pull
remote: Counting objects: 48, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 48 (delta 22), reused 22 (delta 13)
Unpacking objects: 100% (48/48), done.
 From https://github.com/shadow/shadow
    66fb3be..154db62  release    -> origin/release
    9798ad5..154db62  master     -> origin/master
  * [new tag]         v1.10.1    -> v1.10.1
Updating 66fb3be..154db62
Fast-forward
...

$ ./setup build --include=/opt/llvm-3.2/share/llvm/cmake 
--include=/opt/llvm-3.2/include
[...]
In file included from 
/home/ndanner/src/shadow/src/plugin/llvm-hoist-pass/HoistGlobals.cpp:9:
In file included from /opt/llvm-3.2/include/llvm/Pass.h:33:
In file included from 
/usr/lib/gcc/i486-linux-gnu/4.7/../../../../include/c++/4.7/string:41:
In file included from 
/usr/lib/gcc/i486-linux-gnu/4.7/../../../../include/c++/4.7/bits/char_traits.h:40:
In file included from 
/usr/lib/gcc/i486-linux-gnu/4.7/../../../../include/c++/4.7/bits/stl_algobase.h:65:
In file included from 
/usr/lib/gcc/i486-linux-gnu/4.7/../../../../include/c++/4.7/bits/stl_pair.h:61:
In file included from 
/usr/lib/gcc/i486-linux-gnu/4.7/../../../../include/c++/4.7/bits/move.h:57:
/usr/lib/gcc/i486-linux-gnu/4.7/../../../../include/c++/4.7/type_traits:256:39: 
error:
       use of undeclared identifier '__float128'
     struct __is_floating_point_helper<__float128>
                                       ^
[...]
[ 86%] Built target shadow
1 warning and 1 error generated.
make[2]: *** 
[src/plugin/llvm-hoist-pass/CMakeFiles/LLVMHoistGlobals.dir/HoistGlobals.cpp.o] 
Error 1
make[1]: *** 
[src/plugin/llvm-hoist-pass/CMakeFiles/LLVMHoistGlobals.dir/all] Error 2
make: *** [all] Error 2
2015-02-13 16:39:23,200 INFO make returned 2
2015-02-13 16:39:23,200 ERROR Non-zero return code from make.
2015-02-13 16:39:23,200 INFO returning code '2'
ndanner@kurtz:shadow$


On 2/6/15 11:29 AM, Rob Jansen wrote:
> @ndanger000 could you please try with the above fix (which is pushed to master)?
>
> We don't currently interpose the `stat` (i.e. `__xstat`) or `statfs` functions, so I didn't bother to add interposition of `__xstat64`.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/shadow/shadow/issues/260#issuecomment-73264600
>

-- 
Norman Danner - ndanner@wesleyan.edu - http://ndanner.web.wesleyan.edu
Department of Mathematics and Computer Science - Wesleyan University

**Comment by robgjansen** [comment]
That looks like an unrelated LLVM/Clang issue, probably due to updates to our code to support LLVM 3.5. Do you think its worth setting up a 32-bit VM? I don't think your error message will help me if I can't reproduce it.

**Comment by ndanger000** [comment]
Hi Rob,

No, don't bother with a 32-bit VM yet.  I've built clang 3.5.0, and 
shadow and shadow-plugin-tor both seem to compile.  But then when I try 
to run the minimal example for shadow-plugin-tor, I get an assertion error:

ndanner@kurtz:minimal$ shadow-tor -i shadow.config.xml
[2015-02-17 11:24:48.089300] shadow-tor: Data directory reset in output path
[2015-02-17 11:24:48.106565] shadow-tor: set environmental variables for 
libevent: EVENT_NOSELECT, EVENT_NOPOLL, EVENT_NOKQUEUE, EVENT_NODEVPOLL, 
EVENT_NOEVPORT, EVENT_NOWIN32
[2015-02-17 11:24:48.106661] shadow-tor: set environmental variable for 
openssl: OPENSSL_ia32cap=~0x200000200000000
[2015-02-17 11:24:48.106751] shadow-tor: calling 
'/home/ndanner/.shadow/bin/shadow 
--preload=/home/ndanner/.shadow/lib/libshadow-preload-tor.so 
/home/ndanner/src/shadow-plugin-tor/resource/minimal/shadow.config.xml', 
output directed to 
'/home/ndanner/src/shadow-plugin-tor/resource/minimal/data/shadow.log'
**
ERROR:/home/ndanner/src/shadow/src/plugin/shadow-plugin-tgen/shd-tgen-transport.c:127:void 
tgentransport_ref(TGenTransport *): assertion failed: (transport && 
(transport->magic == TGEN_MAGIC))
[2015-02-17 11:24:52.041410] shadow-tor: Shadow returned 0 in 
0:00:03.934446 seconds


On 2/13/15 9:27 PM, Rob Jansen wrote:
> That looks like an unrelated LLVM/Clang issue, probably due to updates to our code to support LLVM 3.5. Do you think its worth setting up a 32-bit VM? I don't think your error message will help me if I can't reproduce it.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/shadow/shadow/issues/260#issuecomment-74357634
>

-- 
Norman Danner - ndanner@wesleyan.edu - http://ndanner.web.wesleyan.edu
Department of Mathematics and Computer Science - Wesleyan University

**Comment by robgjansen** [comment]
OK, great! This error has already been reported in shadow/shadow-plugin-tor#9, and seen by the stack trace in [this comment](https://github.com/shadow/shadow-plugin-tor/issues/9#issuecomment-74469688). Unfortunately, this also appears to be a 32-bit issue, so I don't have any leads on it yet. Please discuss there if you have more comments about it. Thanks!
