### ISSUE TITLE
Shadow does not build on ArchLinux with llvm 3.2 or 3.5.1

### ISSUE THREAD

**Issue by Javex** [shadow/shadow#262]
I tried building Shadow today. However, it fails with the following message:

    Scanning dependencies of target shadow
    opt: Unknown command line argument '-hoist-globals'.  Try: '~/.shadow/bin/opt -help'
    opt: Did you mean '-asan-globals'?
    src/plugin/tgen/CMakeFiles/shadow-plugin-tgen.dir/build.make:53: recipe for target 'src/plugin/tgen/shadow-plugin-tgen.hoisted.bc' failed
    make[2]: *** [src/plugin/tgen/shadow-plugin-tgen.hoisted.bc] Error 1
    make[2]: Leaving directory '...'
    CMakeFiles/Makefile2:267: recipe for target 'src/plugin/tgen/CMakeFiles/shadow-plugin-tgen.dir/all' failed
    make[1]: *** [src/plugin/tgen/CMakeFiles/shadow-plugin-tgen.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....

I tried to install llvm 3.2 (download & build from source) because it could be that the feature was removed. However, I get the same error here as well.

I should note that llvm 3.2 failed a single test: `LLVM :: Bindings/Ocaml/bitwriter.ml`. I suppose this is irrelevant, but I want to note it here. Nonetheless, the 3.5.1 package is from my repositories and should thus work.

I am workong on the release branch. Should I test something else? I did find the above error message using Google but all seems to point to a different issue here.

**Comment by robgjansen** [comment]
`-hoist-globals` is an llvm plug-in added by Shadow. The error from opt indicates that Shadow had trouble building the llvm plug-in. This should be fixed in the master branch, please try it there and let me know if it works. See #257 for links to the commits that fix this.

**Comment by Javex** [comment]
Yes, #257 did indeed fix it. I don't quite get why my local install wouldn't build but as long as it works now, I am happy. Thank you.
