### ISSUE TITLE
dependencies not tracked by cmake for plug-in header files

### ISSUE THREAD

**Issue by vladie** [shadow/shadow#265]
i've found that cmake didn't tracks correctly header dependencies in case of building 'hoisted bitcode'. for example, i can build any of shadow's plugins - then change random header file and run make again - it will not rebuild anything.

**Comment by robgjansen** [comment]
I didn't notice this because I almost always use `./setup build --clean` when building. Any ideas how to fix it? Is it enough to just add the header files as dependencies?

**Comment by vladie** [comment]
seems that this is cmake problem, it can't find dependencies for targets built with compiler plugins. quick fix i've made is to add into llvmtools.cmake dependecies for ALL headers which project uses. but this solution will rebuild all project source files in case of any header file was modified (even unused in project sources). i didn't know yet how to use cmake dependecy scanner correctly.

**Comment by vladie** [comment]
solution is to add IMPLICIT_DEPENDS into building llvm code rule (into LLVMTools.cmake):

    ## the command to generate the bitcode for this file
    add_custom_command(OUTPUT ${outfile}.bc
      COMMAND ${src_bc_compiler} -g -emit-llvm ${srcdefs} ${srcflags} ${srcincludes}
        -c ${infile} -o ${outfile}.bc
      DEPENDS ${infile}
      IMPLICIT_DEPENDS CXX ${infile}
      COMMENT "Building LLVM bitcode ${outfile}.bc"
      VERBATIM
    )

**Comment by robgjansen** [comment]
Added in e5b2493c3c4643ab7ee2b02f8e80219450316404 - thanks!
