### ISSUE TITLE
Fix for #251 introduces memory leak

### ISSUE THREAD

**Issue by Skinnor** [shadow/shadow#269]
The fix for #251 (commit 9798ad55bdd99f721baa9a3c2fe816d5359207c2) introduces a memory leak. In the function "packet_getTCPHeader" a list of "selectiveACKs" is copied, which is allocated on the heap. But every function invoking "packet_getTCPHeader" allocates the header struct on the stack. The copied "selectiveACKs" are NEVER free'd, which introduces a huge memory leak.

I believe this also cause #268.

**Comment by robgjansen** [comment]
Oh, wow, thanks for noticing this! I was hoping to figure this out soon, so your report is very timely :)

**Comment by robgjansen** [comment]
Running the example in `shadow/resource/examples` at 50% packet loss before and after f8303ecdd results in this:
![shadow selacks memleak](https://cloud.githubusercontent.com/assets/788144/6833042/92e8a584-d300-11e4-9bae-17a7a9530e21.png)
