### ISSUE TITLE
Issue with  CPU pinning?

### ISSUE THREAD

**Issue by frochet** [shadow/shadow#2709]
**Describe the issue**
![image](https://user-images.githubusercontent.com/1092288/215891870-e4d22789-b4c5-424d-b8da-3ec0bfe10cd2.png)

I am running two Shadow simulations in parallel, using 64 threads each. They seem to all get pinned to the first 64 processors. 
Is that a known bug? I might investigate next week if you don't see an obvious fix.

Thanks a lot!

**Shadow (please complete the following information):**

I am running Shadow v2.4.0-34-g668fd1a8 2023-01-28--22:01:13 on a Tor simulation

**Additional context**

Ubuntu 22.04

**Comment by stevenengler** [comment]
Here's our documentation on this: https://shadow.github.io/docs/guide/parallel_sims.html.

Shadow doesn't know about other Shadow simulations running on the same machine, so it doesn't know to use a different set of CPUs. You may wish to use `taskset` to set an initial affinity for each Shadow simulation.

**Comment by frochet** [comment]
Thanks! Sorry I missed  the info within the documentation

**Comment by stevenengler** [comment]
No problem, if you think of a way we can improve this let us know!

**Comment by frochet** [comment]
Mmh shadow could write in a file which CPU have been pinned, and how many threads. The next shadow command could check that file and make the best decision?

**Comment by stevenengler** [comment]
We thought about using a similar solution, but it gets messy if a shadow sim crashes without cleaning up the file, or if running more than two simulations, or if running simulations in different environments/containers/chroots, etc.
