### ISSUE TITLE
dynamically balance host-to-thread assignment based on host load

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#275]
We could track run times for each host, and try to balance expected run times across threads by dynamically relocating hosts to other threads when appropriate.

(We could also just keep a global locked queue of all hosts, where the threads grab hosts from the queue and process them. However, this would cause high contention on this global queue, and doesn't scale with many threads.)

**Comment by jtracey** [comment]
Is there a reason this bug isn't closed? We now do a modification of the second option (i.e., work stealing) by default, right?

**Comment by robgjansen** [comment]
Good catch! Thanks!
