### ISSUE TITLE
application-space memory manager for packets

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#276]
We could add an application-space memory manager for packets and packet payloads, to avoid going to the kernel for mallocing and freeing packets so often.

**Comment by robgjansen** [comment]
Not even sure if this is a good idea, GLib's allocator may already do something similar.

**Comment by jtracey** [comment]
GLib's allocator is just a wrapper for the libc allocator (unless you're using slices). glibc however does use data structures to avoid hitting the kernel for malloc, so unless you know of something that the libc allocator doesn't handle well, yeah I wouldn't bother.

**Comment by robgjansen** [comment]
OK, thanks! I'll mark this as wontfix and close.
