### ISSUE TITLE
Unable to Install Shadow on Red Hat 6.6

### ISSUE THREAD

**Issue by AkshayaMani** [shadow/shadow#291]
1) Installed all dependancies:
sudo yum install -y gcc gcc-c++ clang clang-devel llvm llvm-devel glib2 glib2-devel igraph igraph-devel cmake make xz
sudo yum install -y python numpy scipy python-matplotlib python-networkx python-lxml
sudo yum install -y git dstat screen htop

2) Exported path of llvm, clang and clang++

3) cd shadow
    ./setup build

fatal error: too many errors emitted, stopping now [-ferror-limit=]
make[1]: *** [src/CMakeFiles/shadow.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
1 warning and 20 errors generated.
make[2]: *** [src/plugin/llvm-hoist-pass/CMakeFiles/LLVMHoistGlobals.dir/HoistGlobals.cpp.o] Error 1
make[1]: *** [src/plugin/llvm-hoist-pass/CMakeFiles/LLVMHoistGlobals.dir/all] Error 2
make: *** [all] Error 2
2015-08-12 23:25:46,715 INFO make returned 2
2015-08-12 23:25:46,715 ERROR Non-zero return code from make.
2015-08-12 23:25:46,716 INFO returning code '2'

**Comment by robgjansen** [comment]
Please send this to the mailing list <shadow-support@cs.umn.edu> for help. When running the build step, it would be more helpful to include verbose output like this:
```
./setup build -v
```
Thanks!
