### ISSUE TITLE
LLVM Hoist Pass CMakeLists syntax error

### ISSUE THREAD

**Issue by jdgeddes** [shadow/shadow#297]
In /src/plugin/llvm-hoist-pass/CMakeLists.txt there is a problem with some of the if statements.  Instead of

`if(${LLVM_INCLUDE_DIRS})`

it should be

`if(LLVM_INCLUDE_DIRS)`

otherwise if it finds anything there will be errors.

**Comment by robgjansen** [comment]
@jdgeddes does this change fix the build with your custom LLVM install?

**Comment by jdgeddes** [comment]
@robgjansen yes, other then the problems in issue #298.  But like I mentioned there I'm not sure if it's an issue with the shadow install process of LLVM, the install I'm using is probably at least a year old.

Also, not sure if this needs its own issue, but I don't think shadow is compatible with igraph v0.5.4 anymore.  Using the library results in this error:

`shadow-plugin-tgen/shd-tgen-graph.c:368: undefined reference to igraph_es_incident`

The function was added in v0.6.
