### ISSUE TITLE
run shadow.yaml

### ISSUE THREAD

**Issue by zhuxiuzhen** [shadow/shadow#2996]
cannot find package "shadow.yaml" in any of:
	/usr/lib/go-1.13/src/shadow.yaml (from $GOROOT)
	/root/go/src/shadow.yaml (from $GOPATH)
shadow: error during loading

**Comment by stevenengler** [comment]
Can you post more information? What are you trying to do and what have you tried? None of these log messages are from shadow.

**Comment by zhuxiuzhen** [comment]
yes ,I know.I just want to run the a example in shadow. it's in shadow/examples/wget2/run.sh,&nbsp; then it show the bug.So I have no ieda...





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shadow/shadow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月3日(星期六) 晚上9:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shadow/shadow] run shadow.yaml (Issue #2996)





 
Can you post more information? What are you trying to do and what have you tried? None of these log messages are from shadow.

**Comment by stevenengler** [comment]
What command are you running?

**Comment by zhuxiuzhen** [comment]
I have run the command that (1)./run.sh (2) shadow run.sh .I have try these,but these didn't work. And I think the bug has no relationship with the project, so I reload the shadow project. I follow the command from&nbsp;

https://shadow.github.io


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shadow/shadow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月3日(星期六) 晚上9:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shadow/shadow] run shadow.yaml (Issue #2996)





 
What command are you running?

**Comment by stevenengler** [comment]
Since you have gotten shadow to run in follow-up issues, I'm going to close this one.
