### ISSUE TITLE
Shadow build fails starting with LLVM 3.7.0

### ISSUE THREAD

**Issue by anonimal** [shadow/shadow#301]
Greetings Rob,

All dependencies are satisfied per the installation guide.

```bash
$ python2 ./setup build --clean --debug
...
[  0%] Built target rpth-src
[  8%] Built target rpth
[ 10%] Built target shadow-interpose
[ 70%] Built target shadow
Scanning dependencies of target LLVMHoistGlobals
[ 70%] Building CXX object src/plugin/llvm-hoist-pass/CMakeFiles/LLVMHoistGlobals.dir/HoistGlobals.cpp.o
shadow/src/plugin/llvm-hoist-pass/HoistGlobals.cpp:248:20: error: no matching function for call to 'getGetElementPtr'
                        Constant *GEP = ConstantExpr::getGetElementPtr(HoistedStruct, GEPIndexes, true);
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/llvm/IR/Constants.h:1092:20: note: candidate function not viable: no known conversion from 'llvm::GlobalVariable *' to 'llvm::Type *' for 1st argument
  static Constant *getGetElementPtr(Type *Ty, Constant *C,
                   ^
/usr/include/llvm/IR/Constants.h:1100:20: note: candidate function not viable: no known conversion from 'llvm::GlobalVariable *' to 'llvm::Type *' for 1st argument
  static Constant *getGetElementPtr(Type *Ty, Constant *C, Constant *Idx,
                   ^
/usr/include/llvm/IR/Constants.h:1108:20: note: candidate function not viable: no known conversion from 'llvm::GlobalVariable *' to 'llvm::Type *' for 1st argument
  static Constant *getGetElementPtr(Type *Ty, Constant *C,
                   ^
1 error generated.
src/plugin/llvm-hoist-pass/CMakeFiles/LLVMHoistGlobals.dir/build.make:62: recipe for target 'src/plugin/llvm-hoist-pass/CMakeFiles/LLVMHoistGlobals.dir/HoistGlobals.cpp.o' failed
make[2]: *** [src/plugin/llvm-hoist-pass/CMakeFiles/LLVMHoistGlobals.dir/HoistGlobals.cpp.o] Error 1
CMakeFiles/Makefile2:224: recipe for target 'src/plugin/llvm-hoist-pass/CMakeFiles/LLVMHoistGlobals.dir/all' failed
make[1]: *** [src/plugin/llvm-hoist-pass/CMakeFiles/LLVMHoistGlobals.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
2016-01-24 06:04:30,789 [ERROR] Non-zero return code from make.
```

So, for obvious reasons:

- Arch
```bash
$ llvm-config --version
3.7.1
$ grep -A2 "\*getGetElementPtr\(" /usr/include/llvm/IR/Constants.h
  static Constant *getGetElementPtr(Type *Ty, Constant *C,
                                    ArrayRef<Constant *> IdxList,
                                    bool InBounds = false,
--
  static Constant *getGetElementPtr(Type *Ty, Constant *C, Constant *Idx,
                                    bool InBounds = false,
                                    Type *OnlyIfReducedTy = nullptr) {
--
  static Constant *getGetElementPtr(Type *Ty, Constant *C,
                                    ArrayRef<Value *> IdxList,
                                    bool InBounds = false,
$
```

- Ubuntu LTS
```bash
$ llvm-config --version
3.4
$ grep -A2 "\*getGetElementPtr\(" /usr/include/llvm/IR/Constants.h
  static Constant *getGetElementPtr(Constant *C,
                                    ArrayRef<Constant *> IdxList,
                                    bool InBounds = false) {
--
  static Constant *getGetElementPtr(Constant *C,
                                    Constant *Idx,
                                    bool InBounds = false) {
--
  static Constant *getGetElementPtr(Constant *C,
                                    ArrayRef<Value *> IdxList,
                                    bool InBounds = false);
$
```
Sorry, I don't have a working patch (still testing); I *literally* just sat down with the code (this was on the first build). Since I'd like to pursue https://github.com/monero-project/kovri/issues/82, if I can patch this during research, then I'll be sure to send one.

**Comment by robgjansen** [comment]
First of all, make sure you grab the latest from the master branch: I just pushed version 1.11.0 a couple of days ago.

I'm not surprised to see the error from LLVM, since they change their API regularly. We'll need to find a alternative way to implement the required functionality where the API changed, and then add an #IFDEF to handle it for newer versions of LLVM. (I have not yet tried compiling against LLVM 3.7.)

**Comment by dmS0Zq** [comment]
I'm having the same problem.

Building off of master with the same command as @anonimal. Same version of LLVM, using Arch.

Here's the error in the build log. https://gist.github.com/dmS0Zq/4cc4ee76f088a5d884ad

**Comment by anonimal** [comment]
Hi @dmS0Zq, thank you for reporting/confirming.

As we have asserted, the issue is a matter of reimplementation.  For me, https://github.com/monero-project/kovri/issues/82 has been on the back-burner so I've had no time to look more into this. I *can* say that ```API migration for GEP constant factories``` was introduced in LLVM [19443c1](https://github.com/llvm-mirror/llvm/commit/19443c1bcb863ba186abfe0bda3a1603488d17f7) which coincides with their 3.5.2 release.

@robgjansen would you advise to amend build instruction documentation for clang/LLVM (version >= 3.2 || <=3.5.1) until this ticket is resolved?

**Comment by robgjansen** [comment]
I started looking into this. I verified that Shadow builds correctly on LLVM 3.5.2, 3.6.2, and first fails with LLVM version 3.7.0.

**Comment by robgjansen** [comment]
The latest master with the changes from c40cf850a2b685a744f42b4e31f1c721f96b72a0 work for me on LLVM version 3.7.0.

@anonimal @dmS0Zq can either of you verify if this fixes the issue for you? Thanks!

**Comment by robgjansen** [comment]
Just tried and it works for me on LLVM 3.7.1 as well. I'm closing as fixed, please re-open if it did not solve the issue.

**Comment by dmS0Zq** [comment]
@robgjansen HEAD now builds successfully as of 500b744, c40cf85 being a couple commits prior.

Thanks
