### ISSUE TITLE
pthread initialization error in glib 2.40.x during 'pthread_cond_init'

### ISSUE THREAD

**Issue by jtracey** [shadow/shadow#302]
Can't seem to get the latest version of shadow working.
Fresh build, Ubuntu 14.04 LTS, glib 2.40.2
```bash
$ shadow --version
Shadow v1.11.1-2-g40d5c58 2016-01-24 (built 2016-02-06)
For more information, visit https://shadow.github.io or https://github.com/shadow
$ shadow --help
GLib (gthread-posix.c): Unexpected error from C library during 'pthread_cond_init': Invalid argument.  Aborting.
Aborted (core dumped)
```
As you can see, I can get shadow --version to run fine, but anything else, including help, breaks.

**Comment by robgjansen** [comment]
This is due to a bug in `glib 2.40.2`. I believe compiling and linking against `glib 2.42.x` or greater should fix the problem. I'm not sure where exactly in glib the problem is, so I think upgrading glib is the best answer.

Please post here if upgrading glib works for you. Also, if you learn more or find a different way to work around it, please do let me know!

**Comment by shafiul** [comment]
Hi, 
How to update glib to 2.42.x in Ubuntu? 

Thanks for helping out!

**Comment by ooee123** [comment]
First post ever:
Upgrading to glib 2.42.1 worked for me. I grabbed a copy of glib 2.42.1 from here [glib 2.42.1](http://www.linuxfromscratch.org/blfs/view/7.7/general/glib2.html) then built it.

Had to include the 2.42.1 shared library files, with this guy. (I built the libraries starting at home)

`./setup build -c --include ~/glib-2.42.1/glib --include ~/glib-2.42.1 --include ~/glib-2.42.1/gmodule --library ~/glib-2.42.1/glib/.libs/ --library ~/glib-2.42.1/gmodule/.libs/ --library ~/glib-2.42.1/gthread/.libs/`

Then I'm able to perform --version and --help without aborting. Also ran a sample sim with shadow.config.xml just fine.

Also, I tried doing the same with glib 2.46.2, but I get segfaults there with both --version and --help.

**Comment by robgjansen** [comment]
Thanks @ooee123 ! The shadow setup part is a bit easier if you install the newly built glib to your `~/.shadow` directory.

```
wget http://ftp.gnome.org/pub/gnome/sources/glib/2.42/glib-2.42.1.tar.xz
tar xaf glib-2.42.1.tar.xz
cd glib-2.42.1
./configure --prefix=~/.shadow
make
make install
```

Then I think you can build shadow like this:

```
./setup build -cg
./setup install
```

**Comment by shafiul** [comment]
Thanks all, after following @robgjansen's instructions I was able to run shadow --help without any issues.

**Comment by robgjansen** [comment]
Its concerning that this bug came back in `glib 2.46.2`, so I'm leaving this ticket open so we can track down the real underlying problem here.

**Comment by robgjansen** [comment]
The bug does not seem to be present in glib `2.42`, `2.44`, or `2.48`. I can confirm that it is present at least in glib `2.40`, and possibly `2.46`.

Ubuntu 16.04.1 is currently on glib `2.48.1`, and CentOS 7 is currently on glib `2.42.2`, and there is no bug in either of those cases. I have also been using CentOS 7 with glib `2.44.1` without any issues.

**Comment by robgjansen** [comment]
Just tried glib 2.46.2 on CentOS 7 and did not have any problems. So it seems that any stable version of glib greater than 2.40 should work. If anyone has evidence otherwise, please comment.

**Comment by AMarcedone** [comment]
I am having trouble running version 1.10.2 of the code (which I need because I want to run the bitcoin plugin), and I think it is probably related to glib.
I checked out the code and did some minor modifications to build it (i.e. manually backporting commits to the cmake files to allow my recent llvm version to work) 

My glib version is 
> dpkg -s libglib2.0-0 |grep Version
> Version: 2.48.1-1~ubuntu16.04.1

When I try to run shadow --version I get segmentation faults. 
A quick investigation under gdb shows:

> gdb shadow
> GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
> This GDB was configured as "x86_64-linux-gnu".
> (gdb) r
> Starting program: /home/antonio/.shadow/bin/shadow 
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> 
> Program received signal SIGSEGV, Segmentation fault.
> 0x00007ffff6d6ea84 in g_slice_alloc () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
> (gdb) backtrace
> #0  0x00007ffff6d6ea84 in g_slice_alloc () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
> #1  0x00007ffff6d6fa06 in g_slist_prepend () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
> #2  0x00007ffff6d71c5d in g_strsplit () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
> #3  0x000000000040c3b8 in shadow_main (argc=1, argv=0x7fffffffe048) at /[...]/shadow/src/engine/shd-main.c:177
> #4  0x0000000000439cf2 in main (argc=1, argv=0x7fffffffe048) at /[...]/shadow/src/main.c:10
> (gdb) frame 3
> #3  0x000000000040c3b8 in shadow_main (argc=1, argv=0x7fffffffe048) at /[...]/shadow/src/engine/shd-main.c:177
> 177	    gchar** cmdv = g_strsplit(cmds, " ", 0);
> (gdb) print cmds
> $1 = (gchar *) 0x65e250 "/home/antonio/.shadow/bin/shadow"
> (gdb) 
> 

Tomorrow I will try to see if using a different glib version solves the problem.

**Comment by kjacks21** [comment]
In case anyone else gets this error: 
```
** The version of the run-time GLib library (2.43.0) is not compatible with the version against 
which Shadow was compiled (2.48.2). GLib message: 'GLib version too old (micro mismatch)'
```
Following @robgjansen instructions above resolved this. The only difference was changing the glib version to 2.42.2. For example: 

```
wget http://ftp.gnome.org/pub/gnome/sources/glib/2.42/glib-2.42.2.tar.xz
tar xaf glib-2.42.2.tar.xz
cd glib-2.42.2
./configure --prefix=~/.shadow
make
make install
```


My system:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

**Comment by 00h-i-r-a00** [comment]
I just installed shadow 1.10.2 (because I need to be able to use the bitcoin plugin) on Ubuntu 14.04 with glib version 2.40.2 and I don't seem to be getting any errors on shadow --help . Given that I am not getting any errors (so far), I was wondering if I should still change my glib version?

**Comment by robgjansen** [comment]
If it's not broken, why fix it? If the [Shadow examples](https://github.com/shadow/shadow/wiki/2-Simulation-Execution-and-Analysis#basic-functional-tests) are working , then I would think you should be ok.

**Comment by 00h-i-r-a00** [comment]
I ran the first example that runs tgen with 10 clients. It doesn't seem to be creating a shadow.data directory,  even though the logging seems to be coming out fine. It exits cleanly with the following last few lines:

> 
> 00:00:23.998121 [thread-0] 00:19:59.000000001 [tgen-message] [server1~11.0.0.11] [_tgendriver_onHeartbeat] [driver-heartbeat] transfers-completed=0 bytes-read=0 bytes-write=0 transfers-error=0
> 00:00:23.998136 [thread-0] 00:19:59.000000001 [tgen-message] [server2~11.0.0.12] [_tgendriver_onHeartbeat] [driver-heartbeat] transfers-completed=0 bytes-read=0 bytes-write=0 transfers-error=0
> 00:00:23.998192 [thread-0] 00:19:59.000000001 [tgen-message] [server3~11.0.0.13] [_tgendriver_onHeartbeat] [driver-heartbeat] transfers-completed=0 bytes-read=0 bytes-write=0 transfers-error=0
> 00:00:23.998214 [thread-0] 00:19:59.000000001 [tgen-message] [server4~11.0.0.14] [_tgendriver_onHeartbeat] [driver-heartbeat] transfers-completed=0 bytes-read=0 bytes-write=0 transfers-error=0
> 00:00:23.998230 [thread-0] 00:19:59.000000001 [tgen-message] [server5~11.0.0.15] [_tgendriver_onHeartbeat] [driver-heartbeat] transfers-completed=0 bytes-read=0 bytes-write=0 transfers-error=0
> 00:00:23.999269 [thread-0] n/a [shadow-message] [n/a] [_topology_clearCache] path cache cleared, spent 0.000000 seconds computing 0 shortest paths
> 00:00:00.000000 [thread-0] n/a [shadow-message] [n/a] [master_free] Shadow v1.10.2 (built 2017-03-08) shut down cleanly at 2017-03-08 22:11:37

Would that something to do with the glib version?

**Comment by 00h-i-r-a00** [comment]
Also I just installed bitcoin's plugin using [these](https://github.com/shadow/shadow-plugin-bitcoin/wiki) instructions, and then ran the basic example:

```
mkdir run
cd run
../src/bitcoind/shadow-bitcoind -y -i ../resource/shadow.config.xml -r -t | grep -e "received: getaddr" -e "received: verack"
```

I am getting this after running the above example:

> 
> fieldsofgold@fieldsofgold-VirtualBox:~/shadow-plugin-bitcoin/run$ ../src/bitcoind/shadow-bitcoind -y -i ../resource/shadow.config.xml -r -t | grep -e "received: getaddr" -e "received: verack"
> copying /home/fieldsofgold/shadow-plugin-bitcoin/run/data/bcdnode1
> copying /home/fieldsofgold/shadow-plugin-bitcoin/run/data/bcdnode2
> [2017-03-09 00:31:08.029713] bitcoind: Data directory reset in output path
> [2017-03-09 00:31:08.058293] bitcoind: set environmental variables for libevent: EVENT_NOSELECT, EVENT_NOPOLL, EVENT_NOKQUEUE, EVENT_NODEVPOLL, EVENT_NOEVPORT, EVENT_NOWIN32
> [2017-03-09 00:31:08.058512] bitcoind: calling '/home/fieldsofgold/.shadow/bin/shadow --preload=/home/fieldsofgold/.shadow/lib/libshadow-preload-bitcoind.so  /home/fieldsofgold/shadow-plugin-bitcoin/resource/shadow.config.xml', output directed to '/home/fieldsofgold/shadow-plugin-bitcoin/run/data/shadow.log'
> write skipping worker
> gmodule init bitcoind
> read skipping worker
> check_init done
> read skipping worker
> gmodule init bitcoind
> check_init done
> pthread_key_create:0x7ffa3e0da3a0
> pthread_create:0
> pthread_key_create:0x7ffa3e0da3d0
> pthread_create:1
> pthread_key_create:0x1877288
> pthread_create:2
> passing to pth_pthread_create
> returning from pth_pthread_create
> pthread_key_create:0x7ffa3e0da63c
> pthread_create:3
> pthread_mutex_lock: initializing
> pthread_key_create:0x7ffa3e0da5d0
> pthread_create:4
> passing to pth_pthread_create
> returning from pth_pthread_create
> passing to pth_pthread_create
> returning from pth_pthread_create
> passing to pth_pthread_create
> returning from pth_pthread_create
> passing to pth_pthread_create
> returning from pth_pthread_create
> passing to pth_pthread_create
> returning from pth_pthread_create
> passing to pth_pthread_create
> returning from pth_pthread_create
> passing to pth_pthread_create
> returning from pth_pthread_create
> pthread_key_create:0x7ffa3e0da3a0
> pthread_create:0
> pthread_key_create:0x7ffa3e0da3d0
> pthread_create:1
> pthread_key_create:0x1a05b88
> pthread_create:2
> passing to pth_pthread_create
> returning from pth_pthread_create
> pthread_key_create:0x7ffa3e0da63c
> pthread_create:3
> pthread_mutex_lock: initializing
> pthread_key_create:0x7ffa3e0da5d0
> pthread_create:4
> passing to pth_pthread_create
> returning from pth_pthread_create
> passing to pth_pthread_create
> returning from pth_pthread_create
> passing to pth_pthread_create
> returning from pth_pthread_create
> passing to pth_pthread_create
> returning from pth_pthread_create
> passing to pth_pthread_create
> returning from pth_pthread_create
> passing to pth_pthread_create
> returning from pth_pthread_create
> passing to pth_pthread_create
> returning from pth_pthread_create
> write: going to pth fd:22
> pthread_mutex_lock: initializing
> 00:00:00.526166 [thread-0] 00:00:13.603000000 [bitcoind-message] [bcdnode2~11.0.0.1] [CLogPrintStr] received: verack (0 bytes)
> 00:00:00.527154 [thread-0] 00:00:13.603000000 [bitcoind-message] [bcdnode1~11.0.0.2] [CLogPrintStr] received: verack (0 bytes)
> 00:00:00.537597 [thread-0] 00:00:13.804000000 [bitcoind-message] [bcdnode2~11.0.0.1] [CLogPrintStr] received: verack (0 bytes)
> 00:00:00.537742 [thread-0] 00:00:13.804000000 [bitcoind-message] [bcdnode2~11.0.0.1] [CLogPrintStr] received: getaddr (0 bytes)
> 00:00:00.538197 [thread-0] 00:00:13.804000000 [bitcoind-message] [bcdnode1~11.0.0.2] [CLogPrintStr] received: verack (0 bytes)
> 00:00:00.538338 [thread-0] 00:00:13.804000000 [bitcoind-message] [bcdnode1~11.0.0.2] [CLogPrintStr] received: getaddr (0 bytes)
> [2017-03-09 00:31:09.958384] bitcoind: Shadow returned 0 in 0:00:01.899714 seconds

The common thing between running the vanilla shadow and its bitcoin version is that in both cases 0 bytes are being read and written, is that expected behavior? 

PS: apologize for the cutouts in the log above, they seem to be getting in there because of the dashes.

**Comment by robgjansen** [comment]
This does not appear to be a glib issue.

**Comment by 00h-i-r-a00** [comment]
Is there a way I could debug this? Any particular areas I should look into? Also maybe I should open a separate issue for this? 
Thanks!

**Comment by robgjansen** [comment]
If you don't mind, please open a separate issue in [the shadow-plugin-bitcoin issue tracker](https://github.com/shadow/shadow-plugin-bitcoin/issues) and move your comments above there (and delete them here if you think they are out of scope for this issue).
