### ISSUE TITLE
Setup Problem

### ISSUE THREAD

**Issue by droofe** [shadow/shadow#304]
I had a couple of problems getting the setup to run on this program. With the installation of clang, clang++, and llvm of version 3.6, I had to change a large amount of the CMake files before this would run properly.

**Comment by robgjansen** [comment]
I just pushed a commit that might help. Could you try the current master (at or after commit 0b9ab87ac1034a79fc5c762f931b5a3d6e588e64) and let me know if that works smoothly with your installation of clang/llvm? If you get errors, could you post the relevant message? Thanks!

**Comment by robgjansen** [comment]
I'm going to assume that the above commit fixed this issue.

If it didn't, then use the just-released Shadow version 1.12.0. We have now removed LLVM/Clang as a component in the build process, along with a host of other improvements. (The wiki pages have been updated to be consistent with installing v1.12.0.)
