### ISSUE TITLE
--profile produces broken builds

### ISSUE THREAD

**Issue by jtracey** [shadow/shadow#306]
When compiling with -o/--profile, for gprof support, broken binaries are built, to the point that the code doesn't even reach shadow's main function. 

gdb backtrace: https://gist.github.com/jtracey/796f5f25de0d43b0e9248639346160ec#file-shadow-gprof-bt

It looks like gprof's call to calloc is being interposed during the initialization, and being hit by the limit in [this line](https://github.com/shadow/shadow/blob/ef12abc10041deb2f4495d1e455341dc999138f8/src/plugin/shd-interposer.c#L649).

Some potential solutions are increasing the size of the buffer, finding a way to stop gprof's calls from being interposed, and just switching to a different profiler in the build script (i.e. #187).

In the mean time, is there another means of profiling that should be used?

**Comment by robgjansen** [comment]
Unfortunately, I have not gotten any profiling mechanism to work properly yet. It would be great to have some help working this out so profiling can be useful to us again.

**Comment by robgjansen** [comment]
@jtracey do you know if this is still an issue in v1.12.0?

**Comment by jtracey** [comment]
So elf-loader can't use -pg, because gprof assumes a GOT (which obviously doesn't exist until elf-loader sets it up). I've also learned that gprof doesn't work if you try to use it on shared objects. If we just move the -pg flag from the global cmake file to the one in ./src/main, it looks like everything works fine.

The problem then being that this only profiles the core of Shadow, not any libraries, plugins, or elf-loader. Even worse, gprof only measures active CPU and call counts, and I would expect the core of Shadow will mostly have performance impacts as a result of blocking (I/O and barriers, in the logger and scheduler respectively). So even if it "works", it's probably not particularly helpful. But it's also easy to set up, so probably no harm either.

**Comment by robgjansen** [comment]
OK, I will make this change. It will give at least some info about Shadow, though we might be better off using `perf` most of the time anyway. Also, I added gprof info to the developers guide on the wiki.
