### ISSUE TITLE
add support for python interpreter

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#307]
Taken from @Javex commits here: 
  + Javex/shadow@ 3a84703ba79d35070ee7c78818891ba2a4c9cffa
  + Javex/shadow@ c70cbb8b4ba64a98d7e12702f4761a9739245d3e

**Comment by cauthu** [comment]
Hi Rob,
Two related questions: How stable is this python support? and which version of python is supported?
I'm guessing the interpreter is just a C program, so the answers are "solid" and "all versions," respectively?
Thanks,

**Comment by robgjansen** [comment]
@Javex was preparing a plugin for the shadow-plugin-extras repository that could be used to run python. He ran into some Shadow bugs that I am now trying to fix. So, until he shares his plug-in, it is not yet ready for use. (I have little experience using python in Shadow myself.)

See some more recent info here;
http://mailman.cs.umn.edu/archives/shadow-support/2016-June/000520.html

**Comment by cauthu** [comment]
Ok thanks; I will stick with C then.

**Comment by Javex** [comment]
If you actually have a Python use case I would be very interested in having you run it to test my implementation. I would say it is moving towards a somewhat finished state now so you should be able to try it. Check it out here: https://github.com/Javex/shadow-plugin-extras/ The ´tests´ directory has an implementation of echo client and server but it should be straightfoward to use.

**Comment by Javex** [comment]
I'm glad to announce Python 2 support is in and tested with the simulation provided with the plugin. Let me know what you think if you decide to run it.

**Comment by robgjansen** [comment]
@Javex do you think it's worth merging into https://github.com/shadow/shadow-plugin-extras now that python2 is working? (Then you could do a separate merge for python 3.) Though if you want to merge now, I would ask that you first update the README for your plugin first :-)

**Comment by Javex** [comment]
@robgjansen Created a PR here: https://github.com/shadow/shadow-plugin-extras/pull/6
