### ISSUE TITLE
getGlobalContext() is not supported anymore

### ISSUE THREAD

**Issue by haxxpop** [shadow/shadow#309]
I saw you use getGlobalContext() in src/plugin/llvm-hoist-pass/HoistGlobals.cpp. I'm here to inform you that, due to llvm's commit [41b016e569](https://github.com/llvm-mirror/llvm/commit/41b016e569802fa3effe8a25fb84dd00f647d112), getGlobalContext is not supported anymore.

Do you have any plan in the future to fix this issue?

**Comment by robgjansen** [comment]
Thanks, I was not aware of that. I'm not that familiar with LLVM, so I'm not sure how to fix this. If you have any suggestions, or know someone that could help, that would be awesome! Thanks!
