### ISSUE TITLE
Segmentation Fault when build with LLVM 3.8.0

### ISSUE THREAD

**Issue by haxxpop** [shadow/shadow#310]
I built it successfully, but, when I ran the executable, I got the "Segmentation Fault".
I don't know why. Does anyone have the same issue?

**Comment by robgjansen** [comment]
I haven't tried LLVM 3.8.0 yet. Is this related to #309?

**Comment by haxxpop** [comment]
No. The issue #309 occurs only when I use the latest LLVM from the git repo. So, I used LLVM 3.8 instead. It is built successfully with 3.8 but I got the "Segmentation Fault" when I ran it.

**Comment by lixf** [comment]
I have a similar issue. What does your stack trace say? 
Mine is: 
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6d628b4 in g_slice_alloc (mem_size=mem_size@entry=16) at /build/glib2.0-meArNm/glib2.0-2.46.2/./glib/gslice.c:827
827	/build/glib2.0-meArNm/glib2.0-2.46.2/./glib/gslice.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6d628b4 in g_slice_alloc (mem_size=mem_size@entry=16) at /build/glib2.0-meArNm/glib2.0-2.46.2/./glib/gslice.c:827
Python Exception <class 'TypeError'> iter() returned non-iterator of type '_iterator': 
#1  0x00007ffff6d63836 in g_slist_prepend (list=list@entry=0x0, data=0x69b280) at /build/glib2.0-meArNm/glib2.0-2.46.2/./glib/gslist.c:254
#2  0x00007ffff6d65990 in g_strsplit (string=0x69b250 "/home/xiaofan/.shadow/bin/shadow --help", delimiter=0x47c8c8 " ", max_tokens=2147483646)
    at /build/glib2.0-meArNm/glib2.0-2.46.2/./glib/gstrfuncs.c:2339
#3  0x0000000000413800 in shadow_main (argc=2, argv=0x7fffffffddf8) at /home/xiaofan/Private/test/shadow/src/engine/shd-main.c:177
#4  0x0000000000457592 in main (argc=2, argv=0x7fffffffddf8) at /home/xiaofan/Private/test/shadow/src/main.c:10
