### ISSUE TITLE
Update LLVM getGetElementPtr usage

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#312]
The API changed sometime before LLVM version 3.8.

https://github.com/llvm-mirror/llvm/commit/19443c1bcb863ba186abfe0bda3a1603488d17f7

**Comment by dmS0Zq** [comment]
Already fixed in at one spot in c40cf850a2b685a744f42b4e31f1c721f96b72a0. If this is the only spot getGetElementPtr is used, why did I run into it??

**Comment by dmS0Zq** [comment]
That *is* the only place getGetElementPtr is used. I must have built with one version of clang and then updated clang. 

This issue can be closed.

**Comment by robgjansen** [comment]
Thanks for following up!
