### ISSUE TITLE
writev() not working, thus libevent not working

### ISSUE THREAD

**Issue by cauthu** [shadow/shadow#317]
libevent uses `writev()`, e.g., for its `bufferevent_write()`. But shadow's emulation of `writev()` is incorrectly calling the real `writev()` with its emulated fd, leading to `"Bad file descriptor"` error.

Attached is a very minimal program ([mytest.c.txt](https://github.com/shadow/shadow/files/441431/mytest.c.txt) -- not allowed to attach `.c` files) where the server simply prints to stdout whatever the client sends.

### If client uses `write()`
then things work as expected.

client's stdout:
```
client begin dispatching
we are now connected to server --> send it a msg
5124095576030409:15:19.18446744073708582294 [thread-0] 00:00:02.000000003 [shadow-warning] [node~11.0.0.1] [shd-process.c:2059] [process_emu_write] _____ begin emu_write(), fd= 24
write(v) error [Operation now in progress]
```
server's stdout:
```
server begin dispatching
server has accepted a new connection
    server received 10 bytes: 1..4..7..0
```
simulator's log contains (patch [shd-process.c.patch.txt](https://github.com/shadow/shadow/files/441433/shd-process.c.patch.txt)):
```
5124095576030409:14:49.18446744073709246248 [thread-0] 00:00:02.000000003 [shadow-warning] [node~11.0.0.1] [shd-process.c:2059] [process_emu_write] _____ begin emu_write(), fd= 24
00:00:00.012265 [thread-0] 00:00:02.000000003 [shadow-warning] [node~11.0.0.1] [shd-process.c:2085] [process_emu_write] _____ emu_sendHelper() returned 10, strerror= [Operation now in progress]
```

### if client uses `writev()`
then it fails to send the message.

client's stdout:
```
client begin dispatching
we are now connected to server --> send it a msg
5124095576030409:13:29.18446744073709331888 [thread-0] 00:00:02.000000003 [shadow-warning] [node~11.0.0.1] [shd-process.c:2153] [process_emu_writev] _____ begin emu_writev(), fd= 24
write(v) error [Bad file descriptor]
```
server's stdout:
```
server begin dispatching
server has accepted a new connection
```
simulator's log contains:
```
5124095576030409:13:29.18446744073709331888 [thread-0] 00:00:02.000000003 [shadow-warning] [node~11.0.0.1] [shd-process.c:2153] [process_emu_writev] _____ begin emu_writev(), fd= 24
00:00:00.012396 [thread-0] 00:00:02.000000003 [shadow-warning] [node~11.0.0.1] [shd-process.c:2195] [process_emu_writev] _____ emu_writev() called write(), fd= 24,  totalIOLength= 10, totalBytesWritten= -1, strerror [Bad file descriptor]
```

**Comment by cauthu** [comment]
start the server and the client in the simulation xml file:
```
    <node id="node" geocodehint="US">
        <application plugin="mytest" time="1" arguments="s" />
        <application plugin="mytest" time="2" arguments="c" />
    </node>
```

**Comment by cauthu** [comment]
(original shadow-support email thread http://mailman.cs.umn.edu/archives/shadow-support/2016-August/000559.html)

**Comment by cauthu** [comment]
I guess this issue is related to #250

**Comment by robgjansen** [comment]
@cauthu Thanks for reporting!

Could you please add your test cases into the existing file test in `shadow/test/file/shd-test-file.c`, and submit a pull request? You should write the test in a way that it will succeed when run on Linux. The other tests in that file provide good examples.

That will help me debug this issue. Thanks!

**Comment by robgjansen** [comment]
I found a bug, and I think the following is all that is needed for the fix:

```
diff --git a/src/host/shd-process.c b/src/host/shd-process.c
index 014b4f6..d8f142e 100644
--- a/src/host/shd-process.c
+++ b/src/host/shd-process.c
@@ -2178,7 +2178,7 @@ ssize_t process_emu_writev(Process* proc, int fd, const struct iovec *iov, int i
                 ssize_t totalBytesWritten = 0;
                 if(bytesCopied > 0) {
                     /* try to write all of the bytes we got from the iov buffers */
-                    totalBytesWritten = write(fd, tempBuffer, bytesCopied);
+                    totalBytesWritten = process_emu_write(fd, tempBuffer, bytesCopied);
                 }
 
                 g_free(tempBuffer);
```

Let me know if that works and I will commit.

**Comment by cauthu** [comment]
> +                    totalBytesWritten = process_emu_write(fd, tempBuffer, bytesCopied);

Looks like that will change the context again inside `process_emu_write()` to `PCTX_SHADOW`, which is already the active one, so it's an unnecessary change; is that expensive?

**Comment by robgjansen** [comment]
> Looks like that will change the context again inside process_emu_write() to PCTX_SHADOW, which is already the active one, so it's an unnecessary change

That isn't right - I think it is in fact necessary. The first time you call writev, it comes from the PLUGIN context, and then enters the PTH context inside of the if statement in process_emu_writev. Pth will then handle the blocking and  eventually will call back into process_emu_writev a second time, and on the second time around it enters the else statement and then goes into shadow to do the actual write the the shadow fd.

You can see process_emu_readv works similarly.

**Comment by cauthu** [comment]
ah ok; pardon my naivety :)

**Comment by cauthu** [comment]
pull req #318 created

**Comment by robgjansen** [comment]
@cauthu The file test passes for me with the above commit. I assume `readv` and `writev` also work for sockets, correct? If so, do you want it tested? I think it might make sense to separate the test cases that you just added into a new `test/iov` folder, and then we could add iov test for both files and sockets into that file. Thoughts?

**Comment by cauthu** [comment]
yep, `readv` and `writev` should work for sockets, too, and should be tested. I'm not sure how to do two processes in the test; or maybe just one process that connects to itself?

**Comment by cauthu** [comment]
(It seems fine to add a separate `test/iov` folder)

**Comment by robgjansen** [comment]
You could either connect a single process to itself, or see the `test/tcp` for an example of doing multiple processes that connect to each other.

**Comment by cauthu** [comment]
created pull req #319 . the non-shadow test passes, but the shadow test is failing

**Comment by cauthu** [comment]
phew! thx!
