### ISSUE TITLE
C++ static instances not being constructed

### ISSUE THREAD

**Issue by aliclark** [shadow/shadow#320]
In the following code, the line "Test my_test(4);" results in the variable memory being initialised to all zero, leading to "test 0 0" being printed instead of "test 2 4".

The other code is included to show that they work fine.

``` c++
#include <stdio.h>

typedef struct _Hello Hello;
struct _Hello {
    /* the epoll descriptor to which we will add our sockets.
     * we use this descriptor with epoll to watch events on our sockets. */
    int ed;

    /* track if our client got a response and we can exit */
    int isDone;

    /* storage for client mode */
    struct {
        int sd;
        char* serverHostName;
        int serverIP;
    } client;

    /* storage for server mode */
    struct {
        int sd;
    } server;
};
static struct _Hello my_hello = { 1,2, {3, 0, 4}, {5} };
static struct _Hello* my_hello_p = &my_hello;

class Test {
public:
   Test(int arg) : foo(2) {
     fromarg = arg;
   }
   int foo = 1;
   int fromarg = 3;
};

Test my_test(4);
Test* my_test_p = &my_test;

int main(void) {
    Test local_test(4);
    Test* local_test_p = &local_test;

    printf("hey %d\n", my_hello.server.sd);
    printf("hey %p %p\n", &my_hello, my_hello_p);
    printf("test %d %d\n", my_test.foo, my_test.fromarg);
    printf("test %p %p\n", &my_test, my_test_p);
    printf("local test %d %d\n", local_test.foo, local_test.fromarg);
    printf("local test %p %p\n", &local_test, local_test_p);
}
```

> hey 5
> hey 0x7f85dfc68058 0x7f85dfc68058
> test 0 0
> test 0x7f85dfc68040 0x7f85dfc68040
> local test 2 4
> local test 0x7f85e2c4cf48 0x7f85e2c4cf48

**Comment by cauthu** [comment]
probably underlying cause for some issues with logging libraries like google glog, etc. (#315)

**Comment by robgjansen** [comment]
Could someone please turn this into a test case in the `shadow/src/test` directory, and submit a pull request? The test case should pass when run outside of Shadow. That way we will have a better idea when we have Shadow working correctly, and future Shadow versions will benefit from the test. Thanks!

**Comment by robgjansen** [comment]
I'm not sure if this is still an issue in the latest v1.12.0 that I just released today.
