### ISSUE TITLE
Rename/Repurpose --host-filter option in plot-shadow.py

### ISSUE THREAD

**Issue by pastly** [shadow/shadow#325]
It's a misnomer. It only filters relays in `plot_tor`. It doesn't filter clients in the tgen graphs or anything else. 

Would a host filter that filters in every graphing function be correct? Maybe. Having `['client', 'relay', 'thority']` as the filters would get us present-day behavior. Having `['client', 'relaymiddle123']` would still let all clients through the filter in tgen graphing, but would narrow the tor graphs down to just 123 (the point of this feature to begin with).

There's also the possibility of one list of filters per class of graphs. The command line option names for that though could be quite long.

**Comment by robgjansen** [comment]
Let's add regex filters. I have a fix.
