### ISSUE TITLE
shd-library.h not found

### ISSUE THREAD

**Issue by lamiaaMB** [shadow/shadow#329]
I'm trying to include "shd-library.h" in our plugin, but it can not be found in the ~/.shadow/include/ directory.
Any ideas ?

**Comment by robgjansen** [comment]
If you are building with the latest stable Shadow `v1.11.2`, then you should no longer need to include `shd-library.h`. Just write your plug-in code as you would to run it in any standard linux distro.

I know for sure that at least these two plug-in examples have been updated for shadow `v1.11.2`:
https://github.com/shadow/shadow-plugin-extras/tree/master/hello
https://github.com/shadow/shadow-plugin-extras/tree/master/echo

The CMake files there should show you how to build your code.

**Comment by robgjansen** [comment]
Please re-open if this issue is not fixed.
