### ISSUE TITLE
Bad for throughput: unordered input buffer counts against rwnd

### ISSUE THREAD

**Issue by pastly** [shadow/shadow#334]
The bad commit: https://github.com/shadow/shadow/commit/f80a733cd7f41d28b16c10eca84716c9670586b8

As mentioned in an email, there were three recent TCP-related commits.

- b250f7d update consideration of dubious acks ("without-2")
- f80a733 unordered input buffer counts against rwnd ("after")
- 7f074be disable tcp auto-tuning when user sets buf size ("without-1")

The attached graphs plot three lines: one for each _individually cherry-picked_ commit applied on top of 21f35595c4, a recent unrelated commit on master, qtime shadow branch, and glibhack shadow branch.

All three were running the same version of KIST.

[shadow.results.pdf](https://github.com/shadow/shadow/files/748709/shadow.results.pdf)

**Comment by robgjansen** [comment]
Thanks! In case this is only a problem in KIST, we should do vanilla runs of the `after` case.

**Comment by pastly** [comment]
'v-after' is as "after" is above, except vanilla instead of kist. All the other lines are the same exact data.

[shadow.results.pdf](https://github.com/shadow/shadow/files/748935/shadow.results.pdf)
