### ISSUE TITLE
tcp_getInfo returns their rcv_space instead of our rcv_space

### ISSUE THREAD

**Issue by pastly** [shadow/shadow#335]
This is helpful for what I need to be doing, but my dive into the kernel says that that's backwards.

Evidence:

- tcp\_rcv\_space\_adjust in [tcp_input.c](http://lxr.free-electrons.com/source/net/ipv4/tcp_input.c#L580) updates rcv_space.space whenever data is copied to user space. rcv_space.space is what ends up in tcp_info->rcv_space

**Comment by robgjansen** [comment]
@pastly do you know if this is still an issue in v1.12.0? I can't find a commit that references fixing this problem.

**Comment by pastly** [comment]
Looks like it is still an issue. The last meaningful commit that touched the offending line is 3e98e8443 (the introduction of cubic).

**Comment by robgjansen** [comment]
The lastWindow is the window we received from the other side:
```
tcpinfo->tcpi_rcv_space = (u_int32_t)tcp->receive.lastWindow;
```

This needs to be changed to our receive window:
```
tcpinfo->tcpi_rcv_space = (u_int32_t)tcp->receive.window;
```

https://github.com/shadow/shadow/blob/71fec610864a5ddbfb4e78cfa0652e0ca6c03de9/src/main/host/descriptor/shd-tcp.c#L1223

Thanks @pastly
