### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by AudiTTRSi** [shadow/shadow#338]
Hi
I did find any contact here on gitsite so i am writing like this. I am trying to build shadow simulator for tor.
I followed steps of your tutorial for buidling shadow simulator but i encountered errors.
After this step:
`./setup build`

I get following error: 
![build_error](https://cloud.githubusercontent.com/assets/6359197/24261294/d6ac6816-0ff6-11e7-825a-5a19661c113b.JPG)

I am using Fedora release 25 (Twenty Five), VMWare 12 player.

**Comment by robgjansen** [comment]
Could you please make the full output of the setup command available? That will include the version of CMake and Clang that you are using.

**Comment by robgjansen** [comment]
Also, you should take a look at #337 because I suspect your solution will be similar to that one.

**Comment by AudiTTRSi** [comment]
Thank you robgjansen. I will have al look at #337 an read it through.


![output_setup](https://cloud.githubusercontent.com/assets/6359197/24286389/49d047b2-1075-11e7-90eb-4968dd022133.JPG)

**Comment by robgjansen** [comment]
I just released Shadow version 1.12.0. We have now removed LLVM/Clang as a component in the build process, along with a host of other improvements. Could you please try installing the latest from master? (The wiki pages have been updated to be consistent with installing v1.12.0.)

**Comment by robgjansen** [comment]
Please re-open if this problem still exists.
