### ISSUE TITLE
Allow non-random payload in tgen

### ISSUE THREAD

**Issue by jvsg** [shadow/shadow#341]
It seems as if tgen can only transfer random bytes of data. Would be great if user determined bytes could be sent as payload.

**Comment by robgjansen** [comment]
Seems like a nice feature. Any suggestions on how to implement that?

Maybe in the `transfer` action, you would give a `data` attribute and set your data bytes there, rather than setting a `size` attribute?
https://github.com/shadow/shadow/wiki/3-Simulation-Customization#actions-vertices

**Comment by jvsg** [comment]
My approach is a little different than yours. I think since the data can get a few megabyte long, so we shouldn't just dump it in the xml file. We would need to add an attribute `deterministic-payload` with the possible values `yes` and `no`, with the default value `no`. 

If the vertex has this attribute set to `yes`, then the corresponding function would be called (which we'll have to add) instead of `_tgentransfer_getRandomString(...)`.

We would also need to add an attribute that gives the server's document root, and on the client's side the relative path of the document that it wants to get.

I looked at Filetransfer plugin, but since it's broken I guess we'll have to either fix that or this.

Also, I want to use this feature along with `shadow-plugin-tor`. Do you think it would work fine?

**Comment by robgjansen** [comment]
It should work fine with shadow-plugin-tor.

Have you taken a look at the `web` plugin in the extras repo:
https://github.com/shadow/shadow-plugin-extras/tree/master/web

It seems like that might be more useful for your use case, and it may be easier to get that running in the latest shadow.

**Comment by jvsg** [comment]
Thanks for pointing me to `web` plugin.

But I need to handle UDP traffic and this plugin won't help in that case. However, we could tweak the code a little (like changing `SOCK_STREAM` to `SOCK_DGRAM` and so on..).

So the question remains, which one is easier? Fixing the broken `filetransfer` or allowing non-random payload in `tgen` or making HTTP work over UDP.

**Comment by jvsg** [comment]
Ping

**Comment by robgjansen** [comment]
I just realized that UDP is not implemented in `tgen` either. Support for it was envisioned in my original design, but I never got that far. I don't think `tgen` as currently implemented would cope well if packets get dropped... `tgen` also wasn't designed to handle document root and relative file path requests, it was meant to be different from the usual HTTP sort of behavior.

Therefore, my preference would be to tweak the web plugin, to allow UDP mode and anything else you need for your use case. Ideally, I think you would add UDP as an option, but it would really be up to you on how you would want to implement it for your needs.

Hope that helps!
