### ISSUE TITLE
Support SO_BROADCAST udp socket option with getsockopt

### ISSUE THREAD

**Issue by Nashatyrev** [shadow/shadow#3439]
**Describe the issue**

The followup issue for #3435 

Java [Netty library](https://github.com/netty/netty) (widely adopted jvm network lib) [asks](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/AbstractChannel.java#L547) for this socket option prior to binding a UDP port. No workarounds on a client code side were found for this. 

The stub from #3434 draft PR worked for me, however it doesn't look like a legit solution

**To Reproduce**
Please check the #3435 reproduce section 

**Operating System (please complete the following information):**
Please check the #3435 

**Shadow (please complete the following information):**
Please check the #3435

**Comment by stevenengler** [comment]
You only need support for this option with `getsockopt`, and not `setsockopt`, is that correct?

Supporting `getsockopt` is easy since we can just return 0 (since shadow doesn't emulate broadcast sockets). But supporting `setsockopt` might be more difficult since then we'd actually need to support the feature.

**Comment by ppopth** [comment]
> You only need support for this option with `getsockopt`, and not `setsockopt`, is that correct?

It seems so from what I see in https://github.com/shadow/shadow/pull/3434

**Comment by Nashatyrev** [comment]
> You only need support for this option with `getsockopt`, and not `setsockopt`, is that correct?

Right, till now I've captured just `getsockopt` call. 

> Supporting `getsockopt` is easy since we can just return 0 (since shadow doesn't emulate broadcast sockets). 
> But supporting `setsockopt` might be more difficult since then we'd actually need to support the feature.

Probably setting `SO_BROADCAST` option to `false` could just be ignored instead of returning error? Looks like a fair option which could prevent another potential failure
