### ISSUE TITLE
Providing a standard 'Linux' OS name instead of 'shadowsys'

### ISSUE THREAD

**Issue by Nashatyrev** [shadow/shadow#3440]
**Describe the issue**

Followup issue to #3435 

Java has 'shadowsys' as the `os.name` system property when running under Shadow instead of a standard `Linux` string. Some libraries with platform specific components may depend on this property and fail if the OS name is unknown.

The workaround would be supply this system property manually via JVM CLI option `-Dos.name=Linux`

TBH I'm not quite sure where this value is retrieved from (@stevenengler mentioned `uname`) 

**To Reproduce**

Run the following simple Java class under Shadow `java OsName.java` :
```java
public class OsName {
    public static void main(String[] args) {
        System.out.println(System.getProperty("os.name"));
    }
}
```

**Operating System:**
Please check the #3435 

**Shadow:**
Please check the #3435

**Comment by ppopth** [comment]
> TBH I'm not quite sure where this value is retrieved from (@stevenengler mentioned `uname`)

Yes, it's from `uname` syscall (see `man syscalls` to see it's a syscall)

```bash
~/adhoc$ strace -f java OsName 2>&1 | grep 'uname'
[pid 96188] uname({sysname="Linux", nodename="thinkpad-t14", ...}) = 0
```

The change will be just one line though https://github.com/shadow/shadow/blob/main/src/main/host/syscall/handler/unistd.rs#L936

I think it quite makes sense to change it to `Linux` since we want to simulate Linux.

**Comment by sporksmith** [comment]
```
        let sysname = u8_to_i8_slice(&b"shadowsys"[..]);
        let release = u8_to_i8_slice(&b"shadowrelease"[..]);
        let version = u8_to_i8_slice(&b"shadowversion"[..]);
        let machine = u8_to_i8_slice(&b"shadowmachine"[..]);
```

`Linux` seems pretty reasonable for `sysname`. It's not as clear what we ought to provide for the other fields, though probably just some fairly recent example of "real world" values would be ok to hard-code.

I could see a case for making this configurable, maybe on a per-host basis, but that's probably overkill for now.

**Comment by robgjansen** [comment]
I can take this one. Per-host configurable over-rides sounds good, but for now I'll hard code to values returned in Debian 12 as suggested.
