### ISSUE TITLE
Build error in rust-unit-tests with rustc 1.82.0

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#3445]
There is an error building during the `rust-unit-tests` test, as follows:

```
./setup build -cgtj32
./setup test rust-unit-tests
```

For some reason `libremora.a` is not getting linked correctly, causing undefined references to `retransmit_tally_*`. Output is

```
Start testing: Nov 23 14:41 EST
----------------------------------------------------------
1/208 Testing: rust-unit-tests
1/208 Test: rust-unit-tests
Command: "/usr/bin/bash" "-c" "              SHADOW_VERSION="" RUSTFLAGS="-C force-frame-pointers=y" CFLAGS=" -std=gnu11 -O0 -ggdb -fno-omit-frame-pointer -Wreturn-type -Wswitch -DDEBUG" CXXFLAGS=" -std=c++11 -O0 -ggdb -fno-omit-frame-pointer -Wreturn-type -Wswitch -DDEBUG" CC="/usr/bin/cc" CXX="/usr/bin/c++"             cargo test                                       --manifest-path "/home/rjansen/dev/shadow/src"/Cargo.toml             --target-dir "/home/rjansen/dev/shadow/build/src/target"             --features ""             "
Directory: /home/rjansen/dev/shadow/build/src
"rust-unit-tests" start time: Nov 23 14:41 EST
Output:
```

...

```
= note: /usr/bin/ld: /home/rjansen/dev/shadow/build/src/target/debug/build/shadow-rs-8a085ae6b3bd174c/out/libshadow-c.a(134261f062bcde65-tcp.o): in function `_tcp_flush':
          /home/rjansen/dev/shadow/src/main/host/descriptor/tcp.c:1280: undefined reference to `retransmit_tally_num_lost_ranges'
          /usr/bin/ld: /home/rjansen/dev/shadow/src/main/host/descriptor/tcp.c:1284: undefined reference to `retransmit_tally_populate_lost_ranges'
          /usr/bin/ld: /home/rjansen/dev/shadow/src/main/host/descriptor/tcp.c:1298: undefined reference to `retransmit_tally_mark_retransmitted'
          /usr/bin/ld: /home/rjansen/dev/shadow/build/src/target/debug/build/shadow-rs-8a085ae6b3bd174c/out/libshadow-c.a(134261f062bcde65-tcp.o): in function `_tcp_runRetransmitTimerExpiredTask':
          /home/rjansen/dev/shadow/src/main/host/descriptor/tcp.c:1506: undefined reference to `retransmit_tally_clear_retransmitted'
          /usr/bin/ld: /home/rjansen/dev/shadow/src/main/host/descriptor/tcp.c:1508: undefined reference to `retransmit_tally_mark_lost'
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib)

error: could not compile `shadow-rs` (lib test) due to 1 previous error
<end of output>
Test time =  40.02 sec
----------------------------------------------------------
Test Failed.
"rust-unit-tests" end time: Nov 23 14:41 EST
"rust-unit-tests" time elapsed: 00:00:40
----------------------------------------------------------

End testing: Nov 23 14:41 EST
```

Full log file attached.
[LastTest.log](https://github.com/user-attachments/files/17882365/LastTest.log)

**Comment by sporksmith** [comment]
```
./setup build -cgtj32
```

What's `-cgtj32`?  It results in an error on my machine.

```
$ ./setup build -cgtj32
Traceback (most recent call last):
  File "/home/jnewsome/projects/shadow/./setup", line 334, in <module>
    main()
  File "/home/jnewsome/projects/shadow/./setup", line 164, in main
    r = args.func(args, remaining)
  File "/home/jnewsome/projects/shadow/./setup", line 191, in build
    if args.do_force_rebuild and os.path.exists(builddir): shutil.rmtree(builddir)
  File "/usr/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.10/shutil.py", line 658, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.10/shutil.py", line 658, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: '35'
```

```
./setup build
./setup test rust-unit-tests
```

seems to work as expected on my machine. Which OS and rust toolchain is this?

**Comment by robgjansen** [comment]
> What's -cgtj32?

```
$ ./setup build --help

  -c, --clean           Force a full rebuild of Shadow by removing the build cache directory. (default: False)
  -g, --debug           Build in extra memory checks and debugging symbols when running Shadow. Simulator performance will be  significantly reduced. (default: False)
  -t, --test            Build tests. (default: False)
  -j N, --jobs N        Number of jobs to run simultaneously during the build. (default: 64)
```

> It results in an error on my machine.

`-c` or `--clean` will attempt to remove the `./build` directory, but it looks that that is not succeeding for you because there is a file or directory in there which your user is not allowed to access.

> `./setup build`
> `./setup test rust-unit-tests`
> seems to work as expected on my machine.

My result does not change when I remove the `-cgtj32` flags.

> Which OS and rust toolchain is this?

```
$ uname -a
Linux hades1 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

$ rustc --version
rustc 1.82.0 (f6e511eec 2024-10-15)
```

My Debian 12 is fully updated with the latest packages from the debian package manager (apt).

The tests seem to be passing in #3446, so maybe there is an issue with my environment, but the error is nonsensical to me. All of the other tests are passing for me, just the `rust-unit-tests` are failing.

**Comment by robgjansen** [comment]
> So as a workaround you can probably use 1.81

Ahh ha! Thanks! Everything works as expected after downgrading to 1.81 with 
`rustup default 1.81.0 && ./setup build -cgtj32 && ./setup test`.

**Comment by stevenengler** [comment]
This might be https://github.com/rust-lang/rust/pull/128400:

> Removes a problematic hack that always passed the `--whole-archive` linker flag for tests, which may cause linker errors for code accidentally relying on it.

**Comment by sporksmith** [comment]
> This might be https://github.com/rust-lang/rust/pull/128400:

Huh; that *does* seem suspicious.

Unfortunately I tried to reproduce again just now and haven't been able to.

Looking at Rob's `LastTest.log` though, the link order looks correct. `retransmit_tally_clear_retransmitted` is defined in libremora, and it appears before libshadow-c in the link order as it should:

```
...
"-lremora" "-Wl,-Bdynamic" "-lstdc++" "-Wl,-Bstatic" "-lshadow-c"
...
```

Likewise remora is built before shadow-c in the build file, which I believe is what controls the link order: https://github.com/shadow/shadow/blob/2a026f2624bc705ae6ca5a482b2db2c439309500/src/main/build.rs#L433

I was thinking maybe it was somehow trying to do the link step before libremora is actually built, since we've run into such nondeterministic build errors before, but I don't think that should happen when both are built as part of the same crate. I also think the error would be different, stating that the library couldn't be found instead of that the symbol couldn't be found.

**Comment by sporksmith** [comment]
>  it appears before libshadow-c in the link order as it should:

Oh wait, no, that is the wrong order. I was thinking it makes sense to build the dependency before the dependee, but in the link order that's wrong.

I'll try reversing it.

**Comment by sporksmith** [comment]
> Unfortunately I tried to reproduce again just now and haven't been able to.

Ah, and I'd forgotten that it was the `setup test` step that generates the link error, not the `setup build` step.

Successfully reproduced again, fixed, and verified. Wills end out a PR shortly.

**Comment by sporksmith** [comment]
> Ahh ha! Thanks! Everything works as expected after downgrading to 1.81 with

Btw another option, that I do, is to keep a symbolic link from `rust-toolchain.toml` in my shadow checkout to stay in sync with the supported rust version.

```
ln -s ci/rust-toolchain-stable.toml rust-toolchain.toml
```
