### ISSUE TITLE
Shadow python plugin is incomplete

### ISSUE THREAD

**Issue by WladimirDelaCadena** [shadow/shadow#345]
I know this issue should be be en the shadow-plugin-extras but the issues section is deactivated ther . My problem is: by compiling, it does not find the file the 'python-interpreter.h'. And I can not find it in any place. Could you push it? Thanks

**Comment by robgjansen** [comment]
I don't have an answer, but maybe the author @javex does?

**Comment by Javex** [comment]
Tracking this on Javex/shadow-plugin-extras#9, feel free to close this here.

**Comment by robgjansen** [comment]
Thanks!
