### ISSUE TITLE
Tests failing on master and v1.12.0

### ISSUE THREAD

**Issue by haselhorst** [shadow/shadow#353]
I try to run shadow on a Ubuntu Linux machine

uname -a 
Linux ittlap-10 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

build is successful for both master and v1.12.0, but some tests fail and I am also not able to run the examples in recources/examples successfully.

failing tests for master:

The following tests FAILED:
         24 - file-shadow (Failed)
         25 - phold-shadow (SEGFAULT)
         26 - phold-threaded-shadow (SEGFAULT)
         37 - sockbuf (Failed)
Errors while running CTest
2017-10-11 17:01:40,756 [INFO] ctest -j1 returned 8
2017-10-11 17:01:40,756 [WARNING] Failed to pass all test cases!

failing tests for v1.12.0

The following tests FAILED:
          2 - dynlink-shadow (Failed)
         20 - bind-shadow (Failed)
         22 - epoll-shadow (Failed)
         24 - file-shadow (Failed)
         25 - phold-shadow (Failed)
         26 - phold-threaded-shadow (Failed)
         28 - poll-shadow (Failed)
         30 - pthreads-shadow (Failed)
         32 - random-shadow (Failed)
         36 - sleep-shadow (Failed)
         38 - sockbuf-shadow (Failed)
         40 - tcp-blocking-loopback-shadow (Failed)
         41 - tcp-blocking-lossless-shadow (Failed)
         42 - tcp-blocking-lossy-shadow (Failed)
         44 - tcp-nonblocking-poll-loopback-shadow (Failed)
         45 - tcp-nonblocking-poll-lossless-shadow (Failed)
         46 - tcp-nonblocking-poll-lossy-shadow (Failed)
         48 - tcp-nonblocking-epoll-loopback-shadow (Failed)
         49 - tcp-nonblocking-epoll-lossless-shadow (Failed)
         50 - tcp-nonblocking-epoll-lossy-shadow (Failed)
         52 - tcp-nonblocking-select-loopback-shadow (Failed)
         53 - tcp-nonblocking-select-lossless-shadow (Failed)
         54 - tcp-nonblocking-select-lossy-shadow (Failed)
         56 - tcp-iov-shadow (Failed)
         58 - timerfd-shadow (Failed)
Errors while running CTest
2017-10-11 17:12:25,308 [INFO] ctest -j1 returned 8
2017-10-11 17:12:25,308 [WARNING] Failed to pass all test cases!

output when running example on master: 
[shadow.log](https://github.com/shadow/shadow/files/1376112/shadow.log)

output when running example on v1.12.0
[shadow.log](https://github.com/shadow/shadow/files/1376135/shadow.log)

**Comment by haselhorst** [comment]
Thx for the fix! Most tests are passing now and the examples seem to run.
One test is still failing: 

98% tests passed, 1 tests failed out of 58

Total Test time (real) =  17.13 sec

The following tests FAILED:
         37 - sockbuf (Failed)
Errors while running CTest
2017-10-16 09:17:33,039 [INFO] ctest -j1 returned 8
2017-10-16 09:17:33,039 [WARNING] Failed to pass all test cases!

**Comment by robgjansen** [comment]
That test also failed for shadow/shadow-plugin-tor#39, but I'm not sure if the underlying problem is the same or not.
