### ISSUE TITLE
tgen test fails under Ubuntu 17.10

### ISSUE THREAD

**Issue by rpgdev** [shadow/shadow#366]
For some reason shadow is not working properly on ubuntu 17.10. I installed everything as instructed by the guide and it all seems to be running as expected (the ./setup test says it passed all the tests) but when I run the tgen test the transfers error out. Attached is the ./setup test output (100% passed) and the outputs from tgen. Not sure what can be the issue, this test runs perfectly under ubuntu 16.04.

[stdout-bulkclient1.tgen.1000.log](https://github.com/shadow/shadow/files/1483472/stdout-bulkclient1.tgen.1000.log)
[stdout-server1.tgen.1000 1.log](https://github.com/shadow/shadow/files/1483473/stdout-server1.tgen.1000.1.log)
[stdout-webclient1.tgen.1000.log](https://github.com/shadow/shadow/files/1483474/stdout-webclient1.tgen.1000.log)

I truncated the server log because it was huge.

**Comment by robgjansen** [comment]
Which version of Shadow are you using? Are you using the version from git or did you download it from the website? Can you post the git commit hash if applicable?

Ubuntu 17.10 uses a newer version of glibc and the version from git master has some fixes.

**Comment by jtracey** [comment]
I'm getting the same result on the latest commit (all tests pass, minimal tgen example doesn't transfer anything). Looks like read() is failing for some reason.

**Comment by robgjansen** [comment]
Oh, crap, did my latest commit (4eb6066fa0b7cb0f802c5408349de43c69d058f0 ) break things?

**Comment by rpgdev** [comment]
@robgjansen I'm using the version from git: Shadow v1.12.0-31-g370b821f 2017-11-16 (built 2017-11-16) running GLib v2.54.1 and IGraph v0.7.1

**Comment by jtracey** [comment]
@robgjansen I'm not at home any more so I can't test, but my guess is that I didn't check the output of the tgen example when testing and it slipped through, and that it never worked. It is possible though, I can check either late tonight or tomorrow.

**Comment by robgjansen** [comment]
I did some testing:

OS version:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

Shadow version:
```
$ shadow --version
Shadow v1.12.0-33-g4eb6066 2017-11-17 (built 2017-11-17) running GLib v2.48.2 and IGraph v0.7.1
```

libc:
```
$ ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu9) 2.23
```

TGen example:
```
$ cd resource/examples
$ shadow shadow.config.xml > shadow.log
$ $ for d in shadow.data/hosts/*client*; do grep "transfer-complete" ${d}/* ; done | tee clients.log | wc -l
1000
```

But I guess we already knew this works on 16.04 from the OP. I don't have a 17.10 VM handy at the moment, so @jtracey I'll let you take a look at this next. Let me know if you think it is not an elf-loader issue and I can take another look.

**Comment by robgjansen** [comment]
To be clear, @rpgdev tested at `Shadow v1.12.0-31-g370b821f`, which is two commits before my latest commit `Shadow v1.12.0-33-g4eb6066`. I'm not sure which commit caused it, but based on this evidence I don't think it was 4eb6066.

Also, it is troubling that some important aspect of the tgen example is not being exercised in a test case. We should write a simple test once we find the issue.

**Comment by robgjansen** [comment]
After some poking around by @jtracey, it seems like this bug may not be in the elf-loader code. This will require some debugging with TGen and tracing in Shadow.

**Comment by robgjansen** [comment]
This is not a bug in elf loader, but in Tgen when parsing the transfer size. There is a bug in converting KiB, MiB, GiB etc to bytes using `pow()` that started in Ubuntu 17.10. Changing to `powl()` seems to fix things. Commit coming shortly.

**Comment by jtracey** [comment]
`pow()` is a libc function, I bet this is elf-loader. I'll take a closer look. Worst case I'll file a bug report upstream.
