### ISSUE TITLE
A TLS error prevents Tor to bootstrap

### ISSUE THREAD

**Issue by frochet** [shadow/shadow#405]
Hello,

Tried master branch on shadow and shadow-plugin-tor, as well as tagged V1.12 for both. I launched the shadowtor-minimal from /resource and observed the following within Tor's logs:

Jan 01 00:26:00.000 [info] connection_or_note_state_when_broken(): Connection died in state 'handshaking (TLS) with SSL state SSLv2/v3 read server hello A in HANDSHAKE'

From the logs, it looks like there's a deadlock somewhere during TLS handskake. Could that be possible? Version V1.11 works just fine, but not with recent Tor version, though.

**Comment by robgjansen** [comment]
Could you please list the version of Tor that you are using, ideally including the commit hash? Thanks!

**Comment by frochet** [comment]
I did try 4 versions, same issue for each:
- A fork from release-0.3.2 
- The default version that the build command downloads if no --tor-prefix provided (tor-0.3.2.9 I think)
- The tag tor-0.3.0.9
- The tag tor-0.2.6.7

Same problem each time.

**Comment by frochet** [comment]
Just noticed that ./setup test gives sometimes an error:

98% tests passed, 1 tests failed out of 64

Total Test time (real) =   8.84 sec

The following tests FAILED:
	 43 - sockbuf (Failed)

Btw, thanks a lot for you assistance.

**Comment by jtracey** [comment]
That tests sometimes fails on my machine too, I can't remember the details but I once looked into it a bit and it's a false positive.

**Comment by thiennamdinh** [comment]
Hi,

I can confirm that I am having the same issues. I tested on earlier commits and found this to be the most recent working setup:

shadow: b03518c5f05644a524cd5c9013195c9b9cd38383 (Feb 1st)
shadow-plugin-tor: 7d8bc5c0fa12c2ac15744da31b9a4c4fb527d87f (HEAD)
tor: 0.3.2.9 (default in setup script)
experiment: shadow-minimal

The very next shadow commit for valgrind elf-loader leads to the TLS errors. I'm not familiar enough with this stuff yet to know what happened exactly, but hope this helps!

**Comment by jtracey** [comment]
@thiennamdinh thanks!

**Comment by frochet** [comment]
It works :).  Thx @jtracey ,  @thiennamdinh , @robgjansen
