### ISSUE TITLE
Tests failing on master and v1.12.0 - Ubuntu 16.04

### ISSUE THREAD

**Issue by thiennamdinh** [shadow/shadow#406]
Hello,

I'm trying to run shadow on an ubuntu 16.04 machine and am getting what looks to be similar errors as #353, which I understand was fixed for ubuntu 17.04. Is it possible that the fix did not apply for previous versions? Thanks!

-uname -a

4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x8
6_64 GNU/Linux   

commit: 3ba48737556ee938f63c409b767b069cf460b0bb

./setup test

73% tests passed, 17 tests failed out of 64

Total Test time (real) =  14.98 sec

The following tests FAILED:
          2 - dynlink-shadow (SEGFAULT)
         28 - epoll-writeable-shadow (SEGFAULT)
         31 - phold-shadow (SEGFAULT)
         32 - phold-threaded-shadow (SEGFAULT)
         43 - sockbuf (Failed)
         44 - sockbuf-shadow (SEGFAULT)
         46 - tcp-blocking-loopback-shadow (SEGFAULT)
         47 - tcp-blocking-lossless-shadow (SEGFAULT)
         48 - tcp-blocking-lossy-shadow (SEGFAULT)
         50 - tcp-nonblocking-poll-loopback-shadow (SEGFAULT)
         51 - tcp-nonblocking-poll-lossless-shadow (SEGFAULT)
         54 - tcp-nonblocking-epoll-loopback-shadow (SEGFAULT)
         55 - tcp-nonblocking-epoll-lossless-shadow (SEGFAULT)
         56 - tcp-nonblocking-epoll-lossy-shadow (SEGFAULT)
         58 - tcp-nonblocking-select-loopback-shadow (SEGFAULT)
         59 - tcp-nonblocking-select-lossless-shadow (SEGFAULT)
         60 - tcp-nonblocking-select-lossy-shadow (SEGFAULT)
Errors while running CTest
2018-02-23 14:12:14,217 [INFO] ctest -j4 returned 8
2018-02-23 14:12:14,217 [WARNING] Failed to pass all test cases!

- should also note that the number of failed tests is not deterministic so this may not be the full list

- output for shadowtor-minimal experiment
[shadow.log](https://github.com/shadow/shadow/files/1753029/shadow.log)

**Comment by jtracey** [comment]
Ubuntu 16.04 should work, it's what I use for my main development machine. Can you load one of these in gdb (e.g. the shadowtor-minimal), run and get a segfault, run `p vdl_linkmap_abi_update()` in the gdb shell, and provide the backtrace?

**Comment by thiennamdinh** [comment]
Sure, here it is:

...

Thread 10 "shadow" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd07c7700 (LWP 32320)]
0x00007fffd7a60162 in ?? ()
(gdb) p vdl_linkmap_abi_update()
[New Thread 0x7fffcff76700 (LWP 32322)]
[New Thread 0x7fffcf725700 (LWP 32323)]
[New Thread 0x7fffceed4700 (LWP 32324)]

Thread 11 "shadow" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcff76700 (LWP 32322)]
0x00007fffd7a60162 in __GI___ctype_init () at ctype-info.c:31
31      ctype-info.c: No such file or directory.
The program received a signal in another thread while
making a function call from GDB.
Evaluation of the expression containing the function
(vdl_linkmap_abi_update) will be abandoned.
When the function is done executing, GDB will silently stop.
(gdb) bt
#0  0x00007fffd7a60162 in __GI___ctype_init () at ctype-info.c:31
#1  0x00007fffd781c62b in start_thread (arg=0x7fffcff76700) at pthread_create.c:268
#2  0x00007fffd7b3941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb)

**Comment by thiennamdinh** [comment]
I did, and unfortunately it didn't help. Thanks anyway; I'll let you guys know if I ever end up resolving this.

**Comment by robgjansen** [comment]
@thiennamdinh did you make progress on this issue? Is it legitimate? What is our path forward on this issue? Thanks!

**Comment by thiennamdinh** [comment]
Hi, unfortunately not :( I've since moved onto another machine (also ubuntu 16.04) that works with your latest TLS error fix.

All I've been able to do is confirm that it works with v1.11 versions of things, so once I have some free time I can perhaps try to hunt down the incremental commit where it stops working.
