### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [shadow/shadow#411]
I would like to point out that identifiers like “[`_Slave`](https://github.com/shadow/shadow/blob/5e490156e5fbb8a4b3fad95606740528f13cb05e/src/main/core/shd-slave.h#L25 "Update candidate")” and “[`_WorkerRunData`](https://github.com/shadow/shadow/blob/069e715a827d51a3251ab082e28beae5b36983ff/src/main/core/shd-worker.h#L12 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jtracey** [comment]
Yeah, it's actually not valid C either, strictly speaking: https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html
I've never pointed out before because it's really a nit, since it will probably always work, but it technically should be changed.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by pastly** [comment]
If you can run an automated tool to find these things, perhaps you can run an automated tool that fixes them too.

**Comment by elfring** [comment]
Would you like to [apply any semantic patches](http://coccinelle.lip6.fr/ "Using semantic patch language?") with which [identifiers can be adjusted](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?

**Comment by robgjansen** [comment]
We are aware of this issue, and plan to make adjustments as we clean up the code in future releases. Thanks!

**Comment by stevenengler** [comment]
Closing since we're moving from C to rust.
