### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [shadow/shadow#412]
[An extra null pointer check is not needed in functions](https://developer.gnome.org/glib/stable/glib-Memory-Allocation.html#g-free "Do I need to check for null before g_free(p)?") like the following.
- [bytechunk_free](https://github.com/shadow/shadow/blob/9fce6e321e05a15db85ed20a546430fa21677efb/src/main/utility/shd-byte-queue.c#L43 "bytechunk_free function")
- [_logrecord_free](https://github.com/shadow/shadow/blob/9fce6e321e05a15db85ed20a546430fa21677efb/src/main/core/logger/shd-log-record.c#L45 "_logrecord_free function")

How do you think about to apply a corresponding update suggestion which will eventually be generated by [the software "Coccinelle"](http://coccinelle.lip6.fr/)?

```
@Deletion@
expression x;
@@
-if (\(x != 0 \| x != NULL\))
    g_free(x);
```

**Comment by pastly** [comment]
If you have the time to open issues for trivial-to-fix non-issues, please also find the time to submit pull requests to solve them.

**Comment by elfring** [comment]
I find it unlikely at the moment that I am going to contribute pull requests for this software because I do not like specific properties of [the corresponding licence](https://github.com/shadow/shadow/blob/70add41110cc98f03b32a7eb16106c06eff34a6c/LICENSE "Software licence").

**Comment by robgjansen** [comment]
Thanks for pointing this out. We plan to remove glib as a dependency soon, in which case the NULL checks may become useful. We'll consider this as we clean up our code in future releases.

**Comment by elfring** [comment]
I suggest to consider additional development tools and software design approaches so that more unnecessary checks can be avoided.

**Comment by stevenengler** [comment]
Closing since we're moving away from C.
