### ISSUE TITLE
problems with OpenBLAS threading

### ISSUE THREAD

**Issue by jtracey** [shadow/shadow#414]
When testing Shadow on Ubuntu 18.04, some problems arose.

1. The LD_STATIC_TLS_EXTRA environment variable doesn't seem to be correctly calculated anymore. I haven't investigated too closely yet since it's probably a simple fix, and might be related to the second problem.
2. There appears to be a new dependency on the library OpenBLAS, I believe through igraph. OpenBLAS uses multiple POSIX threads by default, which causes issues with Shadow, because its threading ends up getting caught by the interposer when it shouldn't. Luckily, OpenBLAS anticipated problems such as these and has a few solutions:
https://github.com/xianyi/OpenBLAS/wiki/faq#multi-threaded
I've tested the environment variable, and it works. So it's just a question of whether we prefer setting the environment variable, or doing a conditional compile with the function call. I'm guessing we want the former, but I thought I'd check first.

**Comment by jtracey** [comment]
confirmed that the first issue goes away when setting OPENBLAS_NUM_THREADS=1 as well, OpenBLAS must just be using static TLS we weren't measuring

**Comment by jtracey** [comment]
Ah, so there is another problem with this as well: tgen also links against OpenBLAS, so when it gets dlmopened from the static TLS-calculating code, it can cause problems. So we need to set up the environment variable before we get there, which would imply we need to restart shadow twice, which is unfortunate... Any other ideas?

**Comment by jtracey** [comment]
It looks like OpenBLAS is only used as a dependency of libigraph in Ubuntu (and presumably anything else `apt`-based) if the libopenblas-base package was installed before libigraph was (any of libatlas3-base, libblas3, or libopenblas-base can provide libblas.so.3, with the default dependency being libblas3). I think the best workaround for now is to just install the libblas3 package and maybe remove libopenblas-base. Although it would be nice to get this fixed at some point, I don't think I can do it right now, since OpenBLAS appears to be doing some weird things with pthreads, even in single threaded mode, which causes problems in other more normal projects -- let alone with elf-loader.

**Comment by robgjansen** [comment]
Thanks for documenting this issue and the workaround, @jtracey. (If it was as easy as setting `OPENBLAS_NUM_THREADS=1` and then restarting Shadow, we could do it; but it seems that you found issues even here so I guess we'll put this off for the time being.)
