### ISSUE TITLE
python 2 deprecation

### ISSUE THREAD

**Issue by jtracey** [shadow/shadow#422]
Many components of shadow (the setup script, the parsing tools, and some of the build scripts for elf-loader) rely on python 2. RHEL has announced that they're deprecating python 2 in this release, which in practice typically means dropping support in the next release.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.5_release_notes/chap-red_hat_enterprise_linux-7.5_release_notes-deprecated_functionality

This is a result of python 2 itself being EOL'd in 2020. It's only a matter of time before other distros follow suit, so we should start the process of moving these scripts over to python 3 now.

**Comment by jtracey** [comment]
related: #9 
That fixed most of the issues with the main setup script (it still needs to handle when no args are passed), but didn't address the other scripts.

**Comment by robgjansen** [comment]
Thanks, didn't know python was EOL'd. Guess it's finally time to move on :)

**Comment by ildella** [comment]
Compared to the current [instructions ](https://github.com/shadow/shadow/wiki/1.1-Shadow) I was able to build and install from master On Ubuntu 19.10 with only:

```
sudo apt install gcc g++ libglib2.0-0 libglib2.0-dev libigraph0v5 libigraph0-dev cmake make xz-utils
sudo apt install python3-pyelftools
```

 All the other listed python deps seem to be useless
```
$ sudo apt remove python-matplotlib python-numpy python-scipy python-networkx python-lxml
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'python-lxml' is not installed, so not removed
Package 'python-matplotlib' is not installed, so not removed
Package 'python-networkx' is not installed, so not removed
Package 'python-numpy' is not installed, so not removed
Package 'python-scipy' is not installed, so not removed
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```

**Comment by jtracey** [comment]
Those packages are necessary for other scripts, such as the tools used to create new networks/experiments, or to analyze the generated data as well as plot it.

**Comment by robgjansen** [comment]
I think #780 added the last migration of the elf-loader scripts. So, I think this can be closed now, unless we first want to remove the python 2.7 linter in the CI? @sporksmith?

**Comment by sporksmith** [comment]
Well, we probably want to *start* linting and testing with python 3 in the CI.

If we want to keep python 2 working as well we could create another dimension in the CI matrix so that it validates 2 and 3. I suppose that probably isn't worth the maintenance burden though since 2 is officially EOL.

**Comment by sporksmith** [comment]
I see we currently are [linting](https://github.com/shadow/shadow/blob/master/.github/workflows/lint_python.yml) both versions. Yeah, I'm fine with dropping 2 support.

We should probably tweak the test script to force python 3

**Comment by florian-vuillemot** [comment]
Let me know if you decide to remove the python2 compatibility. I can do it and finish the migration.

**Comment by jtracey** [comment]
Just to point out, the only thing stopping the linter from succeeding in `src/external/` is this line:
https://github.com/shadow/shadow/blob/c0cd2d4066f579076abf27d6981d9033cfc097ed/src/external/elf-loader/test/junit_xml_output/__init__.py#L14
which could be removed if python2 support is dropped.

**Comment by robgjansen** [comment]
The list of things that are needed to complete the removal of python 2:
- Update the `to_str` func as shown in https://github.com/shadow/shadow/issues/422#issuecomment-621228607
- Stop running the linter on python 2 [here](https://github.com/shadow/shadow/blob/c0cd2d4066f579076abf27d6981d9033cfc097ed/.github/workflows/lint_python.yml#L19)
- Remove the `src/external` inlcude [here[(https://github.com/shadow/shadow/blob/c0cd2d4066f579076abf27d6981d9033cfc097ed/.github/workflows/lint_python.yml#L26)
- Force python3 in the test script

For the last one, I'm not positive about all of the places that need updates.

**Comment by sporksmith** [comment]
> Force python3 in the test script

AFAICT the best practice for making a script python3-only is to change the shebang line to `#!/usr/bin/env python3`

**Comment by jtracey** [comment]
Another step I would add to that list: replace all references to python 2 in the documentation with python 3 (e.g., switching from the `python-pyelftools` package to the `python3-pyelftools`). Actually, that should probably be done first, since full python 3 support is already there, and python 2 support will soon be gone.

**Comment by stevenengler** [comment]
Generally things should be using Python 3 now. The setup guide uses Python 3 rather than Python 2, but I haven't gone through the rest of the documentation to see what else uses Python 2. The other repositories like shadow-plugin-tor also need to be updated to use Python 3 in any documentation or scripts.

**Comment by jtracey** [comment]
I think this issue can be closed now?
