### ISSUE TITLE
Build error in shd-topology.c

### ISSUE THREAD

**Issue by Silur** [shadow/shadow#426]
```
/home/shadow/shadow/src/main/routing/shd-topology.c: In function '_topology_igraphAttributeTypeToString':
/home/shadow/shadow/src/main/routing/shd-topology.c:151:23: error: 'IGRAPH_ATTRIBUTE_BOOLEAN' undeclared (first use in this function)
     } else if(type == IGRAPH_ATTRIBUTE_BOOLEAN) {
```
uname -a output:
```
Linux fb3708ae7d9e 4.17.12-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 3 07:16:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
Seems like the igraph lib had some updates you didn't cover? All other IGRAPH_ATTRIBUTE consts are visible

**Comment by robgjansen** [comment]
Can you please find and post the version of the igraph library that you are using? Usually this is printed in the output of `shadow --version`.

**Comment by robgjansen** [comment]
I wonder if you are using an older version of igraph that does not define the `IGRAPH_ATTRIBUTE_BOOLEAN` constant?

**Comment by robgjansen** [comment]
Please re-open if you are still experiencing this issue.

**Comment by nikitaborisov** [comment]
I just ran into the same build issue. Here's my `libigraph` version:

`nikita@tick4:~/shadow$ dpkg-query -l libigraph0 libigraph0-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                      Version           Architecture      Description
+++-=========================-=================-=================-========================================================
ii  libigraph0                0.6.5-5           amd64             library for creating and manipulating graphs
ii  libigraph0-dev            0.6.5-5           amd64             library for creating and manipulating graphs - developme`

**Comment by nikitaborisov** [comment]
(This is on ubuntu 14.04.)

**Comment by nikitaborisov** [comment]
I was able to build things by building a local copy of libigraph 0.8.0, but I ran into issues figuring out how to get cmake to use my version and not the system one. This is what I ended up with, but I assume there's a better way:
```nikita@tick4:~/shadow$ git diff setup
diff --git a/setup b/setup
index 28d7891..88bec98 100755
--- a/setup
+++ b/setup
@@ -155,6 +155,8 @@ def build(args):
     if args.disable_tgen: cmake_cmd += " -DBUILD_TGEN=OFF"
     if args.do_valgrind: cmake_cmd += " -DLOADER_VALGRIND=ON"

+    cmake_cmd += " -DIGRAPH_INCLUDES=/home/nikita/include/igraph -DIGRAPH_LIBRARIES=/home/nikita/lib/libigraph.so"
+
     # we will run from build directory
     calledDirectory = os.getcwd()
```

**Comment by nikitaborisov** [comment]
OK I see, never mind; installing libigraph in ~/.shadow worked.
