### ISSUE TITLE
Subject: Re: [shadow-support] Shadow-Tor sleep() function


### ISSUE THREAD

**Issue by shadow-org-bot** [shadow/shadow#501]
From: Lei Yang <leiyang198710 -at- gmail.com>
To: Rob Jansen <rob.g.jansen -at- nrl.navy.mil>
Cc: "shadow-support -at- cs.umn.edu" <shadow-support -at- cs.umn.edu>
Subject: Re: [shadow-support] Shadow-Tor sleep() function
Date: Wed, 17 Jun 2015 20:55:50 -0500

Thank you, Rob!

I did as you instructed. It works!

Best,
Lei

On Wed, Jun 17, 2015 at 4:26 PM, Rob Jansen <rob.g.jansen -at- nrl.navy.mil>
wrote:

> The issue is that your sleep() call is a blocking call which will
> currently not be handled correctly by Shadow. As you noticed, sleep will
> cause the *shadow* process to sleep, instead of inserting delays on your
> *virtual host* process.
>
> You could get the desired result by saving away the cells in a queue,
> and then creating a new function 'my_cell_processor' that will continue
> where you left off by processing the queue of cells that you created.
> Then, you can call 'my_cell_processor' from the
> 'second_elapsed_callback' function in Tor (which gets called every
> second). If you want it to be called more or less often than once per
> second, you could create your own function using Shadow's api, as shown
> here:
>
>
> https://github.com/shadow/shadow-plugin-tor/blob/master/src/tor/shadowtor.c#L20
>
> I wish this was easier, but I don't think it will be until this issue is
> implemented:
> https://github.com/shadow/shadow/issues/236
>
> Hope that helps,
> Rob
>
> On 06/17/2015 03:55 PM, Lei Yang wrote:
> > Hi Rob,
> >
> > I want to use the sleep() function in the Tor codes, but it looks like
> > the sleep() doesn't work to the Tor, while the Shadow process sleeps for
> > several seconds. Then, I tried to write endless loop which stops until
> > the specific time is elapsed, but it still doesn't work. It seems that
> > the loop doesn't cost time. Could you please give me some hints that how
> > Tor cells in the Shadow simulator could be delayed for several seconds?
> >
> > Thank you very much!
> >
> > Best,
> > Lei
> >
> >
> > _______________________________________________
> > shadow-support mailing list
> > shadow-support -at- cs.umn.edu
> > https://wwws.cs.umn.edu/mm-cs/listinfo/shadow-support
> >
>

**Comment by abuishgair** [comment]
Hi,

I was working on solving the same issue, You have suggested to create a similar  function  to second_elapsed_callback using Shadow's api, as shown in the link:
https://github.com/shadow/shadow-plugin-tor/blob/master/src/tor/shadowtor.c#L20
The link is not working now, could you please share the current link ?

Thanks,

**Comment by robgjansen** [comment]
(It is a bit unclear which issue you are talking about. I assume you are having problems with `sleep()`. If not, please explain your problem in more details.)

The link no longer exists because the Tor plugin no longer has to handle callback functions or `sleep()` in a special way. That allowed us to eliminate most code on the Tor plugin side of things, and so `shadowtor.c` no longer exists in the repo.

If you are using the latest version of Shadow, then Shadow does now support `sleep()` calls. In other words, you don't have to worry that `sleep()` will block and stall your Shadow simulation, it should just work as you expect it would.
