### ISSUE TITLE
Missing debug package

### ISSUE THREAD

**Issue by lzmartinico** [shadow/shadow#665]
I can't compile shadow in fedora-based distribution, either natively or through a Valgrind VM, because of an issue in the elf-loader library. It seems like the instructions to install the debug symbols for glibc are outdated, because the first step of compiling elf-loader (make vdl-config.h) fails with a CouldNotFindFile exception for the debug symbols

**Comment by jtracey** [comment]
What fedora-based distro are you using specifically (name and version)?

**Comment by lzmartinico** [comment]
I tried Fedora 28 and Scientific Linux 7.5 (based on RHEL 7.5)

**Comment by jtracey** [comment]
It looks like Fedora (& co) have deprecated yum in favor of dnf. Try:
``sudo dnf -y debuginfo-install glibc``

**Comment by lzmartinico** [comment]
I tried spinning up a new vagrant box with your addition and it worked, thanks! However, there's another bug in the wiki boostrap scrip: you should `mkdir /vagrant/shadow` before you can cd into it!

**Comment by robgjansen** [comment]
> However, there's another bug in the wiki boostrap scrip: you should `mkdir /vagrant/shadow` before you can cd into it!

I don't understand the problem. Here is the relevant part of the bootstrap.sh script:

```
cd /vagrant
git clone https://github.com/shadow/shadow.git
...
cd /vagrant/shadow
```

As you can see, the git clone will create the shadow directory. Creating an empty directory and changing into it in order to set up shadow is guaranteed not to work.

**Comment by lzmartinico** [comment]
Ah yes, sorry I should have said that the script should create the `/vagrant` directory before cloning the repository. I don't know if it depends form the source image (generic/fedora28) or from the vagrant version (2.1.2), but that directory does not exist for me

**Comment by robgjansen** [comment]
Ahh, that makes sense! I just updated the wiki page to run `mkdir -p /vagrant` before `cd /vagrant`. Thanks!!

**Comment by lzmartinico** [comment]
Great, thank you! I would also add the line installing glibc debugging symbols or at least a comment about it for future reference
