### ISSUE TITLE
Shadow determinism is broken

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#666]
Running the same Shadow experiment twice results in non-deterministic behavior; so far I have observed the following:

- [x] hosts may get assigned different IP addresses
- [x] tgen uses `getpid` and logs Shadow's PID instead of the virtual process PID
- [x] packet events are executed out of order
- [x] gettid using `syscall(SYS_gettid, ...)` should be implemented
- [x] futexes are woken in a non-deterministic order
- [x] descriptors are notified in a non-deterministic order
- [x] ~~non-deterministic behavior when retransmitting packets~~ - no evidence in #2109

**Comment by robgjansen** [comment]
I still need to verify that Tor experiments are deterministic with these changes.

**Comment by RWails** [comment]
I'm able to reproduce non-deterministic results with the following experiment:

[exp.zip](https://github.com/shadow/shadow/files/2728395/exp.zip)

Experiment has two clients who write, one server who reads, all using non-blocking, epoll-managed I/O. Each host periodically logs how much data they've transmitted and corresponding timestamps.

Build the plugin using make.bash and run two instances using the run script.  I am able to reliably produce plugin outputs that differ.

**Comment by robgjansen** [comment]
I updated @RWails test case and here I attach a new version for future reference.
[determinism_test.zip](https://github.com/shadow/shadow/files/2765780/determinism_test.zip)

**Comment by robgjansen** [comment]
After some fixes in #1460, I'm still seeing non-deterministic behavior in the Tor minimal example.

Here is the latest way I've been checking:

```bash
# It's best to build shadow in release mode, but still enable trace logging at runtime.
# That will ensure that the experiment runs more quickly but we still get the desired
# packet-level log lines.
./setup build -ctj6

cd src/test/tor/minimal
chmod 700 shadow.data.template/hosts/hiddenserver/hs

shadow -d a -e shadow.data.template -l trace tor-minimal.yaml | grep "packet_add" > shadow.log
mv shadow.log a/.

shadow -d b -e shadow.data.template -l trace tor-minimal.yaml | grep "packet_add" > shadow.log
mv shadow.log b/.

for d in a/hosts b/hosts
do
    cd ${d}
    for name in *
    do
        cat ../shadow.log | grep "${name}:" | grep "packet_add" | cut -d' ' -f3- > ${name}.log
    done
    cd -
done

for p in a/hosts/*log
do
    host_packet_log=`basename ${p}`
    diff --brief a/hosts/${host_packet_log} b/hosts/${host_packet_log}
done
```

**Comment by sporksmith** [comment]
#1515 should help. Prior to that rdtsc was only emulated in ptrace and hybrid modes, and measured the cpu frequency empirically, so wasn't deterministic.

(libopenssl uses rdtsc as a low-entropy source of randomness)

**Comment by stevenengler** [comment]
Added a list entry for futexes. For example in `futex_wake()`, listeners are iterated in order of the `futex->listeners` hash table keys.

From two runs of the tor minimal test:

```
00:04:02.050 [tid 1000] read(14, <pointer>, 5) = -11 (EAGAIN: Try again)
00:04:02.050 [tid 1000] futex(...) = 1
---
< 00:02:53.050 [tid 1002] futex(...) = 0
< 00:02:53.050 [tid 1002] futex(...) = 0
< 00:02:53.050 [tid 1002] getrandom(<pointer>, 32, 0) = 32
< 00:02:53.050 [tid 1002] write(10, <pointer>, 8) = 8
---
> 00:02:53.050 [tid 1001] futex(...) = 0
> 00:02:53.050 [tid 1001] futex(...) = 0
> 00:02:53.050 [tid 1001] getrandom(<pointer>, 32, 0) = 32
> 00:02:53.050 [tid 1001] write(10, <pointer>, 8) = 8
---
00:04:02.050 [tid 1000] epoll_wait(...) = 1
00:04:02.050 [tid 1000] read(10, <pointer>, 8) = 8
```

**Comment by stevenengler** [comment]
Added a list entry for descriptor status listeners. For example in `_descriptor_handleStatusChange()`, listening descriptors are notified in order of the `futex->listeners` hash table keys.

**Comment by robgjansen** [comment]
From discussion: fix the hash table iterators using a simple approach: have a per-host object id counter and add a new object id to the futex and listener objects. Then sort the hash table items by the object id and iterate in order.

Later, when we rewrite in rust, we can consider using a ring-buffer rather than a list to make sure the same objects that are always first in the list don't always get prioritized and starve the objects that are last in the list.

**Comment by robgjansen** [comment]
Based on results in #2109, we're no longer seeing evidence of "non-deterministic behavior when retransmitting packets", so I'm crossing out that item and closing this issue. Please open new issues if additional non-deterministic behaviors are discovered.
