### ISSUE TITLE
Please ensure 'tor' and 'tor-gencert' are in your 'PATH'

### ISSUE THREAD

**Issue by Stefanoga** [shadow/shadow#680]
Hi, I have a problem with the generation of a new Tor Network (procedure described in chapter "Generating a new Tor Network", https://github.com/shadow/shadow-plugin-tor/wiki). I followed all procedure of "Prepare Alexa website data", "Prepare Tor metrics data" and "Start generating!" but, after the last command (python ~/shadow-plugin-tor/tools/generate.py --nauths 1 --nrelays 20 --nclients 200 --nservers 20 --fweb 0.90 --fbulk 0.10 --nperf50k 10 --nperf1m 10 --nperf5m 10 ../alexa-top-1000-ips.csv ../2017-01-31-23-00-00-consensus ../server-descriptors-2017-01/ ../extra-infos-2017-01/ ../userstats-relay-country.csv), program notify error "Please ensure 'tor' and 'tor-gencert' are in your 'PATH'". I have installed shadow and shadow-plugin-tor and these files are in my path and with previous examples i had not problems. I attach the screen of my terminal after mistake. I hope that someone could help me
![5b536f7a-2f1a-46e1-8d27-61abf7cee8ef](https://user-images.githubusercontent.com/23016213/53751197-0faffe80-3eac-11e9-87e9-8d473224c081.jpg)

**Comment by robgjansen** [comment]
If you are trying to use Tor 0.3.5 or later, then Tor changed the location of the tor binary. The wiki was out of date and did not reflect this change. I guess you are using a later Tor version.

I just updated the wiki. Try doing this:
```
export PATH=${PATH}:~/shadow-plugin-tor/build/tor/src/or:~/shadow-plugin-tor/build/tor/src/app:~/shadow-plugin-tor/build/tor/src/tools
```

And then please post the output of the following 3 commands:
```
echo $PATH
which tor
which tor-gencert
```

Let me know if that worked.

**Comment by Stefanoga** [comment]
Hi! I have used the command that you wrote and moved one of the consensus file in the main directory: now I can generate Tor Network without problem. I attach the screenshot of the output of the other 3 commands line.
I have another question: I noticed that, when I close and reopen the terminal, the problem "Please ensure 'tor' and 'tor-gencert' are in your 'PATH'" still persist; I need to reinsert the command
`export PATH=${PATH}:~/shadow-plugin-tor/build/tor/src/or:~/shadow-plugin-tor/build/tor/src/app:~/shadow-plugin-tor/build/tor/src/tools`
each time: it is normal or I must change something?
Thanks for your help
![7bd44539-25dc-4e7f-aa10-14c3528a4efb](https://user-images.githubusercontent.com/23016213/53817123-19e20380-3f65-11e9-85ab-1c7e3d8e090e.jpg)

**Comment by robgjansen** [comment]
> I need to reinsert the command
export PATH=${PATH}:~/shadow-plugin-tor/build/tor/src/or:~/shadow-plugin-tor/build/tor/src/app:~/shadow-plugin-tor/build/tor/src/tools
each time: it is normal or I must change something?

This is normal. This is how the $PATH variable works in Linux. If you want it to always be in your path, you can set it in your `~/.bashrc` or `~/.profile` files. See here:
https://stackoverflow.com/questions/14637979/how-to-permanently-set-path-on-linux-unix
