### ISSUE TITLE
I am a newcomer to shadow, the following error occurred during Centos and Ubuntu installation.

### ISSUE THREAD

**Issue by littlesyc** [shadow/shadow#681]
[  0%] Building C object src/external/elf-loader/CMakeFiles/display-relocs.dir/display-relocs.c.o
[  1%] Linking C executable display-relocs
[  1%] Built target display-relocs
Scanning dependencies of target elfedit
[  2%] Building C object src/external/elf-loader/CMakeFiles/elfedit.dir/elfedit.c.o
[  2%] Linking C executable elfedit
[  2%] Built target elfedit
Scanning dependencies of target vdlconfig
[  3%] Generating vdl-config.h
src/external/elf-loader/CMakeFiles/vdlconfig.dir/build.make:60: recipe for target 'src/external/elf-loader/vdl-config.h' failed
make[2]: *** [src/external/elf-loader/vdl-config.h] Error 1
make[2]: *** Deleting file 'src/external/elf-loader/vdl-config.h'
CMakeFiles/Makefile2:788: recipe for target 'src/external/elf-loader/CMakeFiles/vdlconfig.dir/all' failed
make[1]: *** [src/external/elf-loader/CMakeFiles/vdlconfig.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
2019-03-05 20:44:52,286 [ERROR] Non-zero return code from make.

**Comment by robgjansen** [comment]
Hi, I wonder if you have the same error as in #670?

1. What operating system do you intend to use? Post the output of `uname -a` and `lsb_release -d`?
1. Did you do `sudo apt-get install libc-dbg`? Please also do `sudo apt-get -y install elfutils`.
1. Can you post the output of `python shadow/src/external/elf-loader/extract-system-config.py`?
1. Finally, try again with `LANGUAGE=C ./setup build -c -t && ./setup install` and let us know if that worked.

**Comment by littlesyc** [comment]
yes,It's worked.Thank you vey much
