### ISSUE TITLE
Error message while using Shadow-Tor container on Mac

### ISSUE THREAD

**Issue by kobiebendalak** [shadow/shadow#685]
I am getting the following error "shadow: symbol lookup error: /home/shadow/.shadow/plugins/libshadow-plugin-tor.so: undefined symbol: shadowtorpreload_init" when I try to initiate the most basic example of Tor on top of Shadow, as described here - https://github.com/shadow/shadow-plugin-tor/wiki

I am using the container version of Shadow on top of a Mac laptop.

Also, the output of the shadow.log file can be seen below
00:00:00.000150 [thread-0] n/a [shadow-message] [n/a] [master_run] Shadow v1.10.2-0-g1598ccc 2015-05-27 (built 2015-08-25)
00:00:00.000202 [thread-0] n/a [shadow-message] [n/a] [master_run] For more information, visit https://shadow.github.io or https://github.com/shadow
00:00:00.000290 [thread-0] n/a [shadow-message] [n/a] [master_run] Shadow initialized at 2019-03-27 23:54:10 using GLib v2.44.1
00:00:00.000310 [thread-0] n/a [shadow-message] [n/a] [master_run] args=shadow shadow.config.xml
00:00:00.000325 [thread-0] n/a [shadow-message] [n/a] [master_run] LD_PRELOAD=/home/shadow/.shadow/lib/libshadow-interpose.so
00:00:00.000338 [thread-0] n/a [shadow-message] [n/a] [master_run] SHADOW_SPAWNED=TRUE
00:00:00.000615 [thread-0] n/a [shadow-message] [n/a] [master_run] successfully parsed Shadow XML input!
00:00:00.000821 [thread-0] n/a [shadow-message] [n/a] [_topology_loadGraph] reading graphml topology graph at '/tmp/shadow-cdata-H4KHZZ.graphml.xml'...
00:00:00.001170 [thread-0] n/a [shadow-message] [n/a] [_topology_loadGraph] successfully read graphml topology graph at '/tmp/shadow-cdata-H4KHZZ.graphml.xml'
00:00:00.001193 [thread-0] n/a [shadow-message] [n/a] [_topology_checkGraphProperties] checking graph properties...
00:00:00.001242 [thread-0] n/a [shadow-message] [n/a] [_topology_checkGraphProperties] topology graph is complete, undirected, and strongly connected with 1 cluster
00:00:00.001255 [thread-0] n/a [shadow-message] [n/a] [_topology_checkGraphProperties] checking graph attributes...
00:00:00.001287 [thread-0] n/a [shadow-message] [n/a] [_topology_checkGraphProperties] successfully verified graph attributes
00:00:00.001298 [thread-0] n/a [shadow-message] [n/a] [_topology_checkGraphVertices] checking graph vertices...
00:00:00.001317 [thread-0] n/a [shadow-message] [n/a] [_topology_checkGraphVertices] 1 graph vertices ok
00:00:00.001327 [thread-0] n/a [shadow-message] [n/a] [_topology_checkGraphEdges] checking graph edges...
00:00:00.001341 [thread-0] n/a [shadow-message] [n/a] [_topology_checkGraphEdges] 1 graph edges ok
00:00:00.001352 [thread-0] n/a [shadow-message] [n/a] [_topology_checkGraph] successfully parsed graphml and validated topology: graph is strongly connected with 1 cluster, 1 vertex, and 1 edge
00:00:00.001488 [thread-0] n/a [shadow-message] [n/a] [program_new] successfully loaded private plug-in '/home/shadow/.shadow/plugins/libshadow-plugin-torctl.so' at 0x17236d0
00:00:00.001509 [thread-0] n/a [shadow-message] [n/a] [program_new] found '__shadow_plugin_init__' at 0x7f453a2a85f0
00:00:00.001521 [thread-0] n/a [shadow-message] [n/a] [program_new] found '__hoisted_globals' at 0x7f453a4ab190
00:00:00.001532 [thread-0] n/a [shadow-message] [n/a] [program_new] found '__hoisted_globals_pointer' at 0x7f453a4ab1c0
00:00:00.001543 [thread-0] n/a [shadow-message] [n/a] [program_new] found '__hoisted_globals_size' of value '48' at 0x7f453a2aa070

While for the Shadow version w/o Tor it functions correctly.

Does anyone suffer from a similiar case? Am I missing something? Shouldn't it be pre-configured?

**Comment by jtracey** [comment]
To be clear, by Mac, you mean Mac OS? Shadow is only intended to support Linux distros. Notably, it heavily relies on GNU's glibc (for ABI compatibility in the elf-loader component of Shadow). That Shadow works at all on Mac OS is surprising to me. You ran the tests? I.e.,
`./setup build -t && ./setup install && ./setup test`

**Comment by kobiebendalak** [comment]
Yes, MacOS.
I'll spin up a VM and see if it functions OK on Linux.

Thanks!

**Comment by JackChan1024** [comment]
> Yes, MacOS.
> I'll spin up a VM and see if it functions OK on Linux.
> 
> Thanks!

Can you find the way to run Shadow-Docker now? 
I have the same situation ，i test  the Docker on Ubuntu 16.04.6 LTS, it can't work and show the same  error :"shadow: symbol lookup error: /home/shadow/.shadow/plugins/libshadow-plugin-tor.so: undefined symbol: shadowtorpreload_init"
