### ISSUE TITLE
Wiki not updated with tgen removal

### ISSUE THREAD

**Issue by mello29** [shadow/shadow#687]
**Describe the issue**
I just installed (successfully) shadow on both Linux Mint 19.1 and Fedora 29. Trying to launch the example according to the wiki, I get
```
-> % shadow shadow.config.xml  
** Starting Shadow v1.13.0-53-ga31f3e21 2019-04-22 (built 2019-04-23) with GLib v2.56.3 and IGraph v0.7.1  
00:00:00.000152 [thread-0] n/a [message] [n/a] [shd-logger.c:296] [_logger_logStartupMessage] logging system started at 2019-04-23 16:49:31  
00:00:00.000183 [thread-0] n/a [message] [n/a] [shd-main.c:352] [_main_helper] Starting Shadow v1.13.0-53-ga31f3e21 2019-04-22 (built 2019-04-23) with GLib v2.56.3 and IGraph v0.7.1  
00:00:00.000216 [thread-0] n/a [message] [n/a] [shd-main.c:359] [_main_helper] For more information, visit https://shadow.github.io or https://github.com/shadow  
00:00:00.000219 [thread-0] n/a [message] [n/a] [shd-main.c:360] [_main_helper] logging current startup arguments and environment  
00:00:00.000232 [thread-0] n/a [message] [n/a] [shd-main.c:316] [_main_logEnvironment] arg: shadow  
00:00:00.000234 [thread-0] n/a [message] [n/a] [shd-main.c:316] [_main_logEnvironment] arg: shadow.config.xml  
00:00:00.000248 [thread-0] n/a [message] [n/a] [shd-main.c:370] [_main_helper] shadow will automatically adjust environment and relaunch  
00:00:00.000250 [thread-0] n/a [message] [n/a] [shd-main.c:371] [_main_helper] loading shadow configuration file  
00:00:00.000346 [thread-0] n/a [error] [n/a] [shd-configuration.c:856] [_parser_parseContents] g_markup_parse_context_parse: Shadow XML parsing error 5: attribute 'path': '/home/username/.shadow/bin/tgen' is not a valid path to an existing regular file
```

[Chapter 2](https://github.com/shadow/shadow/wiki/2-Getting-Started-Tutorial#basic-functional-tests) states that "Fortunately, Shadow already contains a traffic generator application (tgen) so you can get started without writing your own."
Commit [75973e75a6ab7d08ff0f04d9aab47fc0e4e97d89](https://github.com/shadow/shadow/commit/75973e75a6ab7d08ff0f04d9aab47fc0e4e97d89) on April 3, 2019 removed TGen Plugin for this repo.

**Fix**
The wiki should be updated accordingly.
I saw that everyone can do so but I preferred to open this issue to discuss how the authors think it's better.
To avoid confusion, I'd mention the commit and the need to clone the TGen repo and install it independently.

**Comment by robgjansen** [comment]
You are absolutely correct! Let me take a quick stab at the wiki update, and then it would be great if you could run through it for me and check for accuracy of the instructions. I'll post back here when I'm done with the update.

**Comment by robgjansen** [comment]
OK, the TGen setup process is now described here:
https://github.com/shadow/shadow/wiki/1.1-Shadow#tgen-setup

I also made changes to add pointers to TGen here:
https://github.com/shadow/shadow/wiki/2-Getting-Started-Tutorial#traffic-generation

Please test this out and let me know if anything is missing. Thanks!

**Comment by mello29** [comment]
I followed the steps mentioned in the update and TGen works just fine.
The wiki is very good and easy to follow/understand, in my opinion.

I'd say that this issue solved. Thanks to you for this tool!

**Comment by robgjansen** [comment]
Thanks for responding!
