### ISSUE TITLE
segfault on archlinux during test

### ISSUE THREAD

**Issue by renlord** [shadow/shadow#688]
**Describe the issue**
`./setup test` fails
```
2019-05-08 21:20:18,709 [INFO] calling 'ctest -j4'
Test project /home/rl/Projects/shadow/build/src/external/elf-loader
      Start  2: elfloader-test0
      Start  3: elfloader-test0_1
      Start  5: elfloader-test1
      Start  6: elfloader-test2
 1/34 Test  #2: elfloader-test0 ..................***Failed    0.32 sec
      Start  7: elfloader-test3
 2/34 Test  #5: elfloader-test1 ..................***Failed    0.50 sec
      Start  8: elfloader-test4
 3/34 Test  #6: elfloader-test2 ..................***Failed    0.53 sec
      Start  9: elfloader-test5
 4/34 Test  #3: elfloader-test0_1 ................***Failed    0.68 sec
      Start 10: elfloader-test6
 5/34 Test  #7: elfloader-test3 ..................***Failed    0.50 sec
      Start 11: elfloader-test7
 6/34 Test  #8: elfloader-test4 ..................***Failed    0.48 sec
      Start 12: elfloader-test8
 7/34 Test  #9: elfloader-test5 ..................***Failed    0.45 sec
      Start 13: elfloader-test8_5
 8/34 Test #10: elfloader-test6 ..................***Failed    0.37 sec
      Start 14: elfloader-test9
 9/34 Test #11: elfloader-test7 ..................***Failed    0.32 sec
      Start 15: elfloader-test10
10/34 Test #12: elfloader-test8 ..................***Failed    0.29 sec
      Start 16: elfloader-test11
11/34 Test #13: elfloader-test8_5 ................***Failed    0.33 sec
      Start 17: elfloader-test12
12/34 Test #14: elfloader-test9 ..................***Failed    0.30 sec
      Start 18: elfloader-test13
13/34 Test #15: elfloader-test10 .................***Failed    0.29 sec
      Start 19: elfloader-test14
14/34 Test #16: elfloader-test11 .................***Failed    0.28 sec
      Start 21: elfloader-test16
15/34 Test #18: elfloader-test13 .................***Failed    0.28 sec
      Start 23: elfloader-test18
16/34 Test #17: elfloader-test12 .................***Failed    0.34 sec
      Start 24: elfloader-test19
17/34 Test #19: elfloader-test14 .................***Failed    0.28 sec
      Start 25: elfloader-test20
18/34 Test #21: elfloader-test16 .................***Failed    0.28 sec
      Start 26: elfloader-test21
19/34 Test #23: elfloader-test18 .................***Failed    0.31 sec
      Start 27: elfloader-test22
20/34 Test #24: elfloader-test19 .................***Failed    0.39 sec
      Start 28: elfloader-test23
21/34 Test #25: elfloader-test20 .................***Failed    0.37 sec
      Start 29: elfloader-test24
22/34 Test #26: elfloader-test21 .................***Failed    0.42 sec
      Start 30: elfloader-test25
23/34 Test #27: elfloader-test22 .................***Failed    0.33 sec
      Start 31: elfloader-test27
24/34 Test #28: elfloader-test23 .................***Failed    0.46 sec
      Start 32: elfloader-test28
25/34 Test #29: elfloader-test24 .................***Failed    0.44 sec
      Start 33: elfloader-test29
26/34 Test #31: elfloader-test27 .................***Failed    0.50 sec
      Start  1: elfloader-internals
27/34 Test #30: elfloader-test25 .................***Failed    0.54 sec
      Start  4: elfloader-test0_2
28/34 Test #32: elfloader-test28 .................***Failed    0.44 sec
      Start 22: elfloader-test17
29/34 Test #33: elfloader-test29 .................***Failed    0.55 sec
      Start 34: elfloader-registers
30/34 Test #34: elfloader-registers ..............   Passed    0.09 sec
31/34 Test  #4: elfloader-test0_2 ................   Passed    0.41 sec
32/34 Test #22: elfloader-test17 .................   Passed    0.32 sec
33/34 Test  #1: elfloader-internals ..............   Passed    0.61 sec
      Start 20: elfloader-test15
34/34 Test #20: elfloader-test15 .................***Failed    0.24 sec

12% tests passed, 30 tests failed out of 34

Total Test time (real) =   3.63 sec

The following tests FAILED:
          2 - elfloader-test0 (Failed)
          3 - elfloader-test0_1 (Failed)
          5 - elfloader-test1 (Failed)
          6 - elfloader-test2 (Failed)
          7 - elfloader-test3 (Failed)
          8 - elfloader-test4 (Failed)
          9 - elfloader-test5 (Failed)
         10 - elfloader-test6 (Failed)
         11 - elfloader-test7 (Failed)
         12 - elfloader-test8 (Failed)
         13 - elfloader-test8_5 (Failed)
         14 - elfloader-test9 (Failed)
         15 - elfloader-test10 (Failed)
         16 - elfloader-test11 (Failed)
         17 - elfloader-test12 (Failed)
         18 - elfloader-test13 (Failed)
         19 - elfloader-test14 (Failed)
         20 - elfloader-test15 (Failed)
         21 - elfloader-test16 (Failed)
         23 - elfloader-test18 (Failed)
         24 - elfloader-test19 (Failed)
         25 - elfloader-test20 (Failed)
         26 - elfloader-test21 (Failed)
         27 - elfloader-test22 (Failed)
         28 - elfloader-test23 (Failed)
         29 - elfloader-test24 (Failed)
         30 - elfloader-test25 (Failed)
         31 - elfloader-test27 (Failed)
         32 - elfloader-test28 (Failed)
         33 - elfloader-test29 (Failed)
Errors while running CTest
2019-05-08 21:20:22,354 [INFO] ctest -j4 returned 8
2019-05-08 21:20:22,355 [WARNING] Failed to pass all test cases!
```

**To Reproduce**
I've installed glibc-dbg (glibc-2.29-1) by building the source from scratch with debuginfo.
`elfutils-0.176-1` was installed.
running `setup test` in the project directory fails.

**Operating System (please complete the following information):**
 - OS and version: ArchLinux
 - Kernel version: Linux <hostname> 5.0.13-arch1-1-ARCH #1 SMP PREEMPT Sun May 5 18:05:41 UTC 2019 x86_64 GNU/Linux

**Shadow (please complete the following information):**
 - Version: commit: `a31f3e2125afd4e4048e218916fb05749c09713b` running glib2-2.60.2-1 and igraph-0.7.1-10 (can't get actual version output since binary crashes)
 - Which plug-ins you are using:  None.

**Comment by jtracey** [comment]
How are you installing glibc debug symbols?

**Comment by renlord** [comment]
> How are you installing glibc debug symbols?
> 
> edit: Ah, "by building the source from scratch with debuginfo". I'll give this a quick try, but I can't guarantee I'll find time to look into this fully. There was a PR for Arch support though, #684, so it seems like someone got it working.

On ArchLinux, I just used `asp` to get the `glibc` package and then I edited the PKGBUILD file to include the options `(strip debug ....)` which installs the stripped debuginfo into `/usr/lib/debug/usr/lib`

**Comment by jtracey** [comment]
I managed to reproduce the bug in Arch, preliminary investigation seems to imply it's some new glibc behavior again, but I'm not sure what. I *think* it's trying to access a PLT entry that isn't populated yet, but I'm not positive. In any case, it's segfaulting on a null pointer function call in glibc's init. I don't have time to look into it right now, but if it is a new glibc thing, it's going to start popping up in other distributions.

As a side note, I saw a bug appear on Solus a few months ago, which is what I usually use to check the latest glibc, but that seems to have gone away. Could be a bug that was fixed in glibc? No way to know now.

**Comment by renlord** [comment]
> I managed to reproduce the bug in Arch, preliminary investigation seems to imply it's some new glibc behavior again, but I'm not sure what. I _think_ it's trying to access a PLT entry that isn't populated yet, but I'm not positive. In any case, it's segfaulting on a null pointer function call in glibc's init. I don't have time to look into it right now, but if it is a new glibc thing, it's going to start popping up in other distributions.
> 
> As a side note, I saw a bug appear on Solus a few months ago, which is what I usually use to check the latest glibc, but that seems to have gone away. Could be a bug that was fixed in glibc? No way to know now.

Thanks for taking time out to check this out. I'll also try and poke around to see if I can find anything on my end.

**Comment by robgjansen** [comment]
Is this an elf-loader issue? Or is it more general than elf-loader?

**Comment by jtracey** [comment]
My guess is it has something to do with elf-loader, but until the exact cause gets traced down, there's no way to be sure.

**Comment by jtracey** [comment]
Just got my archlinux VM up and running, and everything seems to work okay now. I think my original theory was correct, that a bug in glibc was introduced then patched, and it just took a while for the patch to make its way through.

**Comment by robgjansen** [comment]
Great, thanks for testing! Let's re-open if the issue occurs again.
