### ISSUE TITLE
potential assertion failures from IP assignment

### ISSUE THREAD

**Issue by jtracey** [shadow/shadow#689]
I haven't actually tested this, and maybe it's intended, but it looks like there is some potentially undesirable behavior from the code that picks IPs:

https://github.com/shadow/shadow/blob/a31f3e2125afd4e4048e218916fb05749c09713b/src/main/routing/shd-topology.c#L2202

In that function, if the available IPs all bitwise-and to 0 with the iphint value, then the function will return that there are no available IPs and assert fail at the check here:

https://github.com/shadow/shadow/blob/a31f3e2125afd4e4048e218916fb05749c09713b/src/main/routing/shd-topology.c#L2320

This means that, e.g., if you have a topology with a countrycode whose IPs are all low hamming weight, you're less likely to find a valid IP for that countrycode.

**Comment by jtracey** [comment]
It also seems a little strange that this code gives, e.g., the IPs "192.168.1.1" and "192.169.1.0" a farther distance than "192.168.1.1" and "224.168.1.1". Is bitwise-and really what we want here?

**Comment by robgjansen** [comment]
Yes, the longest prefix code is incorrect. It would only be correct if the following held:
- (0 & 0) == 1
- (1 & 1) == 1
- (0 & 1) == 0
- (1 & 0) == 0

But clearly (0 & 0) != 1.

**Comment by robgjansen** [comment]
The longest prefix match should be computed as the number of bits from left to right that match, where we stop at the first mismatch.

So
11000000.10101000.00000001.00000001 (192.168.1.1)
11000000.10101001.00000001.00000000 (192.169.1.0)
match the first 15 bits, and
11000000.10101000.00000001.00000001 (192.168.1.1)
11100000.10101000.00000001.00000001 (224.168.1.1)
match the first 2 bits.

**Comment by robgjansen** [comment]
@jtracey you want to try to write a patch?

**Comment by robgjansen** [comment]
Actually, I think we just need and XOR and then a negation. I.e., `!(a ^ b)`

For 192.168.1.1" and "192.169.1.0" this would give, e.g.,
11000000.10101000.00000001.00000001
XOR
11000000.10101001.00000001.00000000
equals
00000000.00000001.00000000.00000001

And then
NOT
00000000.00000001.00000000.00000001
equals
11111111.11111110.11111111.11111110

For "192.168.1.1" and "224.168.1.1" this would give
11000000.10101000.00000001.00000001
XOR
11100000.10101000.00000001.00000001
equals
00100000.00000000.00000000.00000000

and then
NOT
00100000.00000000.00000000.00000000
equals
11011111.11111111.11111111.11111111

We have
11111111.11111110.11111111.11111110 > 11011111.11111111.11111111.11111111
therefore 192.169.1.0 is a closer match than 224.168.1.1

Is my match correct here? If this seems right, then I think it's a very simple one line change.

**Comment by jtracey** [comment]
Yeah, xor as distance sounds good to me. Note that it still leaves the edge case I originally mentioned, but reduces it to only happening when the iphint is the bitwise-not of the only available IP, which is unlikely to happen by coincidence.

**Comment by robgjansen** [comment]
Does this solve both issues:

```
$ git diff src/main/routing/shd-topology.c
diff --git a/src/main/routing/shd-topology.c b/src/main/routing/shd-topology.c
index 9992ed5..64ae7d6 100644
--- a/src/main/routing/shd-topology.c
+++ b/src/main/routing/shd-topology.c
@@ -2217,8 +2217,8 @@ static igraph_integer_t* _topology_getLongestPrefixMatch(Topology* top, GQueue*
         _topology_unlockGraph(top);
         in_addr_t vertexIP = address_stringToIP(ipStr);
 
-        in_addr_t match = (vertexIP & ip);
-        if(match > bestMatch) {
+        in_addr_t match = ~(vertexIP ^ ip);
+        if(match > bestMatch || bestMatch == 0) {
             bestMatch = match;
             bestIP = vertexIP;
             bestVertexIndexPtr = vertexIndexPtr;
```

**Comment by jtracey** [comment]
Yup, lgtm!
