### ISSUE TITLE
Shadow EC2 image is missing

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#693]
Hello Mr. Jansen,
for a master thesis project I'm using Shadow Network Simulator. Since I would like to generate larger networks, I wanted to use Amazon's EC2 but the shadow machine is offline as shown below:

<image.png>

Would it be possible to reactivate the virtual machine?
Thank you so much.

**Comment by robgjansen** [comment]
The EC2 image has been taken offline by the organization that was hosting it. But it's OK! The image was very old and outdated anyway, and there is a much better way to run Shadow. (Sorry about the error, I need to update the Shadow website and the wiki page to remove the dead links!)

The best way to use EC2 is to just pick a Linux virtual machine image of your choice. For example, you could choose a Ubuntu 18.04 LTS image here:
http://cloud-images.ubuntu.com/locator/ec2/

Launch that image, and once you SSH into the machine, you can use it to set up Shadow following the setup guide:
https://github.com/shadow/shadow/wiki/1.1-Shadow

**Comment by zambo92** [comment]
Thank you so much :)
