### ISSUE TITLE
Weird string prepended to plugin arguments when passing those arguments(argv) to shell via a simple C program (compiled into .so).

### ISSUE THREAD

**Issue by GitX123** [shadow/shadow#702]
**Describe the issue**
I wrote a simple C program to accept arguments and pass those arguments to shell to execute by calling system(). The program is compiled into a shared library and taken as a shadow plugin. Whenever I try to run the simulation, weird string is pre-pended to the "command" variable, such as "?褥?echo Hello World". This cannot be fixed by simply filtering out the executable name out of the first argument (strcat(command, filter(argv[i])); , "?褥?echo" => "echo"), the weird string seems to be added during when **calling the functon** (the same if system() is changed to puts()).
[program]
```C
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#define MAX_COMMAND_SIZE 100

int main(int argc, char *argv[]){
    char command[MAX_COMMAND_SIZE];

    for(int i = 1; i < argc; i++){   
        strcat(command, argv[i]);
        strcat(command, " ");
    }
    // system(command);
    puts(command)
    return 0;
}
```

**To Reproduce**
[Compile]
```
gcc -fPIC -c lib_shell.c
gcc -shared -o lib_shell.so lib_shell.o
```
[Topology file]
```xml
<?xml version='1.0' encoding='utf-8'?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
<key id="d8" for="edge" attr.name="packetloss" attr.type="double"/>
<key id="d7" for="edge" attr.name="jitter" attr.type="double"/>
<key id="d6" for="edge" attr.name="latency" attr.type="double"/>
<key id="d5" for="node" attr.name="packetloss" attr.type="double"/>
<key id="d4" for="node" attr.name="bandwidthdown" attr.type="long"/>
<key id="d3" for="node" attr.name="bandwidthup" attr.type="long"/>
<key id="d2" for="node" attr.name="geocode" attr.type="string"/>
<key id="d1" for="node" attr.name="ip" attr.type="string"/>
<key id="d0" for="node" attr.name="type" attr.type="string"/>
<graph edgedefault="undirected">
<node id="node0">
  <data key="d0">client</data>
  <data key="d1">0.0.0.0</data>
  <data key="d2">TW</data>
  <data key="d3">10240</data>
  <data key="d4">10240</data>
  <data key="d5">0.0</data>
</node>
<node id="node1">
  <data key="d0">client</data>
  <data key="d1">0.0.0.1</data>
  <data key="d2">TW</data>
  <data key="d3">10240</data>
  <data key="d4">10240</data>
  <data key="d5">0.0</data>
</node>
<edge source="node0" target="node1">
  <data key="d6">50.0</data>
  <data key="d7">0.0</data>
  <data key="d8">0.0</data>
</edge>
</graph></graphml>
```
[Configuration file]
```xml
<shadow stoptime="20">
  <topology path="./topology.graphml.xml"/>
  <plugin id="shell" path="./lib_shell.so"/>
  <host id="node0">
    <process plugin="shell" starttime="1" arguments="echo Hello World"/>
  </host>
  <host id="node1">
    <process plugin="shell" starttime="1" arguments="echo Hello World"/>
  </host>
</shadow>
```
[Run simulation]
```
shadow shadow_config.xml > shadow.log
```
[Result]
![shadow_issue_result](https://user-images.githubusercontent.com/30967975/70905186-3bb4fe80-203e-11ea-9d54-2d574c5de1cb.PNG)

**Operating System :**
 - OS and version: Ubuntu 18.04.3 LTS
 - Kernel version: Linux 4.15.0-64-generic

**Shadow :**
 - Version: Shadow v1.13.1-1-g2a9245f1 2019-08-12 (built 2019-08-16) running GLib v2.56.4 and IGraph v0.7.1

 - Which plug-ins you are using:  
Self-created plugin (.so).

**Comment by jtracey** [comment]
system() requires forking, which is not supported by shadow (and likely can never be supported)

**Comment by robgjansen** [comment]
As Justin mentioned, plugins that are running in Shadow should not fork processes, as this is not currently supported. This page on the wiki explains the requirements for plugins:
https://github.com/shadow/shadow/wiki/2-Getting-Started-Tutorial#shadow-plug-ins

However, forking can be supported by Shadow, but it requires a change to the architecture. This is currently still in the research phase and we don't have an estimate of when that support might be released.

**Comment by GitX123** [comment]
Thanks for the reply, I actually read the doc before, but I gave it a try because I was thinking system() function a bit differently than for()/exec(). However, the problem happens to functions which do not fork process as well, such puts().

**Comment by robgjansen** [comment]
Could you update your example in your first message so that it uses `puts()` instead of `system()`? That will make it easier to debug.
