### ISSUE TITLE
Migrate wiki into docs subdirectory

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#705]
The wiki is currently a separate git repo from the code itself. Migrating it into the same repo would create a tighter coupling between the code and documentation, e.g. allowing us to make atomic changes to both simultaneously. It'd also force updates to be in the form of pull requests which can be reviewed.

- [x] Port wiki with history into the code repo.
- [x] Maybe/TBD: Update wiki pages to point to the new locations, in the code repo.
- Deferred ~[ ] Delete the wiki entirely. (Possibly after some time period of leaving the stubs up)~

**Comment by sporksmith** [comment]
Moving discussion from https://github.com/shadow/shadow/pull/708#issuecomment-580770139

Let's move discussion to #705 for posterity :)

> Now that this is merged, we have 3 options:
> 
>     1. Leave the wiki as-is
> 
>     2. Disable the wiki, removing the pages and breaking and links pointing to it
> 
>     3. Leave as-is, but restrict editing to those with push access (i.e. me and @sporksmith) - with the policy that the wiki is read-only
> 
> 
> I think 3. is the best answer, with the goal of eventually disabling the wiki after some time. But I could be talked into doing 2. now.

I was thinking roughly 3, but also to replace the content of the individual pages with links to their individual new homes, so that people don't unknowingly consume stale docs. Preparing a pull request to do so now.

**Comment by sporksmith** [comment]
@robgjansen 

It turns out there's no way to create a pull request for a wiki (more reason to move the docs into the code repo!). Instead I pushed the proposed rewrite to here: https://github.com/sporksmith/Temp-Shadow-Wiki/wiki

PTAL, and if it looks good I'll push directly to the shadow wiki.

**Comment by robgjansen** [comment]
Looks good to me.

Also, FYI, I noticed that if you to visit a page on the wiki that does not exist, [like this one](https://github.com/sporksmith/Temp-Shadow-Wiki/wiki/5-Developer-Guide), then it redirects you to the wiki home page. But that doesn't give us a one-to-one mapping from the old page to the new one, so it's probably best to do it the way you have done. (Maybe at the point when we are ready to delete the wiki, we could instead delete all pages except the Home.md page, and then add a short blurb on it and a link to the docs/README.md?)

**Comment by sporksmith** [comment]
Sounds good
