### ISSUE TITLE
python-pyelftools 

### ISSUE THREAD

**Issue by SinaiNday** [shadow/shadow#719]
- The `python-pyelftools` is not found on ubuntu 14.04.5 what should I do
- I removed it and tried to run` ./setup build --clean --test` in shadow folder here is the error 
```
Scanning dependencies of target elfedit
[  1%] Building C object src/external/elf-loader/CMakeFiles/elfedit.dir/elfedit.c.o
Linking C executable elfedit
[  1%] Built target elfedit
Scanning dependencies of target vdlconfig
[  2%] Generating vdl-config.h
Traceback (most recent call last):
  File "/home/test/shadow/src/external/elf-loader/extract-system-config.py", line 8, in <module>
    from elftools.elf.elffile import ELFFile
ImportError: No module named elftools.elf.elffile
make[2]: *** [src/external/elf-loader/vdl-config.h] Error 1
make[1]: *** [src/external/elf-loader/CMakeFiles/vdlconfig.dir/all] Error 2
make: *** [all] Error 2
2020-02-10 14:23:46,715 [ERROR] Non-zero return code from make.

```

**Comment by orville92** [comment]
I would like to test a bitcoin network.

**Comment by sporksmith** [comment]
If you're able to, it's probably better to use a newer Linux distro. Ubuntu 14 is past EOL. https://wiki.ubuntu.com/Releases

We're currently running continuous integration on Ubuntu 18.04, so that should be a well-supported target for you if you're able to upgrade to it.

**Comment by jtracey** [comment]
The standard way to install elftools on Ubuntu 14.04 is pip. You'll also need to compile glib, and libigraph from source. As pointed out though, using a more recent Ubuntu release is the better option.

**Comment by orville92** [comment]
Recent Ubuntu doesn’t work with bitcoin as mentioned on the site

**Comment by orville92** [comment]
I will try linux distro @sporksmith thanks

**Comment by orville92** [comment]
@sporksmith [here](https://github.com/shadow/shadow-plugin-bitcoin/wiki) you suggested to use **shadow 1.10.2** and **newest linux** but `sudo apt-get install libstdc++ libstdc++-dev clang llvm llvm-dev` does not work.

[here too](https://github.com/shadow/shadow-plugin-bitcoin) you suggested to use **linux 14** and **shadow 1.12.0** 
I am confused, I do not know which one to use since all the suggestions are not working.
**If You have tried to simulate bitcoin, please share the virtual machine with all the dependencies installed.**

**Comment by sporksmith** [comment]
Sorry, I'm new to the project and not very familiar with the bitcoin plugin. I agree it looks like the bitcoin-plugin docs seem to be targeting Ubuntu 14.

Have you tried jtracey's suggestion of installing elftools on Ubuntu 14 using pip?

**Comment by sporksmith** [comment]
Opened shadow/shadow-plugin-bitcoin#17

**Comment by orville92** [comment]
I tried @jtracey 's suggestion but nothing worked. 
@00h-i-r-a00 said that He tried and everything worked [here](https://github.com/shadow/shadow/issues/302#issuecomment-285093816), @00h-i-r-a00 can you share your ubuntu VM with all stuff installed or explain exactly what you did?

**Comment by stevenengler** [comment]
Closing since we no longer support [shadow-plugin-bitcoin](https://github.com/shadow/shadow-plugin-bitcoin) (repository has been archived), and Ubuntu 14.04 is not in our list of supported platforms.
