### ISSUE TITLE
  build error 

### ISSUE THREAD

**Issue by GitZinger** [shadow/shadow#728]
**Describe the issue**
build error

**To Reproduce**
Steps to reproduce the behavior. If you problem involves a simulation, please include the configuration file that you used.

 ./setup build --clean --debug

**Operating System (please complete the following information):**
 - OS and version: post the output of `lsb_release -d`  
red hat 6.10
 - Kernel version: post the output of `uname -a`  
2.6.32-754.11.1.el6.x86_64 #1 SMP Tue Jan 22 17:25:23 EST 2019 x86_64 x86_64 x86_64 GNU/Linux

**Shadow (please complete the following information):**
 - Version: post the output of `shadow --version`  
[e.g. Shadow v1.13.0-36-g337d565-dirty 2019-02-07 (built 2019-02-08) running GLib v2.54.2 and IGraph v0.7.1]
 - Which plug-ins you are using:  
[e.g. Shadow-Tor]

**Additional context**
Scanning dependencies of target display-relocs
[  0%] Building C object src/external/elf-loader/CMakeFiles/display-relocs.dir/display-relocs.c.o
cc1: error: unrecognized command line option "-fno-tree-loop-distribute-patterns"
make[2]: *** [src/external/elf-loader/CMakeFiles/display-relocs.dir/display-relocs.c.o] Error 1
make[1]: *** [src/external/elf-loader/CMakeFiles/display-relocs.dir/all] Error 2
make: *** [all] Error 2
2020-02-28 22:53:02,385 [ERROR] Non-zero return code from make

**Comment by robgjansen** [comment]
Is it possible that you can run on something newer than Red Hat 6? [RHEL 6 is already out of maintenance and is going EOL 11/30/2020](https://endoflife.software/operating-systems/linux/red-hat-enterprise-linux-rhel).

FWIW, our continuous integration is set up on Ubuntu 18.04, so it should be well supported there.

**Comment by GitZinger** [comment]
> Is it possible that you can run on something newer than Red Hat 6? [RHEL 6 is already out of maintenance and is going EOL 11/30/2020](https://endoflife.software/operating-systems/linux/red-hat-enterprise-linux-rhel).
> 
> FWIW, our continuous integration is set up on Ubuntu 18.04, so it should be well supported there.

unfortunately no.
So I guess the main problem here is in some cmakelist files, there are some 
`/usr/bin/cc   -O3 -g3 -fno-tree-loop-distribute-patterns`
I guess if it will be working
`gcc -fno-tree-loop-distribute-patterns`
however such lines there are a ton, is it possible I just change one line at the topest folder to make every children file containing such line to  be superseded with gcc???

**Comment by robgjansen** [comment]
You can set the compiler to gcc by setting an environment variable before running the setup script.
```
CC=/usr/bin/gcc setup build ...
```

Make sure to replace the path above with the path to your gcc, which you can find with `which gcc`.

**Comment by GitZinger** [comment]
right now! I figured out it.
but I got a new problem:

`debug_filename = search_debug_file ()
 raise CouldNotFindFile ()
`

I have installed the glibc.
how to add my glibc path into 
shadow/src/external/elf-loader/extract-system-config.py
??

thank you

**Comment by robgjansen** [comment]
Have you followed the documentation to install the appropriate dependencies? Because that error message indicates that you don't have the required glibc debug package installed. You ay be missing other dependencies too.

See here:
https://github.com/shadow/shadow/blob/master/docs/1.1-Shadow.md

**Comment by GitZinger** [comment]
> Have you followed the documentation to install the appropriate dependencies? Because that error message indicates that you don't have the required glibc debug package installed. You may be missing other dependencies too.
> 
> See here:
> https://github.com/shadow/shadow/blob/master/docs/1.1-Shadow.md
I did. I manually installed every package because I don't have the root.
I saw a old post https://github.com/shadow/shadow/issues/350 but since then the py file has changed a lot. like the format of the debug path.
Could you walk me through how to specify the debuginfo in the shadow/src/external/elf-loader/extract-system-config.py there?
I installed the glibc in a folder in there ".../lib "
I have the 
`"ld-2.19.so            ld-linux-x86-64.so.2"`

**Comment by robgjansen** [comment]
https://github.com/shadow/shadow/blob/e24ebecc3a9809a5195227032c4cf4122089ff91/src/external/elf-loader/extract-system-config.py#L94-L117

I think you'll need to add to these lists. Maybe @jtracey can help here?

**Comment by GitZinger** [comment]
I added debug_files, and it seems working. but got another one error, build_ids??

Traceback (most recent call last):
  File "/shadow/shadow/src/external/elf-loader/extract-system-config.py", line 75, in find_build_id
    note = next(section.iter_notes())
AttributeError: 'NoneType' object has no attribute 'iter_notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shadow/src/external/elf-loader/extract-system-config.py", line 210, in <module>
    main(sys.argv[1:])
  File "/shadow/src/external/elf-loader/extract-system-config.py", line 189, in main
    find_build_id(debug_filename)
  File "/shadow/src/external/elf-loader/extract-system-config.py", line 80, in find_build_id
    build_id = codecs.getencoder('hex')(section.data()[-20:])[0].decode('UTF-8')
AttributeError: 'NoneType' object has no attribute 'data'
make[2]: *** [src/external/elf-loader/vdl-config.h] Error 1
make[1]: *** [src/external/elf-loader/CMakeFiles/vdlconfig.dir/all] Error 2
make: *** [all] Error 2
2020-03-06 10:55:25,320 [ERROR] Non-zero return code from make.

**Comment by jtracey** [comment]
You should only have to change one of debug_files or build_ids, the way the script works is it tries to find the debug symbols in the debug files, and if that doesn't work, it falls back on build ids (because different distros store debug symbols in different places).

When you compiled glibc, did you compile debug symbols as well? And if you did compile debug symbols, did you compile them into the shared object itself, or as a separate file? Assuming you did compile debug symbols, you just need to add the literal path, and a regex matching the file with the debug symbols, to debug_files list (similar to the change you made, but only matching the one file).

**Comment by GitZinger** [comment]
> You should only have to change one of debug_files or build_ids, the way the script works is it tries to find the debug symbols in the debug files, and if that doesn't work, it falls back on build ids (because different distros store debug symbols in different places).
> 
> When you compiled glibc, did you compile debug symbols as well? And if you did compile debug symbols, did you compile them into the shared object itself, or as a separate file? Assuming you did compile debug symbols, you just need to add the literal path, and a regex matching the file with the debug symbols, to debug_files list (similar to the change you made, but only matching the one file).
1.
So when I compiled the glibc, I just used the 
```
./configure --prefix=..../cdebug
make
make install
```
anything else I should do more when compiling?
2. so currently in that folder **..../cdebug/lib/**
I have such files:
**ld-2.19.so ld-linux-x86-64.so.2**
does this count?
3.  here is what I added in that py file:
```
debug_files = [ ('..../cdebug/lib/',r'ld-[0-9.]+\.so.debug'),
                      ('.../cdebug/lib/',r'ld-linux-x86-64\.so\.2'), ]
 build_ids = [ ('..../cdebug/lib/',r'ld-linux-x86-64\.so\.2'),
                  ('..../cdebug/lib/',r'ld-[0-9.]+\.so'),
        ]
```
still it does not work.
 
Could you walk me through a little bit more how to fix it from here? thank you so much!

**Comment by jtracey** [comment]
Check your directories and filenames for typos in the script. You shouldn't change the build_ids at all, but the error is being thrown in the part of the script that uses it, which tells me it didn't find the file you specified and was falling back to it.

**Comment by GitZinger** [comment]
> Check your directories and filenames for typos in the script. You shouldn't change the build_ids at all, but the error is being thrown in the part of the script that uses it, which tells me it didn't find the file you specified and was falling back to it.

Thank you so much for being patient.
I put 5 possible writing style:
and in the debug_files  list,
```
debug_files = [...
('/.../cdebug/lib/',r'ld-linux-x86-64\.so\.2\.debug'),
        ('/.../cdebug/lib/',r'ld-linux-x86-64\.so\.2'),
('/.../abox/cdebug/lib/',r'ld-[0-9.]+\.so'),
        ('/.../cdebug/lib/',r'ld-2\.19\.so\.debug'),
        ('/.../cdebug/lib/',r'ld-2\.19\.so'),
]
```



still it does not work! so lost!
```
Scanning dependencies of target vdlconfig
[  3%] Generating vdl-config.h
Traceback (most recent call last):
  File "/shadow/src/external/elf-loader/extract-system-config.py", line 75, in find_build_id
    note = next(section.iter_notes())
AttributeError: 'NoneType' object has no attribute 'iter_notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shadow/src/external/elf-loader/extract-system-config.py", line 212, in <module>
    main(sys.argv[1:])
  File "/shadow/src/external/elf-loader/extract-system-config.py", line 191, in main
    find_build_id(debug_filename)
  File "/shadow/src/external/elf-loader/extract-system-config.py", line 80, in find_build_id
    build_id = codecs.getencoder('hex')(section.data()[-20:])[0].decode('UTF-8')
AttributeError: 'NoneType' object has no attribute 'data'
make[2]: *** [src/external/elf-loader/vdl-config.h] Error 1
make[1]: *** [src/external/elf-loader/CMakeFiles/vdlconfig.dir/all] Error 2
make: *** [all] Error 2
2020-03-06 19:23:46,541 [ERROR] Non-zero return code from make.
```
