### ISSUE TITLE
IO via LSB IO routines isn't interposed

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#739]
The Linux Standard Base (LSB) defines some [additional IO routines](https://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/libc.html#AEN3333), which we currently do not interpose. This can cause shadow to miss some IO.

For example, programs compiled with the glibc headers in [some configurations](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(fontScale:14,j:1,lang:___c,selection:(endColumn:18,endLineNumber:3,positionColumn:18,positionLineNumber:3,selectionStartColumn:18,selectionStartLineNumber:3,startColumn:18,startLineNumber:3),source:'%23include+%3Cstdio.h%3E%0Avoid+f()+%7B%0A++++putchar(!'c!')%3B%0A%7D'),l:'5',n:'0',o:'C+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:cg92,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'1',trim:'1'),fontScale:14,j:1,lang:___c,libs:!(),options:'-O2',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'x86-64+gcc+9.2+(Editor+%231,+Compiler+%231)+C',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4) end up inlining `putchar` using a call to [_IO_putc](https://refspecs.linuxbase.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/baselib--io-putc-3.html)

**Comment by sporksmith** [comment]
We should defer fixing this until after #738 is resolved (or as part of it).

**Comment by RWails** [comment]
Not sure if this is directly related to this issue, but on one testing platform (Ubuntu 18.04.5, GCC v7.5), an inline definition of `read` was being used, which eventually dispatched `__GI___libc_read`, a function that *is not* interposed in Shadow's preload library.

(Adding this function to Shadow's interpose list and defining

```
ssize_t process_emu___GI___libc_read(Process* proc, int fd, void *buff, size_t numbytes) {
	return process_emu_read(proc, fd, buff, numbytes);
}
```

resolved the issue for my particular error.)

**Comment by sporksmith** [comment]
This is somewhat moot now since we'll still interpose at the syscall level. Perhaps still worth wrapping these routines for performance, though.

**Comment by sporksmith** [comment]
Closing since these are intercepted at the syscall level, and we don't know this to happen in a hot path that'd effect performance. Eventually we should make it easier to profile what syscalls are getting intercepted via seccomp instead of at the libc level.
