### ISSUE TITLE
Error on running Getting Started Example

### ISSUE THREAD

**Issue by florian-vuillemot** [shadow/shadow#742]
**Describe the issue**
I'm running the Getting Started Example and obtaining the following error:
> ** Stopping Shadow, returning code -1 (error)

If I look in the client logs (shadow.data/hosts/client/stdout-client.tgen.1000.log) I can see the following line
> 2000-01-01 00:00:02 946684802.000000 [critical] [tgen-graph.c:1299] [tgengraph_new] error (4) while loading graph: Vertex attribute 'type' is unknown, please check your config and try again.

**To Reproduce**
Clone and install the latest Shadow and Tgen version then go in resource/examples and run `shadow shadow.config.xml > shadow.log`.

**Operating System (please complete the following information):**
 - OS and version: post the output of `lsb_release -d`  
Linux Mint 19.1 Tessa
 - Kernel version: post the output of `uname -a`  
Linux user 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Shadow (please complete the following information):**
 - Version: post the output of `shadow --version`  
Shadow v1.13.2-510-gd54fa632 2020-03-13 (built 2020-03-21) running GLib v2.56.4 and IGraph v0.7.1

 - Which plug-ins you are using:  
No plug-in used

**Additional context**
I installed Shadow and Tgen from by clone the repository. I installed dependencies by following the 1.1-Shadow.md documentation.
No files were changed, I checked with a `git status`.
Files `shadow.data/hosts/server1` and `shadow.data/hosts/server2` contain only logs messages with the following pattern:
> 2000-01-01 00:59:59 946688399.000000 [message] [tgen-driver.c:254] [_tgendriver_onHeartbeat] [driver-heartbeat] [bytes-read=0,bytes-written=0]
Moreover, I can see in the beginning of the logs the files
> successfully loaded graphml file 'tgen.server.graphml.xml' and validated acti
ons: graph is weakly connected with 1 cluster, 1 vertex, and 0 edges

My shadow.data/hosts/client/stdout-client.tgen.1000.log:
> 2000-01-01 00:00:02 946684802.000000 [message] [tgen-main.c:45] [_tgenmain_run] Initializing TGen v1.0.0 running GLib v2.56.4 and IGraph v0.7.1 on host client with process id 1000
> 2000-01-01 00:00:02 946684802.000000 [message] [tgen-main.c:76] [_tgenmain_run] Set SIG_IGN for signal SIGPIPE
> 2000-01-01 00:00:02 946684802.000000 [info] [tgen-graph.c:1193] [_tgengraph_loadNewGraph] reading graphml action graph at 'tgen.client.graphml.xml'...
> 2000-01-01 00:00:02 946684802.000000 [info] [tgen-graph.c:1205] [_tgengraph_loadNewGraph] successfully read graphml action graph at 'tgen.client.graphml.xml'
> 2000-01-01 00:00:02 946684802.000000 [warning] [tgen-graph.c:1177] [_tgengraph_parseGraphProperties] failed to verify graph properties and attributes
> 2000-01-01 00:00:02 946684802.000000 [critical] [tgen-graph.c:1299] [tgengraph_new] error (4) while loading graph: Vertex attribute 'type' is unknown, please check your config and try again.
> 2000-01-01 00:00:02 946684802.000000 [critical] [tgen-main.c:82] [_tgenmain_run] cannot continue: traffic generator config file 'tgen.client.graphml.xml' failed validation

**Comment by robgjansen** [comment]
The issue is that we recently pushed a new version of TGen, and some of the config format changed. So we'll need to update the Shadow examples too.

In the meantime, there are some more detailed examples of running an example here:
https://github.com/shadow/tgen/tree/master/resource

**Comment by florian-vuillemot** [comment]
Ok, thank you.
I will search, try to fix it and come back to you.

**Comment by florian-vuillemot** [comment]
I updated the file by changing the node "transfer" to "stream" ("traffic" or "flow" worked also). Moreover, I updated the attributes "type", "protocol" and "size" to "recvsize" and "sendsize" (1 MiB each). 

**But:** Even worse then in https://github.com/shadow/shadow/issues/703, I obtain no result when I do
```
for d in shadow.data/hosts/*client*; do grep "transfer-complete" ${d}/* ; done | tee clients.log | wc -l
0
```
Based on the shadow issue, did you change something again in tgen that can allow such result ?

**Comment by robgjansen** [comment]
I just noticed I overlooked your reply! Sorry!

`transfer` was renamed to `stream`, and I think you need to grep for `stream-success` rather than `transfer-complete`.

Try this:

```
for d in shadow.data/hosts/*client*; do grep "stream-success" ${d}/* ; done | tee clients.log | wc -l
```

**Comment by florian-vuillemot** [comment]
I obtained 99, thank you !
