### ISSUE TITLE
Update scripts to generate new topology files

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#748]
- [x] The scripts in `src/tools/topology` are obsolete and should be removed.
  - [x] We should add and document the latest methods for creating new topology files (may need help from @pastly)

**Comment by robgjansen** [comment]
The new tool and documentation for generating Internet atlas.topology.xml files will be published [in the new shadow/atlas repo here](https://github.com/shadow/atlas), rather than adding those scripts to the base Shadow repo.

**Comment by pastly** [comment]
You’ve mentioned wanting city names in the atlas topology files in addition to the unique but opaque MaxMind city codes. I can either make the citycode node property something like 8764234-Wichita or I can leave it as 8764234 and add an additional node property that lists the city name Wichita.

An example of a node at it exists.

```
  <key attr.name="countrycode" attr.type="string" for="node" id="d5" />
  <key attr.name="citycode" attr.type="string" for="node" id="d4" />
  <key attr.name="ip" attr.type="string" for="node" id="d3" />
  <key attr.name="bandwidthup" attr.type="long" for="node" id="d2" />
  <key attr.name="bandwidthdown" attr.type="long" for="node" id="d1" />
[...]
    <node id="188.37.57.105">
      <data key="d1">13123</data>
      <data key="d2">6101</data>
      <data key="d3">188.37.57.105</data>
      <data key="d4">2267057</data>
      <data key="d5">PT</data>
    </node>
```

AIUI Shadow doesn't care what the city/country codes are as long as they're unique, and it will ignore extraneous properties. So WRT that either way is fine.

**Comment by robgjansen** [comment]
Right now, the `citycode` attribute is parsed as a string:

https://github.com/shadow/shadow/blob/08035fcfe30375ff53d43dd809305c897f127d16/src/main/routing/shd-topology.c#L877-L887

and it is also compared with the `citycodehint` as a string:

https://github.com/shadow/shadow/blob/08035fcfe30375ff53d43dd809305c897f127d16/src/main/routing/shd-topology.c#L2096-L2105

Which means we should be able to append/prepend the human-readable city name without any changes to Shadow. But there is a problem with changing the `citycode` attribute to contain *cityid-cityname* instead of just *cityid*:

- It would break existing configs where people are using *cityid* only in their `citycodehint` attribute, i.e., their hosts may no longer be attached in the topology where they expect.

And I think there would be a problem changing the `citycode` attribute to contain just the *cityname*:

- I believe the *cityid* that we currently use is *guaranteed to be unique* whereas the city name may not be unique.

But they are **distinct pieces of information**, so I think ideally we would keep them in separate node attributes.

I suggest the following:

1. Keep the `citycode` attribute as-is, i.e., continue setting citycode=*cityid* (e.g., `citycode=8764234`)
1. Create a new attribute for the city name, i.e., cityname=*cityname* (e.g., `cityname=Wichita`)

This way the old behavior of `citycode` will continue functioning as before, and we will have a new `cityname` attribute that Shadow doesn't understand now but will eventually be able to take advantage of. Note that Shadow should accept the topology even though it contains an unknown attribute:

https://github.com/shadow/shadow/blob/08035fcfe30375ff53d43dd809305c897f127d16/src/main/routing/shd-topology.c#L629-L631

**Comment by pastly** [comment]
Based on @robgjansen's comment, I have implemented the addition of city name as a new node attribute.

**Comment by robgjansen** [comment]
I believe the scripts have now been updated, documented, and posted to https://github.com/shadow/atlas. Thanks @pastly!
