### ISSUE TITLE
Clarify relationship between hosts and topology-nodes in documentation

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#776]
Following up from discussion on #773 : I was looking over the docs to better understand the relationship between hosts and nodes. I have a few questions:

From https://github.com/shadow/shadow/blob/master/docs/3.1-Shadow-Config.md:

> bandwidthdown and bandwidthup optionally specify the downstream and upstream bandwidth capacities for this host, and override any default bandwidth values set in the cluster element corresponding to the cluster attribute. If not given, the default bandwidth values from the assigned cluster element are used.

As far as I can tell there is no `cluster` element. Is this left over from an old config format? Do these override the corresponding attributes on whatever node the host gets attached to?

> The iphint, geocodehint, and typehint attributes provide hints to Shadow's name and routing system on where to attach this host to the topology. These hints will be matched based on the values of the ip, geocode, and type of the vertices as specified in the topology file.

How is the matching done? Is the iphint used for an exact match against the ip address in the topology, or is there some kind of netmask logic? How do geocodehint and typehint work?

Presumably hosts get assigned IP addresses? Are those distinct from the node ip addresses in the topology?

**Comment by jtracey** [comment]
The code that determines the matching is located here:
https://github.com/shadow/shadow/blob/5669acda4b5ef4001c52b43aeaf186e9e4110170/src/main/routing/topology.c#L2248

**Comment by robgjansen** [comment]
> As far as I can tell there is no cluster element. Is this left over from an old config format?

Yes the term "cluster" is old and should be removed.

I think eventually we want to kill the `geocodehint` since our [topology generation tools](https://github.com/shadow/atlas) use `countryCodeHint` instead. Also, we don't set the `type` or the `asn`, so the `typeHint` could be removed too.

Maybe some of this isn't in the docs anyway...

**Comment by robgjansen** [comment]
Done in #1374
