### ISSUE TITLE
More human readable/editable topologies

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#778]
Broken out of #773. This is lowish priority, but we can consolidate ideas/discussion on the topic here.

Today the topologies in our examples look something like:

```xml
<topology><![CDATA[<?xml version="1.0" encoding="utf-8"?><graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key attr.name="packetloss" attr.type="double" for="edge" id="d6" />
  <key attr.name="latency" attr.type="double" for="edge" id="d5" />
  <key attr.name="packetloss" attr.type="double" for="node" id="d4" />
  <key attr.name="countrycode" attr.type="string" for="node" id="d3" />
  <key attr.name="bandwidthdown" attr.type="int" for="node" id="d2" />
  <key attr.name="bandwidthup" attr.type="int" for="node" id="d1" />
  <key attr.name="ip" attr.type="string" for="node" id="d0" />
  <graph edgedefault="undirected">
    <node id="isp">
      <data key="d0">0.0.0.0</data>
      <data key="d1">2251</data>
      <data key="d2">17038</data>
      <data key="d3">US</data>
      <data key="d4">0.0</data>
    </node>
    <edge source="isp" target="isp">
      <data key="d5">50.0</data>
      <data key="d6">0.01</data>
    </edge>
  </graph>
</graphml>
]]></topology>
```

The graphml format is generally visually noisy, and the networkx graphml exporter chooses opaque attribute-id's like "d6", forcing a reader to have to look back and forth between the `data` tags and `key` tags to understand what's happening.

graphml was chosen in part because it's a format that many tools understand. It's particularly useful that the `networkx` python package understands it (for generating graphs), and that the `igraph` library can import it (for use internally in Shadow).

**Comment by sporksmith** [comment]
I was poking around networkx a bit to see if there's a way to produce nicer graphml output (with better `key` strings, in particular). There doesn't appear to be. However it *does* support other output formats, including some others [supported by igraph](https://igraph.org/c/doc/igraph-Foreign.html). Experimenting with `generate_example_config.py`, [gml](https://en.wikipedia.org/wiki/Graph_Modelling_Language) seems like a promising candidate:

```
graph [
  node [
    id 0
    label "poi-1"
    ip "0.0.0.0"
    bandwidthup 2251
    bandwidthdown 17038
    countrycode "US"
    packetloss 0.0
  ]
  edge [
    source 0
    target 0
    latency 50.0
    packetloss 0.05
  ]
]
```

Generally this is a lot easier to parse visually than the graphml above. One issue is that networkx generates numeric node-ids and reassigns the ids we supplied as `label` attributes. Looking at the [specification](https://web.archive.org/web/20190303094704/http://www.fim.uni-passau.de:80/fileadmin/files/lehrstuhl/brandenburg/projekte/gml/gml-technical-report.pdf), this appears to be because IDs are required to be integers. This means both that Shadow would need to understand the "label" attribute on topologies imported via GML, and that this isn't an unmitigated readability win. While the attributes (latency, packetloss, etc.) are now human readable, now the source and target in the edges require cross-referencing with the node list.

Overall I think adding support for gml as an alternative topology format (via e.g. `<topology type="gml"...`) would be a usability win, I'm not sure it's *enough* of a win to justify the development and maintenance cost.

**Comment by robgjansen** [comment]
>now the source and target in the edges require cross-referencing with the node list.

It looks like we might be able to work around this using an edge label, like this:

```gml
graph [
  node [
    id 0
    ip_address "0.0.0.0"
    bandwidth_up 2251
    bandwidth_down 17038
    country_code "US"
    city_code 123456
    packet_loss 0.0
  ]
  edge [
    source 0
    target 0
    latency 50.0
    packet_loss 0.05
    label "edge from 0.0.0.0 to 0.0.0.0"
  ]
]
```

I'm not sure if we need the node to have `label "0.0.0.0"` for this to work or not.

**Comment by stevenengler** [comment]
Another downside we found is that the igraph implementation of GML is incomplete, and it cannot read graph attributes such as the GML attribute `directed` or the shadow attribute `prefer_direct_paths`.

**Comment by stevenengler** [comment]
We've decided to switch to GML, and have decided to make the following changes:

1. Use igraph to read GML rather than GraphML.
2. Remove the `prefer_direct_paths` topology graph attribute.
3. Add a `use_shortest_path` Shadow config option in the topology section.
    - Defaults to True.
    - If False, the graph must be complete. Otherwise Shadow prints a warning and fails.
    - Have tornettools generate the Shadow config with this option set to False since it's using the atlas graph, which is complete.
4. Update the topology and config conversion scripts.
5. Add a `type` field to the topology section of the Shadow config. The `type` will be either `graphml`, or any of the built-in topologies.

    Examples:

    ```yaml
    topology:
      use_shortest_path: true
      type: graphml
      path: ~/sdfdfsfd.graphml
    ```

    ```yaml
    topology:
      use_shortest_path: true
      type: graphml
      inline: |
    <xml>
    ...
    </xml>
    ```

    ```yaml
    topology:
      use_shortest_path: true
      type: 1_gbit_router
    ```

**Comment by stevenengler** [comment]
@robgjansen What do you think about putting some of the topology fields under a `graph` tag? So it would look something like:

```yaml
topology:
  use_shortest_path: true
  graph:
    type: gml
    path: ~/sdfdfsfd.gml
```

```yaml
topology:
  use_shortest_path: true
  graph:
    type: gml
    inline: |
      graph [
        ...
      ]
```

```yaml
topology:
  use_shortest_path: true
  graph:
    type: 1_gbit_router
```

The advantages are:
1. Since whether some fields (`inline` and `path`) are valid or not depends on the provided type, it maybe makes it nicer to separate these fields from other static fields like `use_shortest_path`.
2. The example in the earlier comment "flattens" the structure so that `inline` and `path` become part of the `topology` field, which means that we can't use `serde(deny_unknown_fields)` to raise an error if the topology includes unexpected fields.

**Comment by robgjansen** [comment]
Yes, great idea!!! The proposed structure seems intuitive to me.

Also, I'd like to propose renaming `topology` to `network`. As a single word name, I think `network` better represents the functionality provided by the module than does `topology`. See these wiki pages:
- [network science](https://en.wikipedia.org/wiki/Network_science)
- [network theory](https://en.wikipedia.org/wiki/Network_theory)
- [network topology](https://en.wikipedia.org/wiki/Network_topology)

(In all cases these are referred to as "networks".)

**Comment by stevenengler** [comment]
I think everything here is complete.
