### ISSUE TITLE
Setup test failure on Ubuntu 19.10

### ISSUE THREAD

**Issue by yihuajack** [shadow/shadow#781]
**Describe the issue**
Firstly I ran `./setup build --clean --test` but it gives build errors as follows.
[shadow_build.txt](https://github.com/shadow/shadow/files/4538765/shadow_build.txt)
Thus, I instead ran `./setup build --clean --test --debug` that it did not give any errors. Then I ran `./setup install`. However, when I ran `./setup test` then, the test failed. The output is:
[shadow_test.txt](https://github.com/shadow/shadow/files/4538775/shadow_test.txt)
I have not found the reason for this.

**To Reproduce**
Just exactly follow the documentation in a specific environment.

**Operating System (please complete the following information):**
 - OS and version: post the output of `lsb_release -d`  
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Ubuntu 19.10"
 - Kernel version: post the output of `uname -a`  
Linux ubuntu 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Shadow (please complete the following information):**
 - Version: post the output of `shadow --version`  
Shadow v1.13.2-553-g5669acda 2020-04-22 (built 2020-04-27) running GLib v2.62.4 and IGraph v0.7.1
 - Which plug-ins you are using:  
NaN

**Additional context**

**Comment by jtracey** [comment]
This looks like a character encoding problem. Try building and running shadow in a path with only ASCII in it. (Shadow has supported non-latin characters in the past, so my guess is the `??` in the path being used are non-UTF8 characters; that, or something broke in the python 2->3 conversion.)

**Comment by yihuajack** [comment]
It seems that a possible reason is though Shadow supports UTF-8, some dependencies do not.
