### ISSUE TITLE
Setup build error on Ubuntu 20.04

### ISSUE THREAD

**Issue by yihuajack** [shadow/shadow#783]
**Describe the issue**
After all the dependencies are installed, running `./setup build -c  -t` or debug test build, there is an error:
```[ 65%] Building C object src/preload/CMakeFiles/shadow-interpose.dir/interposer.c.o
/home/ayka-tsuzuki/Desktop/shadow/src/preload/preload_defs.h:143:25: error: conflicting types for ‘gettimeofday’
  143 | PRELOADDEF(return, int, gettimeofday, (struct timeval* a, struct timezone* b), a, b);
      |                         ^~~~~~~~~~~~
/home/ayka-tsuzuki/Desktop/shadow/src/preload/interposer.c:208:12: note: in definition of macro ‘PRELOADDEF’
  208 | returntype functionname argumentlist { \
      |            ^~~~~~~~~~~~
In file included from /home/ayka-tsuzuki/Desktop/shadow/src/preload/interposer.c:29:
/usr/include/x86_64-linux-gnu/sys/time.h:66:12: note: previous declaration of ‘gettimeofday’ was here
   66 | extern int gettimeofday (struct timeval *__restrict __tv,
      |            ^~~~~~~~~~~~
cc1: warning: unrecognized command line option ‘-Wno-static-in-inline’
make[2]: *** [src/preload/CMakeFiles/shadow-interpose.dir/build.make:63: src/preload/CMakeFiles/shadow-interpose.dir/interposer.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2719: src/preload/CMakeFiles/shadow-interpose.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
2020-04-27 20:49:14,385 [ERROR] Non-zero return code from make.
```
The complete output is:
[shadow_build(1).txt](https://github.com/shadow/shadow/files/4543378/shadow_build.1.txt)

**To Reproduce**
Run `./setup build -c  -t`

**Operating System (please complete the following information):**
 - OS and version: post the output of `lsb_release -d`  
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
 - Kernel version: post the output of `uname -a`  
Linux ubuntu 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Shadow (please complete the following information):**
 - Version: post the output of `shadow --version`  
Shadow v1.13.2-553-g5669acda 2020-04-22 (built 2020-04-27) running GLib v2.62.4 and IGraph v0.7.1
 - Which plug-ins you are using:  
None

**Additional context**

**Comment by yihuajack** [comment]
In addition, compiling with Clang also failed for the same error running `CC=/usr/bin/clang CXX=/usr/bin/clang++ ./setup build -ct`.
[shadow_build_clang.txt](https://github.com/shadow/shadow/files/4544105/shadow_build_clang.txt)

**Comment by sporksmith** [comment]
Merging with #805
