### ISSUE TITLE
Tor simulation acceptance tests

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#806]
We need to define a precise set of simulations and acceptable results of those simulations. The current Tor integration test is a step towards this, but we need more coverage before merging major changes. We at least need some sort of scalability/performance tests.

If some of these are relatively cheap we could add them to the CI executed on every PR. More expensive tests could be set up to run periodically (e.g. daily) or manually on major changes.

**Comment by sporksmith** [comment]
Assigning to @robgjansen for the moment to flesh this out a bit more; e.g. pointers to previous results we want to ensure can be replicated.

**Comment by robgjansen** [comment]
We've made some progress on this: we're running Tor in the CI in #1184, and larger nightly test results comparing incremental changes are pushed to [shadow/tornet-benchmark](https://github.com/shadow/tornet-benchmark).

**Comment by robgjansen** [comment]
Closing now, as we have minimal tests in place. Automatic performance/scalability tests are a bigger issue that should be split off if we want it.
