### ISSUE TITLE
Decide on which distros and versions we will support and document them

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#812]
We should
- [x] decide which distros and versions that we want to "officially" support,
- [x] document that we support those versions, and
- [x] document is what our expectations are for users when they find bugs in the "officially" supported versions vs. unsupported versions. 

A reasonable plan for unsupported versions is that we'll accept PRs to fix bugs in those versions, but don't plan to spend development effort on them.

**Comment by robgjansen** [comment]
I think we decided on:
- Ubuntu 16.04
- Ubuntu 1804 (already handled by the Github actions CI)
- Ubuntu 20.04
- CentOS 7
- CentOS 8
- Fedora 32
- Debian 9 "Stretch"

Did I miss any?

**Comment by armadev** [comment]
You probably want Debian 10 (Buster, aka current stable) if you want one Debian. If you want two Debians, doing stable and oldstable would be reasonable. But I think doing only current stable would be fine too.
