### ISSUE TITLE
Support phold performance evaluation

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#825]
In order to get a better sense of the performance differences between single-process Shadow and a process-based architecture, we want to be able to conduct performance evaluations using the phold test case in `src/test/phold`.

Ideally, we'll get phold working in both `ptrace` and `preload` mode so that we can compare single-process preload, multi-process preload, and multi-process ptrace. The evaluation may inform future development plans and strategy.

**Comment by sporksmith** [comment]
Currently works in ptrace-mode. Works in preload mode when using a [recompiled libc](https://github.com/shadow/shadow/blob/dev/docs/using-recompiled-libc.md)

**Comment by robgjansen** [comment]
Marking this as complete. Getting things working in preload mode *without* using the recompiled libc will be done in #892.
