### ISSUE TITLE
Support multi-threaded plugins

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#826]
In order to support the Tor use-case in the multi-process architecture, we'll need to be able to handle plugins that run multiple threads (because Tor uses multiple threads for its onion-skin CPU workers).

This requires us to support the `clone` syscall, and may also require some work to enable the `pthread` library to function correctly, at least the subset of the API that Tor uses.

**Comment by sporksmith** [comment]
Some subtasks:

- [ ] clone syscall (create new threads). #949 and #952
- [ ] futex syscall (synchronize across threads)
- [ ] Once futex is implemented, honor the `CLONE_CHILD_CLEARTID` flag in clone by doing a futex wakeup on the specified address when the child exits. e.g. this is used by pthread to join a child thread.
- [ ] set_robust_list syscall. This gives the OS (or Shadow, in this case) a list of futexes that should be woken up when the calling thread dies.- [ ] exit_group syscall. Right now it's unhandled, meaning we let it execute natively and don't do anything special. This is fine when there are no other threads. If there are other threads still alive, though, the native execution of exit_group will kill the native threads, but Shadow threads still need to be cleaned up.
- [ ] gettid syscall
