### ISSUE TITLE
File descriptor no longer valid after unlinking

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#852]
From `unlink(2)`:

> If the name was the last link to a file but any processes still have the file open, the file will remain in existence  until  the last file descriptor referring to it is closed.

We currently don't honor this behavior in cases where shadow uses `thread_nativeSyscall` to have the plugin open a file itself that was previously only open inside Shadow.

Notably, this causes a buggy interaction with `tmpfile(3)` and shadow's implementation of `mmap(2)`. Some implementations of `tmpfile` immediately `unlink` the file after creating it (e.g. on centos 7). If the plugin later tries to `mmap` the file, shadow tries to have the plugin open the original path, which no longer exists.

**Comment by sporksmith** [comment]
Proposal: in shadow's implementation of `unlink`, instead rename the file (to get it out of the way) and arrange for it to be deleted at exit (e.g. using `on_exit`).

**Comment by robgjansen** [comment]
I’m worried that keeping files around until the end of a large sim will become bad news really quickly.

Instead, we could keep a new hashmap in each host that maps `filepath->nfds` where nfds is the number of file descriptors with open handles to that file. Whenever `unlink()` is called, we decrement the nfds counter in the host map, and don't actually unlink the file until the counter reaches 0.

This is pretty trivial to implement, I think.

Note that when this is implemented, we should stop interposing `tmpfile()` in the shim.

**Comment by sporksmith** [comment]
Actually I *think* we might be able to just go ahead and unlink, and just use `/proc/<shadow's pid>/fd/<shadow's fd #>` as the path instead of using the original path.

**Comment by robgjansen** [comment]
How important is this bug to fix? I'm wondering if we should move to milestone 22 (https://github.com/shadow/shadow/milestone/22).

**Comment by sporksmith** [comment]
We have a workaround in place, so I think that's fine

**Comment by robgjansen** [comment]
I tried mapping `/proc/<shadow's pid>/fd/<shadow's fd #>` in the plugin, and it seems to work. PR coming soon.

**Comment by robgjansen** [comment]
Note: I also tried the following two approaches that did not work:
- re-linking the unlinked file using `linkat` (as described in `man 2 open`) -> this returns ENOENT
- opening a new file with `fopen`, copying the contents of the shadow fd using `fdopen`, `fread`, and `fwrite`, and mmaping that new file path -> this fails because I/O on the original descriptor will not be linked with the new fopened file
