### ISSUE TITLE
Handle file IO

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#857]
Rob, from https://github.com/robgjansen/shadow-phantom/pull/34#issuecomment-622372687:

> I am hoping to discuss during our next meeting our plan for supporting files. We can:
>   - have the plugins do the file io, which would require extending the shadow<->shim protocol so that we could swap the descriptor for every function that operates on files
>   - have shadow handle the file io on behalf of the plugins, which would require that the file io be transferred through the shmem interface as we already do with packets etc.
> I'm currently in favor of having shadow handle it. We could create a new `FileDescriptor` module that internally uses a real os file (and libc calls on it) to service the plugin calls, and then the descriptor benefits from the same listener/blocking logic as the other shadow descriptor types. One issue would be how to know when to change the readability/writability status of `FileDescriptors`; we basically need to epoll on them but shadow doesn't have an epoll loop. Ryan suggested that we could use another shadow support thread to do the epoll job, and when the epoll thread finds a `FileDescriptor` is ready, it adds an event to shadow's event queue to update the status of the associated `FileDescriptor`.

**Comment by sporksmith** [comment]
thread_nativeSyscall implemented in 300d9009a8ff514f72ab50052c94bcc897ab93ad

**Comment by robgjansen** [comment]
The file syscall handlers were merged in 7593cde5c4e40854350c60ff86c89d7c035e32dc.
