### ISSUE TITLE
Vagrant box no longer exists

### ISSUE THREAD

**Issue by michael-hahn** [shadow/shadow#872]
Vagrant box `boxcutter/fedora22` used to set up Shadow is no longer available on VagrantCloud.
You can reproduce this bug simply by `vagrant up` the Vagrantfile provided in the documentation.
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'boxcutter/fedora22' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'boxcutter/fedora22' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/boxcutter/fedora22"]
Error: The requested URL returned error: 404 Not Found
```

**Comment by michael-hahn** [comment]
It seems like simply using a different Fedora 22 box works:
```config.vm.box = "bento/fedora-22"```
Happy to further verify, but OK to close this issue if not needed.

**Comment by robgjansen** [comment]
Yeah, it's probably best to just install from a clean VM in a more recent OS following the manual setup instructions:
https://github.com/shadow/shadow/blob/master/docs/1.1-Shadow.md

**Comment by stevenengler** [comment]
We removed the Vagrant documentation in https://github.com/shadow/shadow/pull/1044 as it's out-of-date and it's difficult to keep up to date since none of the core Shadow developers use it anymore.
