### ISSUE TITLE
Use shared memory and spinlocks for Shadow-to-plugin IPC

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#894]
After some performance analysis, we've discovered that UNIX sockets and semaphores have very high overhead per context switch between shadow and the plugins it is running. Most of the time is spent waiting for the other side of the channel to signal a wakeup.

Some initial rough tests show that shared memory and spinlocks can improve performance as much as 100x.

Of course, we don't want to spin forever and burn CPU cycles; we want an intelligent algorithm that each side of the IPC channel first tries the spinlock for some amount of time, and if the channel isn't ready by that time, it falls back to using semaphores.

It probably makes sense to do this in multiple steps:
- [x] (merged in #924) Change our shadow-to-plugin channel from sockets to shared memory with spinlocks
- [x] (merged in #924) Implement the part of the algorithm where we eventually give up on the spinlock and fall back to the semaphore.
- [x] ~Support dynamic computation of the number of spins before falling back to semaphore~
- [ ] Pick some reaonable upper bound on the spin time, and print a warning when that time is reached and we fall back to the semaphore

Useful links:
- https://github.com/goldsborough/ipc-bench
- https://stackoverflow.com/questions/2854004/ipc-speed-and-compare

**Comment by sporksmith** [comment]
>  Support dynamic computation of the number of spins before falling back to semaphore

This is *probably* obsoleted in favor of spinning until shadow sends an explicit "stop spinning" message (#992). Keeping open for now, pending further benchmarking.

**Comment by sporksmith** [comment]
Current plan is to pick some relatively high upper bound (on the order of a second), and log a warning when we actually hit it.

**Comment by sporksmith** [comment]
Closing. We've found that while spinlocks can have very low latency, it has to use twice as many CPUs to do so, resulting in less throughput overall.
