### ISSUE TITLE
remove dependency on python2.7

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#9]
Figure out what is forcing us to use python2.7 in our setup.py and src/shadow scripts. See if we can re-write it in a version agnostic way to remove the dependency on 2.7 (while keeping the dependency on python in general).

**Comment by kjacks21** [comment]
If it helps, the only things I had to change in order to successfully build and install shadow using python 3 is remove the `urllib2` import from setup (not sure if this has to do with py 2 vs py 3, but had to do it on two systems) and change all the `xrange` to `range`.
