### ISSUE TITLE
Tests show as passing even if they do not complete before the stop time

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#902]
**Describe the issue**
If the test takes longer than the stop time, or if the test gets stuck, Shadow will eventually kill the process but still return 0 as the exit code. This causes ctest to think that the test passed, even though it didn't complete.

**To Reproduce**
Run a test with a blocking call and a timeout. For example, run a test that calls `sleep(10);` but with `<kill time="5"/>`.

**Shadow (please complete the following information):**
 - Version: post the output of `shadow --version`  
The dev branch as of at least `17b9e45430c06`.

**Comment by sporksmith** [comment]
This is a good observation, but a bit tricky to fix because some tests are designed to run until the simulation end time is reached. I think this is also the norm for most "real" simulations - e.g. tor nodes will still be running when the simulation ends.

**Comment by stevenengler** [comment]
Tor I think should be fine since it returns 0 on SIGTERM, but for other software it might be unexpected. I think it would be useful to have two options here, "stop time" to send a SIGTERM and continue to run Shadow until the processes exit, and a "kill time" to send a SIGKILL and return the exit code.

This is causing our tests to think that `timerfd-shadow-ptrace` passed when it's actually timing out. And `phold-shadow-ptrace` will fail as well, but it's designed to run forever.

**Comment by sporksmith** [comment]
Seems like a promising approach. I suppose then we'd modify phold to catch SIGTERM and shutdown gracefully.

@robgjansen wdyt?

**Comment by stevenengler** [comment]
> Seems like a promising approach. I suppose then we'd modify phold to catch SIGTERM and shutdown gracefully.

I did a little more testing, and it seems that shadow-ptrace doesn't yet allow you to catch signals, so that will need to be supported first. And shadow-preload does work, but I'm not convinced it will work properly all of the time because of the read() loop within the shim. But as long as the signal is sent when the program is not within a system call (or waiting on an event in general), I think it will be fine.

**Comment by robgjansen** [comment]
Updating tests to use macros so that we always arrange to check the plugin return code; see #1114, #1116, #1117, #1123, and #1131.
