### ISSUE TITLE
Enable logging from Rust code

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#915]
Currently our new Rust code is not using logging, but we'll want to be able to log things from Rust and this will become more important as we continue to write/migrate more code in/to Rust.

Shadow uses a custom logger that is written to be performant in simulations consisting of many Shadow worker threads. We should enable Shadow's logging interface to be accessible from Rust. We think we can do this by writing Rust wrappers around Shadow's logger and follow the idiomatic way of installing custom loggers in Rust.

**Comment by stevenengler** [comment]
Closed in #933.
