### ISSUE TITLE
phold off-by-one error

### ISSUE THREAD

**Issue by rwails** [shadow/shadow#951]
**Describe the issue**

The phold test has an off-by-one error in the way hosts talk to each other / are weighted. I think the weights file should contain `n` lines for `n` hosts, but seems to only require `n-1` lines. One host during the experiment doesn't receive traffic from the other hosts.

(rwails to fill in more.)

**To Reproduce*

Run phold :-)

**Comment by RWails** [comment]
Fixed from #976.
