### ISSUE TITLE
Support optional real-time scheduling mode

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#964]
In our new process-based architecture, we may get a performance boost if we can reduce unnecessary context switches by utilizing a non-default CPU scheduler to run the shadow and plugin threads. Using a real-time scheduler like `SCHED_FIFO` will give us tighter control over when context switches will occur.

We think it's worth supporting a real-time scheduling mode as an optional run-mode, so that we can test if it provides a performance boost. In order for us to be allowed to use a real-time mode, support needs to be configured on the simulation host via ulimit.

More info:
- https://man7.org/linux/man-pages/man7/sched.7.html
- https://man7.org/linux/man-pages/man2/sched_setscheduler.2.html

**Comment by sporksmith** [comment]
Done in #1118
