### ISSUE TITLE
Signal plugin when Shadow will block on a syscall

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#965]
Currently in preload mode, the plugin makes a syscall and then spins until shadow gives it an answer. But sometimes Shadow needs to block before the ssycall can be completed, for example when it is waiting for a packet to read data. In this case, Shadow should send a message back to the plugin to inform it that we will be blocking it. This can be used as a signal so the plugin can stop spinning and instead do a `semaphore_wait()` call.

This strategy could allow us to avoid implementing an algorithm to dynamically compute the "optimal" spin time (as requested in #894), because we could just always spin until we get a response from Shadow.

**Comment by sporksmith** [comment]
Next: enable by default, but leave the toggle in for tor benchmarks
