### ISSUE TITLE
Re-enable or replace tcp tests

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#974]
In the dev branch, the whole directory `src/test/tcp` is disabled in `src/test/CMakeLists.txt`.

The tests there use a wrapper script to create a message queue and set its name in an environment variable. The server process can then communicate an (ephemeral) port number to the client process.

However, in the dev branch, plugins don't inherit shadow's environment variables, so this mechanism doesn't work.

The solution I'm leaning towards:

* Propagate environment variables with the prefix `SHADOW_TEST_*` from shadow's environment to the plugin's environment. A slightly more general version is to add command-line and/or config options to whitelist specific environment variables to be propagated.

Alternatives considered:
* Propagate all of shadow's environment to plugins, to preserve the behavior of the master branch. In previous discussions we decided to avoid this in favor of making the simulation more hermetic. This would be an easy fix though, and I'm a little hard-pressed to come up with problems it might cause in practice.
* Add command-line and/or config options to Shadow to specify extra environment names and their values to be set in the plugin. This might be generally useful, though actually is a little awkward in this case. Right now a wrapper script `with_q.sh` creates the queue, exports the env variable, and then calls the specified command. It is also used for running the native tests and isn't Shadow aware. We'd need to make it Shadow-aware for this option to work.
* Pass the message-queue names via the plugin's command-line arguments instead the environment. Since the plugin's command-line arguments are specified in the xml config, we'd either need to do some templating to substitute in the ephemeral queue name on the fly, or hard-code the queue names in each xml config. Neither of these are very appealing.
* Use hard-coded port numbers. The tests used to do this, but it resulted in flakiness due to the hard-coded numbers sometimes being unavailable.
* Use hard-coded port numbers when running under Shadow. This is conceptually simple, but means a somewhat different code-path when running under Shadow vs running natively.

We've also discussed dropping these tests in favor of replacements to be written in Rust; however we'd need to solve the same problem in those as well.

**Comment by stevenengler** [comment]
Another possible option we discussed:

- Have the tests take a port number as an argument. For the Shadow tests, the xml configs could have hard-coded port numbers for the argument. For the non-Shadow tests where we do not want to hard-code the ports, we could use test_launcher to find an unused port by binding to port 0 with the `REUSEPORT` socket option, using `getsockname()` to get the port, and passing the port number as the argument to the tests. The `REUSEPORT` option allows us to avoid race conditions.
