### ISSUE TITLE
Segmentation fault while porting golang on shadow due to a TLS related problem. 

### ISSUE THREAD

**Issue by Emegua** [shadow/shadow#983]
**Describe the issue**
We wrote a very simple golang program and build it as a C-shared library. We run the library as a shadow plugin. Our simple golang program includes an empty main function, and we instrumented Shadow so that it can correctly find the main function symbol of the plugin. However, while executing the main function, the Shadow results in a segmentation fault during the initialization of the plugin.

The initialization process initializes the runtime library by importing different packages. Shadow enters to the plugin initialization program by calling the thread start routine inside _process_executeChild function.

**To Reproduce**
I don't think you would be able to reproduce the case directly since we have changed some parts of the Shadow emulator, but the explanation that I will put would be helpful to understand the case. I also encountered a somewhat-related problem when running a shared library written in C as a Shadow plugin; I will submit another issues for that. 

**Operating System (please complete the following information):**
Description:	`Ubuntu 18.04.5 LTS`
 - Kernel version: post the output of `uname -a`  
`Linux ***-B85M-D3H 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
**Shadow (please complete the following information):**
 - Version: post the output of `shadow --version`  
`Shadow v1.12.1-172-ge74d774c 2020-08-05 (built 2020-09-12) running GLib v2.56.4 and IGraph v0.7.1`

 - Which plug-ins you are using:  
Shadow-golang plugin (we build the plugin by ourselves.)

**Additional context**
I observed that there were 4 golang threads before it reaches the segmentation fault. (4 Emulated threads.)
1. mainGO thread (that runs the main function for our plugin)
2. a thread to initialize the golang runtime (Created by thread 1)
3. system monitor thread (sysmon thread) ((Created by thread 2)
4. I don't exactly know what the main function of this thread is yet. (I don't think its function is relevant for our discussion though.) (Created by thread 2)
 
In golang, there could be more than 1 [goroutine](https://golangbot.com/goroutines/#:~:text=Goroutines) in 1 thread. Each thread has its own TLS variable called <runtime.g> that holds the current goroutine, a pointer to a g struct. 

Without using shadow, loading the shared library with dlsym, and using dlmopen works fine. In this case, all threads have a distinct value for the TLS variable (runtime.g). Whereas in Shadow, all threads have the same (pointer) value for TLS variable(runtime.g), but this (same) pointer indicates different values when it is used by different threads

As long as it points to the correct value for each thread, I don't think having the identical TLS variable value is an issue. Specifically, when a new thread runs, this is not a problem since its value is set inside the thread start routine functions of golang. However, when a thread that was in a waiting state starts to run, its TLS variable points to the previously-running thread’s value. For example, lets say the TLS value is `0x7fbe008d9b18`.

For thread 2 it points to `0xc420000a80`,

For thread 4 it points to`0xc420031500`,

But when thread 4 yields the CPU and thread 2 starts to run, the TLS value still points to `0xc420031500` (the 4th thread’s values). The data of thread 2 is not erased, I checked that by printing the value of `0xc420000a80`. It is just that its TLS value is not pointing to the correct value.

I am suspecting that there could be a problem when shadow emulates multi-threaded applications. Maybe some values are not being set correctly during swapcontext.

______________________________________________
As per @robgjansen suggestion, I tried running shadow by disabling work stealing as follows
`shadow --scheduler-policy=host …`
and just using 1 worker thread as follows. 
`shadow --workers=1 …` 
But the segmentation fault doesn't disappear.

**Comment by Emegua** [comment]
The problem might be similar with [](https://github.com/shadow/shadow/issues/984#issue-701553626).

**Comment by Emegua** [comment]
The TLS variable `runtime.g` was declared as 
`static __thread G *g;`

**Comment by robgjansen** [comment]
Thanks for the detailed reports! I do agree that this is likely a duplicate problem to #984; I think fixing #984 would also fix this issue. Let's focus our discussion on #984 since it will be easier to work with the C example there.

I'm going to close this one for now. If #984 gets fixed and this problem still exists, feel free to re-open.
