### ISSUE TITLE
Add method to convert plugin virtual to physical addresses

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#996]
The futex syscall uses memory addresses as an ID that can be used to uniquely identify a futex object. However, normally the kernel converts the virtual memory address passed by the futex caller into a physical address based on page table and index. This guarantees that the address is unique across processes.

We should handle this virtual to physical address conversion. This is currently stubbed out in [`process_getPhysicalAddress`](https://github.com/shadow/shadow/blob/b9797048a196906b15d1435cf24ad4c1194aac7e/src/main/host/process.c#L614) in `process.c`.

**Comment by sporksmith** [comment]
Double-check that we don't have a potential collision issue; otherwise we can move this to next milestone
